{
  "hash": "a3dbc6e8eea663ec33044af6dd6e6729",
  "result": {
    "engine": "knitr",
    "markdown": "# Explanation and prediction {#sec-explanation-prediction}\n\nIn 2017, a group of researchers issued an unusual challenge. The Fragile Families study had followed thousands of American children born around 2000, interviewing their families at birth and at ages one, three, five, and nine: nearly 13,000 variables per family, feeding a literature of over 750 published articles. The challenge: using everything measured through age nine, predict six outcomes at age fifteen, among them the child's grade point average and whether the family would be evicted. One hundred sixty teams tried, using every method from linear regression to deep learning, scored on families they had never seen. The best predictions were poor. For the two easiest outcomes the best team explained roughly 20% of the variance; for the other four, between 3% and 6%. A benchmark regression using just four variables chosen by a domain expert came close to the winners [@salganik2020].\n\nHundreds of papers had explained these children's development, or so their titles claimed, yet the same data could not predict those children's lives much better than guessing the conditional average based on four variables. The gap points to a problem in how we think about understanding. For four chapters you have fitted models in order to interpret their parameters: the effect of a policy, the share of variance between schools. In the chapters ahead you will fit models in order to predict, and their parameters may interest nobody. This chapter asks what a prediction is, what it is good for when nobody asks for an explanation, and what predicting well has to do with explaining well.\n\n## Prediction as a statement about unseen data\n\nA prediction is a statement about data you have not seen. The data may lie in the future but need not: predicting the outcomes of last year's held-out patients, whose files you never opened, is prediction. What matters is that the model was fixed before the answer was known.\n\nScience has always used prediction in this sense to test theories. A theory implies statements about observations, and once the observations are made, the theory either survives or does not. You have already done this, in @sec-theory-to-glm, perhaps without noticing. A path model implies correlations, via the tracing rules, and the chi-square test asked whether the observed correlations matched them. Every claim of absence was a commitment about data not yet consulted. Testing an explanation and checking a prediction are the same act.\n\nAggregate models make the same move at larger scale. The SIR model of epidemics [@kermack1927] divides a population into susceptible, infected, and recovered persons and predicts a characteristic wave: rise, peak, decline. Real epidemics follow the wave roughly, and each departure from it, from superspreading to waning immunity, forced a better model. The DeGroot model of opinion dynamics [@degroot1974] predicts that people who keep averaging their opinions with their neighbours' will converge to consensus. Real populations do not reach consensus. The model, taken literally, is false, and its failure is informative, since whatever blocks consensus (stubbornness, homophily) is what a better theory must contain. Sociologists in the tradition of @coleman1990 and methodologists like @kkv1994 treat such observable implications as what gives a social theory its value: a theory that implies nothing checkable has none.\n\nA verbal theory, however, usually implies far less than its authors think, and testing \"the theory predicts a difference in the expected direction\" is a weak test; almost any theory passes it [@yarkoni2022]. Meehl's old complaint applies: a theory of climate that predicts it will rain *sometime* next April earns no credit when it does, and \"more rain in April than in May\" impresses nobody, \"even showing three asterisks\"; a theory that predicts how many inches will fall on which April days, and gets seven of them right within tolerance, is starting to look like science [@meehl1978, pp. 817-818]. One diagnosis of the replication crisis is this mismatch between sweeping verbal claims and the weak statistical statements offered as their tests. Predictive performance on data the model has not seen is a test that verbal theorizing alone cannot pass.\n\n::: {.callout-tip icon=\"false\" title=\"Exercise 5.1\"}\nFor each claim, state one concrete prediction it makes about unseen data, and one observation that would embarrass it. (a) The DeGroot model of opinion dynamics. (b) The mediation model of @sec-identification with no direct effect ($X \\to M \\to Y$ only). (c) \"Vocational education helps early careers but hurts late ones\" [@forster2016].\n:::\n\n::: {.callout-note collapse=\"true\" icon=\"false\" title=\"Answer 5.1\"}\n(a) Repeatedly interacting groups should drift toward agreement; stable long-run polarization in such groups embarrasses it. (b) The implied correlation restriction $\\rho_{XY} = \\rho_{XM}\\rho_{MY}$ in fresh data; a clearly larger $\\rho_{XY}$ embarrasses the exclusion. (c) In a new cohort, the employment gap between vocational and general graduates should be positive at labour-market entry and turn negative around mid-career; a gap that stays flat or grows with age embarrasses the reversal claim. In each case the theory earns credit only in proportion to how easily it could have failed.\n:::\n\n## Prediction in its own right\n\nPrediction has a second job that needs no theory at all: sometimes an uncertain forecast is better than none, because a decision has to be made. Economists put the distinction in two images [@kleinberg2015]. Deciding whether to carry an umbrella requires only a forecast of rain: the umbrella does not change the weather. Deciding whether to perform a rain dance requires a causal claim: the dance pays only if it makes rain. Umbrella problems are common. Which arriving patients should be fast-tracked? Which defendants will appear for trial? Which households should an anti-poverty programme visit first? Each of these decisions requires identifying the right people, and does not require knowing the causes.\n\nFor most of the twentieth century, mainstream statistics in the social and health sciences paid little attention to such problems. @breiman2001 described the split in a paper whose argument has held up well. Statistics, he wrote, contains two cultures. The data-modelling culture, which he estimated at 98% of statisticians, assumes a stochastic model and interprets its parameters, validating by goodness of fit. The algorithmic-modelling culture, his 2%, treats nature's mechanism as unknown, seeks any function that predicts well, and validates on held-out data. His warning to the 98% was that conclusions from a fitted model are about the model's mechanism, and \"if the model is a poor emulation of nature, the conclusions may be wrong\". Twenty years on, his advice is mostly vindicated, and @sec-overfitting and @sec-evaluation go into more depth.\n\n@shmueli2010 explains why a model built without regard for truth can predict better than a model built to be true: prediction error has two parts, error from bias (the model is wrong) and error from variance (the estimates are noisy), and a deliberately simplified, \"wrong\" model often wins by trading a little bias for a lot of variance. @sec-overfitting treats that tradeoff in full. For now, explaining well and predicting well are different objectives, optimized by different models, and neither can be read off from the other.\n\nA simulation, in which we know the true data-generating process, shows the two objectives diverging. Take a moment to read through this code and the comments.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1015)\n\ng <- 3         # spurious relationship is g^2\nb <- 0.15       # direct effect from medication to symptoms\nn_train <- 20  # \"training\" sample size (used for fitting model)\n\n# This function is the data-generating process (DGP). It returns random data\n#.  from our population.\ngenerate_data <- function(n) {\n  medication <- rnorm(n) # A truly causal factor with a small effect\n  motivation <- rnorm(n) # An (later unobserved) confounder\n  exercise   <- g*motivation + rnorm(n) # The motivated exercise more\n  \n  # Symptoms are *not* improved by exercise, but only by motivation and medication\n  symptoms   <- g*motivation + 0*exercise + b*medication + rnorm(n)\n  \n  # In the data we do not observe the confounder, motivation:\n  return(data.frame(symptoms, exercise, medication))\n}\n\n# These are the observed data we can use to fit a predictive model:\ndf_observed <- generate_data(n_train)\n\n\n# The model with only the true cause \"medication\": \nfit_true  <- lm(symptoms ~ medication, data = df_observed)\n# The model with both the true cause \"medication\" and the spurious factor \"exercise\":\nfit_best  <- lm(symptoms ~ exercise + medication, data = df_observed)\n# The model with _only_ the spurious factor \"exercise\":\nfit_wrong  <- lm(symptoms ~ exercise, data = df_observed)\n\n# Now let's evaluate how our models can be expected to perform on completely \n#.   newly generated data from the same population.\ndf_test <- generate_data(1e5) # n is just set to a big number \n\n# Evaluate the root-mean squared deviation (residuals)\nrmse <- function(m) {\n  sqrt(mean((\n    df_test$symptoms - predict(m, df_test))^2\n  )) |> round(2)\n}\n\n# Model performance in unseen data from the same population (lower is better):\ndata.frame(true = rmse(fit_true), \n           best = rmse(fit_best), \n           wrong = rmse(fit_wrong))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  true best wrong\n1 3.25 1.49  1.42\n```\n\n\n:::\n:::\n\n\nIn the code above, \n\n * The \"true\" model  includes only the truly causal factor `medication`. Its [root-mean squared error](https://en.wikipedia.org/wiki/Root_mean_square_deviation) is high (RMSE = 3.25), because although `medication` has a true effect, the effect is relatively small;\n * The \"best\" model includes *both* the truly causal factor `medication` and the spurious factor `exercise`. It could be expected to be the \"best\" in terms of prediction, because both variables have predictive value for the outcome, even though changing `exercise` does nothing for symptoms. Indeed, its performance is much improved (RMSE = 1.49). However, in spite of its name, in this sample it is *not* the best;\n * The \"wrong\" model includes *only* the spurious factor `exercise`, and *not* the true causal factor `medication`. So this model can tell us nothing on how to improve symptoms. But this \"wrong\" model *is* actually the best in predictive terms, with an root-mean-squared error of only 1.42.\n\nThis -- perhaps surprising -- example demonstrates that the search for \"true\" (explanatory) models is not necessarily the most helpful if we are only trying to get the best possible prediction. At the same time, it also shows that highly predictive models are not necessarily helpful if we want to learn how to improve the outcome: it is very tempting for a doctor who has not seen our DGP to take the above prediction model and use it to advise their patients to exercise. This shows that establishing the goal of the analysis is extremely important. As argued in this chapter, that goal should sometimes be to just predict instead of (or in addition to) explain the phenomenon at hand.\n\n::: {.callout-tip icon=\"false\" title=\"Exercise 5.2\"}\nExtend the chunk above as needed. (a) Which of the three models gives the right answer to the causal question: would prescribing exercise change symptoms? (b) Which model should a clinic use to forecast symptom burden, and why? (c) Running `coef(fit_wrong)` puts `exercise` at about $0.99$. A doctor reads this as \"each unit of exercise changes the symptom score by about one point\". What can the printed output tell her about whether that reading is safe? (d) A principled analyst refuses to use any variable without causal standing and sticks to `fit_true`. What does the refusal cost, and what does it buy?\n:::\n\n::: {.callout-note collapse=\"true\" icon=\"false\" title=\"Answer 5.2\"}\n(a) None of them. The true effect of exercise is zero by construction, but `fit_wrong` and `fit_best` both attach a coefficient of about $0.99$ to it, because the confounder, motivation, is not in the observed data: no regression on these three columns can hold it constant. Adding the true cause `medication` (going from `fit_wrong` to `fit_best`) does not repair the exercise coefficient at all. The only model that avoids making a false causal claim about exercise is `fit_true`, and it does so by staying silent on the question. (b) `fit_wrong`, which has the lowest error on new data (1.42), with `fit_best` close behind (1.49); forecasts are judged on held-out error, and exercise carries real signal about symptoms regardless of its causal role. (c) Nothing. The printout for the confounded exercise coefficient looks exactly like the printout for the unconfounded medication coefficient: same standard errors, same stars. Which coefficients have causal standing is settled by design and assumptions, never by the fitted output. (d) The refusal costs predictive accuracy (3.25 against 1.42) and buys causal interpretability for the one variable it keeps: because `medication` was assigned independently of everything else, its coefficient is an unbiased estimate of a real effect. Even that purchase is partial, though. With `n_train = 20` the estimate is $-0.55$ where the truth is $+0.15$: the estimate of the one genuinely causal effect does not even have the right sign. Unconfounded is not the same as precise, and a causal design does not excuse a small sample.\n:::\n\n::: {.callout-tip icon=\"false\" title=\"Exercise 5.3\"}\nThe result that the \"wrong\" model beats the \"best\" one is not a law of nature; it depends on the three quantities set at the top of the chunk. Change them, rerun, and report what you find.\n\n(a) Increase `n_train` from 20 to 100, and then to 500 (change the seed a few times at each value, since any single run is noisy). When does `fit_best` start to beat `fit_wrong`, and why?\n(b) Reset `n_train` to 20 and increase the causal effect `b` from 0.15 to 0.5, and then to 1. What happens to the contest between `fit_best` and `fit_wrong`, and to the standing of `fit_true`?\n(c) What does `g` govern, and which comparison does changing it affect most?\n(d) Summarize your findings in one sentence about when leaving a true cause *out* of a model improves prediction.\n:::\n\n::: {.callout-note collapse=\"true\" icon=\"false\" title=\"Answer 5.3\"}\n(a) With `b = 0.15`, `fit_wrong` wins in roughly two thirds of samples at `n_train = 20`, in about a third at 100, and almost never at 500. Including `medication` costs the variance of estimating one extra, nearly-useless coefficient and buys the removal of a tiny bias; the cost shrinks with $n$ while the bias does not, so somewhere around $n$ in the low hundreds the balance tips and the fuller model wins from then on.\n(b) Raising `b` makes `medication` genuinely informative: at `b = 0.5` the \"wrong\" model wins only occasionally at `n_train = 20`, and at `b = 1` essentially never. `fit_true` also improves relative to the other two, since the variable it keeps now carries real signal.\n(c) `g` sets the strength of the confounding, and thereby how much predictive value the spurious variable carries: x. Changing `g` mostly moves `fit_true`'s standing relative to the other two, since they both ride on exercise; the `fit_best`-versus-`fit_wrong` contest is governed by `b` and `n_train`.\n(d) Omitting a true cause improves prediction when its effect is small enough, and the sample small enough, that the variance of estimating it exceeds the bias of ignoring it; more data or a bigger effect flips the verdict. That is the bias-variance trade-off of @shmueli2010 in a single decision, and @sec-overfitting builds the general machinery.\n:::\n\nSo far the argument has been that prediction is a goal in its own right, separate from explanation. There is a complementary argument: predictive checks are useful *within* explanatory research, even when nobody intends to forecast anything. @verhagen2022 makes this case for the social sciences. His starting observation is that predictive evaluation is nearly absent from explanatory practice: in six leading journals of economics, sociology, and political science, fewer than 5 percent of abstracts mention prediction at all. What is lost, he argues, is basic information about the models whose coefficients we interpret. A coefficient can be statistically significant in a model that captures half of the outcome's variation or one that captures a thousandth of it, and the significance test does not distinguish the two; computing predictive performance, which any fitted model can do at no extra cost, does. The information becomes sharper still when performance is computed per group rather than overall. Verhagen's leading example is a well-known analysis of discrimination in mortgage lending: the fitted model describes White applicants' outcomes well and non-White applicants' outcomes much worse, so its conclusions rest on a model that fits the group under study worst. The coefficient table does not reveal this, but a group-wise predictive check does.\n\n@yarkoni2017 draw a related but distinct lesson for psychology. Their broader argument is that psychology should take prediction seriously as a goal in its own right. They also point out something that matters even for pure explainers: the questionable research practices behind the replication crisis, the fishing and flexible analysis of @sec-rq-to-interpretation, are recognizable to a machine learner as **overfitting performed by hand**. A researcher who tries many specifications and keeps the one with the significant result has fit the noise in one dataset, just as an unconstrained algorithm would, and the failure shows up the same way: the finding does not hold in new data. The remedies machine learning developed for its version of the problem, holding out data for evaluation and penalizing flexibility, are therefore also safeguards for explanatory research. Both papers arrive at the same practical advice: whatever your goal, evaluate your model's predictions, and trust it in proportion to how well it predicts.\n\n## One decision, two questions\n\nA hospital loses money when booked patients do not show up: the slot stands empty while another patient waits weeks for it. So the hospital builds a model that flags likely no-shows, and staff call just those patients with a reminder. This decision needs a forecast of which patients, left alone, would skip. It also affects the outcome: a phone call can change whether a patient comes.\n\nRecall the two images from earlier in this chapter [@kleinberg2015]. An *umbrella* decision depends on an outcome without touching it: whether to carry an umbrella depends on rain, but the umbrella does not change the weather, so a forecast is all the decision needs. A *rain-dance* decision pays off only by changing the outcome: the dance is worthwhile only if it actually makes rain, so a causal claim is what the decision needs. Kleinberg and colleagues expressed this distinction in one line of calculus, and the hospital example gives each symbol a concrete meaning.\n\nThree quantities are in play, drawn in @fig-umbrella-raindance. The **action** $X_0$ is what the hospital controls: call a booked patient with a reminder, or not. The **outcome** $Y$ is the part of the world the payoff depends on: whether the patient shows up. And the **payoff** $\\pi(X_0, Y)$ is what the hospital ultimately cares about, the net benefit of the clinic day, which depends on both: on the action, because calls cost staff time and because knowing a no-show is coming lets the clinic rebook the slot, and on the outcome, because a kept appointment is the point of the whole exercise. The question every decision-maker faces is: what happens to the payoff if I act? In symbols, what is $d\\,\\pi / d X_0$? The chain rule splits the answer in two:\n\n$$\n\\frac{d\\,\\pi(X_0, Y)}{d X_0} \\;=\\; \\underbrace{\\frac{\\partial \\pi}{\\partial X_0}\\,(Y)}_{\\text{prediction part}} \\;+\\; \\underbrace{\\frac{\\partial \\pi}{\\partial Y}\\,\\frac{\\partial Y}{\\partial X_0}}_{\\text{causation part}}\n$$\n\n![The two kinds of decision, drawn for the hospital example. In panel (a) the action affects the payoff only directly: whether calling is worthwhile depends on what the patient would do anyway, so the decision needs a *prediction* of $Y$. In panel (b) the action also changes the outcome itself: the arrow $\\partial Y/\\partial X_0$ is a causal effect, and the decision needs a causal estimate of it. Most real decisions contain both arrows.](images/umbrella-raindance.png){#fig-umbrella-raindance width=\"95%\" fig-align=\"center\"}\n\nThe two terms can be read one at a time, each with the hospital in mind.\n\nThe **first term**, $\\partial \\pi / \\partial X_0$, asks: holding the patient's behaviour fixed, how does calling change the payoff? Suppose for a moment that the call has no influence on anyone, as in panel (a) of @fig-umbrella-raindance. Calling still matters, because its value depends on what the patient was going to do. Calling someone who would have shown up anyway costs a few minutes of staff time and gains nothing. Calling someone who was going to skip lets the clinic rebook the slot before it stands empty. So even with no causal effect anywhere, the hospital profits from calling the *right* patients, and choosing the right patients requires one input: a good prediction of $Y$. This is the umbrella term: just as the umbrella does not change the rain, the call in this term does not change the patient, and the value of the action depends on knowing what will happen.\n\nThe **second term** asks the rain-dance question: does the call itself change whether the patient shows up? It is a product of two pieces. The piece $\\partial Y / \\partial X_0$ is the causal effect of the call on attendance, panel (b)'s purple arrow: a reminder may jog a forgetful patient into coming. The piece $\\partial \\pi / \\partial Y$ translates that change in attendance into payoff: a patient who now shows up fills a slot that would have gone empty. Using this term requires what the whole first half of this book was about, a credible causal estimate, and no forecast can substitute for it: a model that predicts attendance perfectly can still be silent about what a *call* would do to attendance.\n\nKleinberg's point is that decisions differ in which term dominates, and that the difference dictates the kind of research the decision needs. When the second term is (near) zero, as with the umbrella, prediction is the entire problem, and demanding a causal interpretation of a forecasting model asks for something the decision will not use. When the second term is substantial, no amount of predictive accuracy certifies the decision, because $\\partial Y / \\partial X_0$ is a causal quantity that held-out data do not contain. Real reminder policies involve both terms at once, because patients adapt. A clinic that reliably reminds its likely skippers teaches them to wait for the call, and when one day no call comes, they skip more often than before the policy existed. That is the causation part with the wrong sign, and a hospital that evaluates its model on forecasting accuracy alone will not detect it.\n\n@hofman2021 make the same point at the scale of a research field. Reviewing computational social science, they sort studies along two dimensions that by now should look familiar. The first is whether a study aims to *explain*: to identify and estimate causal effects, the second term of the payoff. The second is whether a study *tests its predictions*: whether its claims are evaluated against data the model has not seen, the discipline behind the first term. Crossing the two dimensions gives four kinds of research:\n\n|  | **predictions not tested out of sample** | **predictions tested out of sample** |\n|---|---|---|\n| **no causal ambition** | descriptive modelling | predictive modelling |\n| **causal ambition** | explanatory modelling | integrative modelling |\n\n: The organization of research proposed by @hofman2021: what a study estimates (rows) crossed with how it is validated (columns). {#tbl-hofman}\n\nMost quantitative social science, including most of what the first four chapters of this book covered, sits in the lower-left cell: models with causal ambitions whose predictive performance is never checked. Most machine learning sits in the upper-right: models checked rigorously on held-out data, with no causal ambitions at all. Each cell inherits the weakness the payoff formula predicts for it. Work in the lower-left makes rain-dance claims whose predictions are never tested: its estimated effects may be credible, but nobody knows whether the model captures enough of the outcome to matter, which was Verhagen's complaint above. Work in the upper-right can fail as soon as a policy changes the world it learned from, because everything it knows is an association in the training distribution, which was the Google-Flu-style failure and the adapting patients of the reminder example.\n\nThe sparsest cell, Hofman and colleagues report, is the lower-right, which they name **integrative modelling**: research that estimates effects credibly *and* tests whether its predictions survive out of sample, including under interventions and in shifted circumstances. That cell is where the two terms of the payoff meet: a decision-maker who must weigh both terms needs a model whose causal claims are identified and whose predictive claims are verified. Their recommendation follows directly: judge a claim of understanding on both performances at once. A high $R^2$ without a design is not understanding, and neither is a clean identification strategy for a model that explains almost nothing of what happens.\n\n::: {.callout-tip icon=\"false\" title=\"Exercise 5.4\"}\nClassify each decision as mainly a prediction problem (the first term), mainly a causation problem (the second term), or mixed, and name for each the main failure mode of treating it as pure prediction. (a) A judge decides whether to detain a defendant until trial; the worry is flight or a new offence upon release. (b) An agency with limited slots assigns applicants to a job-training programme, aiming to raise employment. (c) A city allocates a fixed team of fire and health inspectors across thousands of commercial buildings. (d) An ICU streams vital signs into a monitor that alerts nurses when a patient appears to be developing sepsis.\n:::\n\n::: {.callout-note collapse=\"true\" icon=\"false\" title=\"Answer 5.4\"}\n(a) Prediction. Detention works through incapacitation: it keeps a risky defendant off the street no matter why the risk is high, and releasing someone does not cause their riskiness, so the decision turns on forecasting $Y$ accurately. The characteristic failure here runs the other way: demanding a causal account of how defendants become risky before acting, when a plain forecast already improves on unaided judges. (b) Causation. The payoff turns on the treatment effect, on who gains employment because of the training. Ranking applicants by predicted unemployment risk fills the slots with people facing barriers the programme cannot touch; ranking by predicted employability cream-skims people who would have found work anyway. Pure prediction wastes the slots from either end. (c) Mixed. The city needs a forecast of which sites are hazardous, and an inspection changes behaviour, since owners fix hazards because an inspector came. Pure prediction sends the team back to the same persistently high-risk sites year after year while ignoring responsive sites that a single visit would fix. (d) Mixed. Detecting incipient sepsis is a forecasting task, but the alert intervenes on clinicians: false alarms cause alert fatigue, and a model with excellent held-out accuracy can then slow the response to true alarms and raise mortality. Accuracy metrics cannot detect this failure, because it is part of $\\partial Y / \\partial X_0$.\n:::\n\n## The bitter lesson: language as the extreme case\n\nThe algorithmic culture's approach has been pushed furthest in language technology. For decades, the path to language technology was assumed to run through understanding: formal grammars and hand-built linguistic knowledge. A rival tradition, from the earliest corpus statisticians to the French data-analysis school of Jean-Paul Benzécri [@benzecri1973], treated language as data for counting rather than a system to axiomatize, and was long dismissed as shallow, on the grounds that a machine would need to know *why* a sentence means what it means before it could use it. The outcome emerged in stages. In the 1970s, statistical models beat linguistically informed systems at speech recognition; over the decades that pattern repeated until @sutton2019 distilled it into the \"bitter lesson\" of seventy years of artificial intelligence: general methods that leverage computation and data eventually beat methods built on human domain knowledge. To see how this is possible, you can think back to the small simulation example above. Large language models are the current endpoint. Their orginal training objective was pure prediction, the next word, with no explanatory ambition, and yet they translate, summarize, diagnose, and tutor.\n\nThe extreme case offers social and health science concrete tools, with concrete caveats. As *measurement instruments*, language models annotate text (stance, emotion, frames) at a quality approaching trained human coders on many tasks, though unevenly, which argues for using them as one coder on a human team rather than as an oracle [@ziems2024]. As *simulated participants*, the results are impressive but open to doubt: one large evaluation by Hewitt and colleagues, reported in a position paper reviewing the method, found a model predicting most of the variation in average treatment effects across dozens of preregistered experiments [@anthis2025], yet the same systems compress the variance of human opinion, misrepresent minorities, and may simply be remembering the studies they were trained on [@bail2024; @grossmann2023]. As *agents*, they revive agent-based modelling with actors that talk. A purely predictive model of human text is a new scientific instrument, and every use of it requires asking, as throughout this book, what assumptions connect the instrument's output to the quantity we care about.\n\n## Two mass collaborations\n\nThe Fragile Families Challenge that opened this chapter, and its European successor, are together the cleanest measurements yet of how predictable individual lives are.\n\n**The Fragile Families Challenge** [@salganik2020] borrowed machine learning's **common task framework**: one dataset, one holdout, one metric, many independent teams, so that failure cannot be blamed on any single researcher's skill. The borrowing was deliberate. Donoho's history of data science credits this framework, public data, enrolled competitors, and a neutral referee scoring held-out predictions, as \"the 'secret sauce' of machine learning\", the source of decades of steady gains in speech and language systems [@donoho2017]. The challenge applied the same framework to a social-science question. The material was rich by any social-science standard: 4,242 families, 12,942 variables spanning birth through age nine, purpose-built survey data rather than found data. Performance was scored as $R^2$ on held-out families, relative to simply predicting the average. In detail, the best submissions reached about 0.23 for material hardship and 0.19 for GPA, and 0.03 to 0.06 for grit, eviction, caregiver layoff, and job training. The four-variable expert benchmark was \"only slightly worse than the most accurate submission\". There were two further findings. The 160 teams' predictions, for all their methodological diversity, agreed with each other far more than any of them agreed with reality; and prediction error concentrated in particular *families*, not particular methods. The authors draw the conclusion carefully: the results \"suggest practical limits to the predictability of life outcomes in some settings\", and policymakers buying predictive tools for child protection or criminal justice should ask for this kind of evidence before believing vendor accuracy claims.\n\n\n**PreFer** [@sivak2024] is the designed follow-up, and its design reflects what was learned from the first challenge. The task: predict which Dutch residents aged 18 to 45 will have a child in 2021 through 2023, from data through 2020. One outcome, well theorized, with a deliberately short three-year horizon. Two data sources compete. The LISS panel is \"wide\" in variables: over 30,000, including stated fertility intentions, the kind of subjective variable registers never contain, but with roughly 1,400 outcome-labelled cases. The Dutch population registers are \"long\" in cases: millions, 1995 through 2023, even the full kinship network, but limited to objective variables. The headline metric is F1, which balances precision and recall on the positive class, chosen because with about one in five positives, raw accuracy flatters models that predict \"no child\" for everyone. Teams submit runnable methods rather than predictions, fixing a reproducibility weakness the Fragile Families organizers discovered in their own archive. Above all, PreFer converts the earlier puzzle into a decomposition: if prediction fails on the survey but succeeds on the registers, the bottleneck was sample size; if the reverse, the subjective variables were what mattered; if both fail, the unpredictability starts to look like a property of lives rather than of datasets.\n\nThe results are now available. Over 150 participants submitted more than 70 models, from traditional machine learning to current methods. Predictive performance remained modest on *both* data sources: even the best models fell below the ceiling on predictability that randomness in conception and fetal survival by itself imposes. The survey-based predictions did slightly better than the register-based ones, so the subjective variables carry real information that millions of register records do not replace; and combining the two sources, by feeding the best register-based model's predicted probabilities into the best survey-based model, improved predictions only slightly further. The organizers' reading is the one the design was built to support: with full-population registers in play, modest accuracy can no longer be blamed primarily on small samples. Predicting an individual's fertility remains highly uncertain even three years out and with the best data currently possible, which moves the Fragile Families puzzle a step closer to a conclusion about lives rather than about datasets.<!-- OPEN(author): supply the reference for the PreFer results paper (the abstract shared in draft); the published version could not be located to cite. The sentence above should carry that citation. -->\n\n\n::: {.callout-tip icon=\"false\" title=\"Exercise 5.5\"}\n(a) In the Fragile Families Challenge, why does the common task method make \"low predictability\" a conclusion about the phenomenon rather than about the researchers? (b) The best GPA model reached $R^2 \\approx 0.19$ against a mean-prediction baseline. A press release announces: \"algorithm predicts children's school success\". Write the two-sentence correction. (c) Explain why PreFer's organizers chose F1 rather than accuracy, using the base rates given above.\n:::\n\n::: {.callout-note collapse=\"true\" icon=\"false\" title=\"Answer 5.5\"}\n(a) One hundred sixty independent teams with free choice of methods all faced the same holdout and the same metric; when the best of them barely beats a four-variable regression, \"a better analyst would have done better\" loses its plausibility, which was the design's purpose. (b) \"The best of 160 competing models explained about a fifth of the variation in GPA, leaving four fifths unexplained; it beat a four-variable regression by a few points. Individual children's outcomes remained largely unpredictable from thirteen thousand variables.\" (c) With roughly 15 to 22% positives, predicting \"no child\" for everyone scores about 80% accuracy while identifying no one; F1, which balances precision and recall on the positive class, gives such a model a score of zero.\n:::\n\n## Pendulums: successes and failures\n\nArguments about whether to focus on explanation or prediction or both are nothing new. In fact, they appear to swing back and forth like a pendulum sometimes. \n\nMacroeconomics swung twice. In the 1970s, its large \"structural\" models, hundreds of equations of interpretable theory, predicted poorly, and @sims1980 argued for replacing them with atheoretical time-series models that let recent data forecast the near future. The forecasting improved; the approach earned Sims a Nobel prize in 2011. Then the pendulum returned: for questions about *policy*, rain-dance questions, forecasting models are silent by construction, and the following generation of economists rebuilt causal credibility with the designs and instruments of chapters 1 and 3, work honoured with its own Nobel a decade later. Both swings were rational: the field learned which of its questions were umbrella questions and which were not.\n\nPrediction has its cautionary tales too. Google Flu Trends estimated influenza incidence from search queries, faster than the official surveillance it aimed to complement, and for a while it worked; then it drifted, at one point overestimating flu prevalence by a factor of two, partly because the search engine and its users kept changing under the model [@lazer2014]. The failure is the mirror image of the Fragile Families lesson: an impressive fit on the past is a statement about the past, and a predictive model deployed in a changing world becomes a model of a world that no longer exists. Meanwhile, successes that attract less attention accumulate: clinical risk scores triage chest pain, predicted readmission risks schedule follow-up calls, and no one demands that these models explain anything, only that they keep predicting well.\n\n## What to carry forward\n\nFour ideas from this chapter travel into the machine learning chapters. A wrong model can predict better than the true one, which stops being a paradox once error is split into bias and variance, the subject of @sec-overfitting. A prediction is a statement about unseen data, so evaluation always requires data the model has not touched; @sec-overfitting names the failure, overfitting, and @sec-evaluation shows how to arrange the checking, and how badly things go when you cheat. A decision's payoff has an umbrella term and a rain-dance term, and no accuracy metric can certify the second. And the chain of @sec-rq-to-interpretation never went away: a predictive model answers its question under assumptions, chiefly that the future resembles the training data, and Google Flu shows what their violation looks like. The tools change in the next two chapters, but the five questions do not.\n\n## Test yourself {.unnumbered}\n\n::: {.callout-tip icon=\"false\" title=\"Exercise 5.A\"}\nA researcher has panel data on adolescents: social media use, sleep, exercise, parental monitoring, and depressive symptoms, over four years. Two goals are on the table. Goal 1: estimate the effect of social media use on depressive symptoms, for policy advice. Goal 2: flag adolescents at high risk of developing symptoms next year, so the school counsellor can reach out.\n\n(a) For each goal, which variables belong in the model, and by what criterion?\n(b) For each goal, what is the appropriate way to judge whether the model is good?\n(c) The Goal 2 model puts large weight on parental monitoring. A journalist concludes that monitoring causes depression. Explain the error, and what would go wrong if a school acted on it.\n(d) Conversely, suppose the researcher uses only the variables with credible causal effects for Goal 2's forecasting task. What is sacrificed, and why?\n:::\n\n::: {.callout-note collapse=\"true\" icon=\"false\" title=\"Answer 5.A\"}\n(a) Goal 1: variables chosen by the causal logic of chapters 1 and 3: confounders of use and symptoms must enter, mediators must stay out of the total-effect equation, and instruments or designs must carry the assumptions. Goal 2: anything measurable in advance that improves held-out prediction, including proxies with no causal standing. (b) Goal 1: by the credibility of the design and assumptions, plus uncertainty of the estimate; fit alone proves little. Goal 2: by predictive performance on held-out adolescents, with a metric suited to the base rate and to the costs of misses versus false alarms. (c) Predictors earn their weights by association, and monitoring may be a marker of parents already worried about a struggling child; acting on it causally (discouraging monitoring) could remove a response to risk rather than a cause of it, an umbrella-rain-dance confusion. (d) Predictive accuracy: causal variables are often few, weak, or hard to measure early, while non-causal markers carry real signal; a forecaster restricted to causes is a worse forecaster, which is Breiman's point.\n:::\n\n::: {.callout-tip icon=\"false\" title=\"Exercise 5.B\"}\nA team proposes to use a language model to code 40,000 open-ended survey answers about vaccine hesitancy into five categories, replacing two student coders.\n\n(a) Describe a validation design that would justify the substitution, including what quantity you would compute.\n(b) Name two failure modes specific to language models that your design should probe, and how.\n(c) The model classifies answers written in regional dialect noticeably worse. Which concept from this chapter (and from @sec-rq-to-interpretation) does this instantiate, and what would you do?\n:::\n\n::: {.callout-note collapse=\"true\" icon=\"false\" title=\"Answer 5.B\"}\n(a) Have the human coders label a random subsample (stratified over categories and respondent groups); compare model and human labels via agreement statistics such as Cohen's kappa, benchmarked against the two humans' agreement with each other; only substitute if model-human agreement approaches human-human agreement, and keep humans on a continuing audit sample. (b) Training-data contamination and drift: probe by testing on newly written answers the model cannot have seen. Systematic skew, such as sycophantic or majority-flavoured readings of ambiguous answers: probe by comparing error rates across answer types and demographic groups. (c) Differential measurement quality, a construct-validity threat, and a violation of the assumption that the instrument works equally well across units; remedies include dialect-specific validation, human coding for the affected group, or adjusting analyses for known error rates.\n:::\n\n::: {.callout-tip icon=\"false\" title=\"Exercise 5.C\"}\n\"Since the best Fragile Families models explained only 20% of GPA variance, social science has learned nothing about child development.\" Write a short assessment (at most 200 words) that engages the strongest version of both sides.\n:::\n\n::: {.callout-note collapse=\"true\" icon=\"false\" title=\"Answer 5.C\"}\nA model answer engages both directions. For the provocation: if understanding is measured by out-of-sample prediction, the result is damning, since 750 papers' worth of variables barely beat four chosen by hand, and the shortfall was no one team's fault by design. Against it: explanation and prediction are different targets; a modest average causal effect can be real, replicable, and policy-relevant while individual outcomes stay dominated by idiosyncratic events, so low individual predictability does not refute the causal knowledge. The strong synthesis notes what the challenge actually adds: a measured ceiling, so far unexplained, which theories of development must now themselves explain; a warning for anyone deploying individual-level risk prediction in policy; and a template, extended by PreFer, for finding out whether the ceiling reflects data limits or genuine randomness in lives. \"Nothing\" overclaims; \"business as usual\" underclaims; the defensible position is that social science learned something painful and useful about the kind of knowledge it has.\n:::\n",
    "supporting": [
      "05-explanation-prediction_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{},\"value\":[]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}