{
  "hash": "bc832e1b5f542c84f22e704deba01f68",
  "result": {
    "engine": "knitr",
    "markdown": "# Explanation and prediction {#sec-explanation-prediction}\n\nIn 2017, a group of researchers issued an unusual challenge. The Fragile Families study had followed thousands of American children born around 2000, interviewing their families at birth and at ages one, three, five, and nine: nearly 13,000 variables per family, feeding a literature of over 750 published articles. The challenge: using everything measured through age nine, predict six outcomes at age fifteen, among them the child's grade point average and whether the family would be evicted. One hundred sixty teams tried, using every method from linear regression to deep learning, scored on families they had never seen. The best predictions were poor. Performance was scored as $R^2$, the fraction of the outcome's variance that the predictions account for: 0 for a model that predicts the average for everyone, 1 for perfect prediction. For the two most predictable outcomes, material hardship and grade point average, the best submissions reached an $R^2$ of 0.23 and 0.19; for the other four, between 0.03 and 0.06. A benchmark regression using just four variables chosen by a domain expert came close to the winners [@salganik2020].\n\nHundreds of papers had explained these children's development, or so their titles claimed, yet the same data could not predict those children's lives much better than guessing the conditional average based on four variables. The gap points to a problem in how we think about understanding. For four chapters you have fitted models in order to interpret their parameters: the effect of a policy, the share of variance between schools. In the chapters ahead you will fit models in order to predict, and their parameters may interest nobody. This chapter asks what a prediction is, what it is good for when nobody asks for an explanation, and what predicting well has to do with explaining well.\n\n## Prediction as a statement about unseen data\n\nA prediction is a statement about data you have not seen. The data may lie in the future but need not: predicting the outcomes of last year's patients whose files you never opened is prediction. Data set aside and never used in fitting the model are called **held-out** data (or the *holdout*), and the requirement is that the model was fixed before the answer was known.\n\nScience has always used prediction in this sense to test theories. A theory implies statements about observations, and once the observations are made, the theory either survives or does not. You have already done this, in @sec-theory-to-glm, perhaps without noticing. A path model implies correlations, via the decomposition rule, and the chi-square test asked whether the observed correlations matched them. Every claim of absence was a commitment about data not yet consulted. Testing an explanation and checking a prediction are the same act.\n\nAggregate models make the same move at larger scale. The SIR model of epidemics [@kermack1927] divides a population into susceptible, infected, and recovered persons and predicts a characteristic wave: rise, peak, decline. Real epidemics follow the wave roughly, and each departure from it, from superspreading to waning immunity, forced a better model. The DeGroot model of opinion dynamics [@degroot1974] predicts that people who keep averaging their opinions with their neighbours' will converge to consensus. Real populations do not reach consensus. The model, taken literally, is false, and its failure is informative, since whatever blocks consensus (stubbornness, homophily) is what a better theory must contain. Sociologists in the tradition of @coleman1990 and methodologists like @kkv1994 treat such observable implications as what gives a social theory its value: a theory that implies nothing checkable has none.\n\nA verbal theory, however, usually implies far less than its authors think, and testing \"the theory predicts a difference in the expected direction\" is a weak test; almost any theory passes it [@yarkoni2022]. Meehl's old complaint applies: a theory of climate that predicts it will rain *sometime* next April earns no credit when it does, and \"more rain in April than in May\" impresses nobody, \"even showing three asterisks\"; a theory that predicts how many inches will fall on which April days, and gets seven of them right within tolerance, is starting to look like science [@meehl1978, pp. 817-818]. One diagnosis of the replication crisis is this mismatch between sweeping verbal claims and the weak statistical statements offered as their tests. Predictive performance on data the model has not seen is a test that verbal theorizing alone cannot pass.\n\n::: {.callout-tip icon=\"false\" title=\"Exercise 5.1\"}\nFor each claim, state one concrete prediction it makes about unseen data, and one observation that would embarrass it. (a) The DeGroot model of opinion dynamics. (b) The mediation model of @sec-identification with no direct effect ($X \\to M \\to Y$ only). (c) \"Vocational education helps early careers but hurts late ones\" [@forster2016].\n:::\n\n::: {.callout-note collapse=\"true\" icon=\"false\" title=\"Answer 5.1\"}\n(a) Repeatedly interacting groups should drift toward agreement; stable long-run polarization in such groups embarrasses it. (b) The implied correlation restriction $\\rho_{XY} = \\rho_{XM}\\rho_{MY}$ in fresh data; a $\\rho_{XY}$ clearly different from the product, in either direction, embarrasses the exclusion. (c) In a new cohort, the employment gap between vocational and general graduates should be positive at labour-market entry and turn negative around mid-career; a gap that stays flat or grows with age embarrasses the reversal claim. In each case the theory earns credit only in proportion to how easily it could have failed.\n:::\n\n## Prediction in its own right\n\nPrediction has a second job that needs no theory at all: sometimes an uncertain forecast is better than none, because a decision has to be made. Economists put the distinction in two images [@kleinberg2015]. Deciding whether to carry an umbrella requires only a forecast of rain: the umbrella does not change the weather. Deciding whether to perform a rain dance requires a causal claim: the dance pays only if it makes rain. Umbrella problems are common. Which arriving patients should be fast-tracked? Which defendants will appear for trial? Which households should an anti-poverty programme visit first? Each of these decisions requires identifying the right people, and does not require knowing the causes.\n\nFor most of the twentieth century, mainstream statistics in the social and health sciences paid little attention to such problems. @breiman2001 described the split in a paper whose argument has held up well. Statistics, he wrote, contains two cultures. The data-modelling culture, which he estimated at 98% of statisticians, assumes a stochastic model and interprets its parameters, validating by goodness of fit. The algorithmic-modelling culture, his 2%, treats nature's mechanism as unknown, seeks any function that predicts well, and validates on held-out data. His warning to the 98% was that conclusions from a fitted model are about the model's mechanism, and \"if the model is a poor emulation of nature, the conclusions may be wrong\". Twenty years on, his advice is mostly vindicated, and @sec-overfitting and @sec-evaluation go into more depth.\n\n@shmueli2010 explains why a model built without regard for truth can predict better than a model built to be true: prediction error has two parts, error from bias (the model is wrong) and error from variance (the estimates are noisy), and a deliberately simplified, \"wrong\" model often wins by trading a little bias for a lot of variance. Exercise 1.D already showed the two kinds of error side by side: the confounded estimate was *biased*, and the spread of the estimates, their variance, had nothing to do with it. Bias in chapters 1 to 3 meant a systematic gap between the estimate and the causal effect; in prediction the word covers any systematic gap between what a model fits on average and the truth, including the gap that comes from leaving a variable out, and @sec-overfitting treats the tradeoff between that bias and variance in full. For now, explaining well and predicting well are different objectives, optimized by different models, and neither can be read off from the other.\n\nA simulation, in which we know the true data-generating process, shows the two objectives diverging. It is the world of Exercise 1.D again, with a medication added. Take a moment to read through this code and the comments.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1015)\n\ng <- 3        # confounding strength; spurious covariance is g^2\nb <- 0.15     # direct effect from medication to symptoms\nn_train <- 20 # \"training\" sample size (used for fitting model)\n\n# This function is the data-generating process (DGP). It returns\n# random data from our population.\ngenerate_data <- function(n) {\n  medication <- rnorm(n) # A truly causal factor with a small effect\n  motivation <- rnorm(n) # An (later unobserved) confounder\n  exercise   <- g*motivation + rnorm(n) # motivated exercise more\n\n  # Symptoms are *not* improved by exercise, but only by motivation\n  # and medication\n  symptoms   <- g*motivation + 0*exercise + b*medication + rnorm(n)\n\n  # In the data we do not observe the confounder, motivation:\n  return(data.frame(symptoms, exercise, medication))\n}\n\n# These are the observed data we can use to fit a predictive model:\ndf_observed <- generate_data(n_train)\n\n\n# The model with only the true cause \"medication\":\nfit_true  <- lm(symptoms ~ medication, data = df_observed)\n# The model with both the true cause \"medication\" and the spurious\n# factor \"exercise\":\nfit_both <- lm(symptoms ~ exercise + medication, data = df_observed)\n# The model with _only_ the spurious factor \"exercise\":\nfit_wrong  <- lm(symptoms ~ exercise, data = df_observed)\n\n# Now let's evaluate how our models can be expected to perform on\n# completely newly generated data from the same population.\ndf_test <- generate_data(1e5) # n is just set to a big number\n\n# Evaluate the root-mean squared deviation (residuals)\nrmse <- function(m) {\n  sqrt(mean((\n    df_test$symptoms - predict(m, df_test))^2\n  )) |> round(2)\n}\n\n# Model performance in unseen data from the same population\n# (lower is better):\ndata.frame(true = rmse(fit_true),\n           both = rmse(fit_both),\n           wrong = rmse(fit_wrong))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  true both wrong\n1 3.25 1.49  1.42\n```\n\n\n:::\n:::\n\n\nThe performance measure is the **root-mean-squared error** (RMSE): square each prediction error on the test data, average the squares, and take the square root, so that the result is in the units of the outcome; @sec-evaluation defines it formally alongside the other metrics. In the code above,\n\n * The \"true\" model includes only the truly causal factor `medication`. Its RMSE is high (3.25), because although `medication` has a true effect, the effect is small, and the variable that drives most of the variation in symptoms, `motivation`, is not in the data;\n * The \"both\" model includes *both* the causal factor `medication` and the spurious factor `exercise`. Both variables carry predictive value for the outcome, even though changing `exercise` does nothing for symptoms, and its RMSE is much lower (1.49);\n * The \"wrong\" model includes *only* the spurious factor `exercise`, and *not* the true causal factor `medication`. It can tell us nothing about how to improve symptoms. But in this sample it is the best of the three in predictive terms, with an RMSE of 1.42.\n\nThe table contains two comparisons, and they are of different kinds. That `fit_wrong` beats `fit_true` by a wide margin is robust: it holds at any sample size and for any seed, because `exercise` is correlated with the unobserved `motivation`, which drives most of the variation in symptoms, and a confounded variable carries predictive signal whatever its causal standing. That `fit_wrong` also beats `fit_both`, by a small margin, is a small-sample effect: including `medication` means estimating one more coefficient from twenty observations, and the noise in that estimate costs more than the small true effect is worth. With a few hundred observations the verdict reverses, as Exercise 5.3 shows and @sec-overfitting computes exactly. The robust comparison carries the lesson. Searching for the \"true\" (explanatory) model is not the way to the best prediction. And a highly predictive model need not say anything about how to improve the outcome: a doctor who has not seen our DGP could take `fit_wrong` and advise patients to exercise. The goal of the analysis has to be settled first, and as argued in this chapter, that goal should sometimes be to predict instead of, or in addition to, explaining the phenomenon at hand.\n\n::: {.callout-tip icon=\"false\" title=\"Exercise 5.2\"}\nExtend the chunk above as needed. (a) Which of the three models gives the right answer to the causal question: would prescribing exercise change symptoms? (b) Which model should a clinic use to forecast symptom burden, and why? (c) Running `coef(fit_wrong)` puts `exercise` at about $0.99$. A doctor reads this as \"each unit of exercise changes the symptom score by about one point\". What can the printed output tell her about whether that reading is safe? (d) A principled analyst refuses to use any variable without causal standing and sticks to `fit_true`. What does the refusal cost, and what does it buy?\n:::\n\n::: {.callout-note collapse=\"true\" icon=\"false\" title=\"Answer 5.2\"}\n(a) None of them. The true effect of exercise is zero by construction, but `fit_wrong` and `fit_both` both attach a coefficient of about $0.99$ to it, because the confounder, motivation, is not in the observed data: no regression on these three columns can hold it constant. Adding the true cause `medication` (going from `fit_wrong` to `fit_both`) does not repair the exercise coefficient at all. The only model that avoids making a false causal claim about exercise is `fit_true`, and it does so by staying silent on the question. (b) `fit_wrong`, which has the lowest error on new data (1.42), with `fit_both` close behind (1.49); forecasts are judged on held-out error, and exercise carries real signal about symptoms regardless of its causal role. (c) Nothing. The printout for the confounded exercise coefficient looks exactly like the printout for the unconfounded medication coefficient: same standard errors, same stars. Which coefficients have causal standing is settled by design and assumptions, never by the fitted output. (d) The refusal costs predictive accuracy (3.25 against 1.42) and buys causal interpretability for the one variable it keeps: because `medication` was assigned independently of everything else, its coefficient is an unbiased estimate of a real effect. Even that purchase is partial, though. With `n_train = 20` the estimate is $-0.55$ where the truth is $+0.15$: the estimate of the one genuinely causal effect does not even have the right sign. Unconfounded is not the same as precise, and a causal design does not excuse a small sample.\n:::\n\nThe result that the \"wrong\" model beats the \"both\" model depends on the three quantities set at the top of the chunk, and a single training sample is a noisy way to study that dependence. The function below repeats the contest 500 times at the current values of `g` and `b`, drawing a fresh training sample each time and scoring all three models on one shared test sample, and reports how often each model has the lowest error.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Repeat the contest reps times at the current values of g and b.\n# Each run draws a fresh training sample; the test sample is shared.\ncontest <- function(n_train, reps = 500) {\n  set.seed(1015)\n  test <- generate_data(2e4)\n  err <- function(m) {\n    sqrt(mean((test$symptoms - predict(m, test))^2))\n  }\n  winner <- replicate(reps, {\n    d <- generate_data(n_train)\n    e <- c(true  = err(lm(symptoms ~ medication, d)),\n           both  = err(lm(symptoms ~ exercise + medication, d)),\n           wrong = err(lm(symptoms ~ exercise, d)))\n    names(which.min(e))\n  })\n  round(table(winner) / reps, 2)\n}\ncontest(n_train = 20)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nwinner\n both wrong \n 0.34  0.66 \n```\n\n\n:::\n:::\n\n\n::: {.callout-tip icon=\"false\" title=\"Exercise 5.3\"}\nUse `contest()` to find out how the outcome depends on the three quantities set at the top of the first chunk. Because `generate_data()` reads `g` and `b` from the workspace, changing them at the top and rerunning that line is enough; `n_train` is an argument of `contest()`.\n\n(a) Call `contest(100)` and `contest(500)`. When does `fit_both` start to beat `fit_wrong`, and why?\n(b) Set `b <- 0.5` and call `contest(20)`; then set `b <- 1` and call it again. What happens to the contest between `fit_both` and `fit_wrong`, and to the standing of `fit_true`?\n(c) Reset `b <- 0.15`. What does `g` govern, and which comparison does changing it (try `g <- 1` and `g <- 0.5`) affect most? Reset `g <- 3` afterwards.\n(d) Summarize your findings in one sentence about when leaving a true cause *out* of a model improves prediction.\n:::\n\n::: {.callout-note collapse=\"true\" icon=\"false\" title=\"Answer 5.3\"}\n(a) With `b = 0.15`, `fit_wrong` wins in 66 percent of the samples at `n_train = 20`, in 34 percent at 100, and in 2 percent at 500. Including `medication` costs the variance of estimating one extra, nearly useless coefficient and buys the removal of a small bias; the cost shrinks with $n$ while the bias does not, so somewhere around $n$ in the low hundreds the balance tips and the fuller model wins from then on.\n(b) Raising `b` makes `medication` genuinely informative: at `b = 0.5` the \"wrong\" model wins in 16 percent of samples at `n_train = 20`, and at `b = 1` in 1 percent. `fit_true` also improves relative to the other two, since the variable it keeps now carries real signal, although at these values it still never wins.\n(c) `g` sets the strength of the confounding, and thereby how much predictive value the spurious variable carries: with `g = 3`, exercise accounts for $g^2/(g^2+1) = 0.9$ of the variance of motivation's contribution to symptoms; with `g = 1` only half. Changing `g` mostly moves `fit_true`'s standing relative to the other two, since they both ride on exercise: at `g = 1` it still wins only 1 percent of contests, but at `g = 0.5` it wins 31 percent. The `fit_both`-versus-`fit_wrong` contest is governed by `b` and `n_train`.\n(d) Omitting a true cause improves prediction when its effect is small enough, and the sample small enough, that the variance of estimating it exceeds the bias of ignoring it; more data or a bigger effect flips the verdict. That is the bias-variance trade-off of @shmueli2010 in a single decision, and @sec-overfitting builds the general machinery.\n:::\n\nSo far the argument has been that prediction is a goal in its own right, separate from explanation. There is a complementary argument: predictive checks are useful *within* explanatory research, even when nobody intends to forecast anything. @verhagen2022 makes this case for the social sciences. His starting observation is that predictive evaluation is nearly absent from explanatory practice: in six leading journals of economics, sociology, and political science, fewer than 5 percent of abstracts mention prediction at all. What is lost, he argues, is basic information about the models whose coefficients we interpret. A coefficient can be statistically significant in a model that captures half of the outcome's variation or one that captures a thousandth of it, and the significance test does not distinguish the two; computing predictive performance, which any fitted model can do at no extra cost, does. The information becomes sharper still when performance is computed per group rather than overall. Verhagen's leading example is a well-known analysis of discrimination in mortgage lending: the fitted model describes White applicants' outcomes well and non-White applicants' outcomes much worse, so its conclusions rest on a model that fits the group under study worst. The coefficient table does not reveal this, but a group-wise predictive check does; @sec-evaluation returns to this kind of subgroup evaluation, with Exercise 7.A asking for it on a real example.\n\n@yarkoni2017 draw a related but distinct lesson for psychology. Their broader argument is that psychology should take prediction seriously as a goal in its own right. They also point out something that matters even for pure explainers: the questionable research practices behind the replication crisis, the fishing and flexible analysis of @sec-rq-to-interpretation, are recognizable to a machine learner as **overfitting performed by hand**. A researcher who tries many specifications and keeps the one with the significant result has fit the noise in one dataset, just as an unconstrained algorithm would, and the failure shows up the same way: the finding does not hold in new data. The remedies machine learning developed for its version of the problem, holding out data for evaluation and penalizing flexibility, are therefore also safeguards for explanatory research, and the section on leakage in @sec-evaluation shows the same failure arising inside machine learning itself. Both papers arrive at the same practical advice: whatever your goal, evaluate your model's predictions, and trust it in proportion to how well it predicts.\n\n## One decision, two questions\n\nA hospital loses money when booked patients do not show up: the slot stands empty while another patient waits weeks for it. So the hospital builds a model that flags likely no-shows, and staff call just those patients with a reminder. This decision needs a forecast of which patients, left alone, would skip. It also affects the outcome: a phone call can change whether a patient comes.\n\nRecall the two images from earlier in this chapter [@kleinberg2015]. An *umbrella* decision depends on an outcome without touching it: whether to carry an umbrella depends on rain, but the umbrella does not change the weather, so a forecast is all the decision needs. A *rain-dance* decision pays off only by changing the outcome: the dance is worthwhile only if it actually makes rain, so a causal claim is what the decision needs. Kleinberg and colleagues expressed this distinction in one line of calculus, and the hospital example gives each symbol a concrete meaning.\n\nThree quantities are in play, drawn in @fig-umbrella-raindance. The **action** $X_0$ is what the hospital controls: call a booked patient with a reminder, or not (the subscript marks it as the one variable the decision-maker sets). The **outcome** $Y$ is the part of the world the payoff depends on: whether the patient shows up. And the **payoff** $\\pi(X_0, Y)$ is what the hospital ultimately cares about, the net benefit of the clinic day, which depends on both: on the action, because calls cost staff time and because knowing a no-show is coming lets the clinic rebook the slot, and on the outcome, because a kept appointment is the point of the whole exercise. The question every decision-maker faces is: what happens to the payoff if I act? In symbols, what is $d\\,\\pi / d X_0$, the rate at which the payoff changes per unit change in the action? The answer splits in two, because the action can reach the payoff along two routes, directly and through the outcome. A *partial* derivative, written with $\\partial$, is the rate of change of a function of several arguments when one argument moves and the others are held fixed, and the chain rule of calculus writes the total rate of change as the sum over the two routes:\n\n$$\n\\frac{d\\,\\pi(X_0, Y)}{d X_0} \\;=\\; \\underbrace{\\left.\\frac{\\partial \\pi}{\\partial X_0}\\right|_{Y}}_{\\text{prediction part}} \\;+\\; \\underbrace{\\frac{\\partial \\pi}{\\partial Y}\\,\\frac{\\partial Y}{\\partial X_0}}_{\\text{causation part}}\n$$\n\nThe vertical bar in the first term means \"evaluated at the outcome $Y$\": that term depends on what $Y$ turns out to be, but does not change it. You need no calculus to read the equation. The first term is how much the payoff changes per unit of action with the outcome held fixed; the second is how much the action changes the outcome, times how much a change in the outcome is worth; and the equation says that the total change is the sum of the two.\n\n![The two kinds of decision, drawn for the hospital example. In panel (a) the action affects the payoff only directly: whether calling is worthwhile depends on what the patient would do anyway, so the decision needs a *prediction* of $Y$. In panel (b) the action also changes the outcome itself: the arrow $\\partial Y/\\partial X_0$ is a causal effect, and the decision needs a causal estimate of it. Most real decisions contain both arrows.](images/umbrella-raindance.png){#fig-umbrella-raindance width=\"95%\" fig-align=\"center\"}\n\nThe two terms can be read one at a time, each with the hospital in mind.\n\nThe **first term**, $\\partial \\pi / \\partial X_0$ evaluated at $Y$, asks: holding the patient's behaviour fixed, how does calling change the payoff? Suppose for a moment that the call has no influence on anyone, as in panel (a) of @fig-umbrella-raindance. Calling still matters, because its value depends on what the patient was going to do. Calling someone who would have shown up anyway costs a few minutes of staff time and gains nothing. Calling someone who was going to skip lets the clinic rebook the slot before it stands empty. So even with no causal effect anywhere, the hospital profits from calling the *right* patients, and choosing the right patients requires one input: a good prediction of $Y$. This is the umbrella term: just as the umbrella does not change the rain, the call in this term does not change the patient, and the value of the action depends on knowing what will happen.\n\nThe **second term** asks the rain-dance question: does the call itself change whether the patient shows up? It is a product of two pieces. The piece $\\partial Y / \\partial X_0$ is the causal effect of the call on attendance, panel (b)'s purple arrow: a reminder may jog a forgetful patient into coming. The piece $\\partial \\pi / \\partial Y$ translates that change in attendance into payoff: a patient who now shows up fills a slot that would have gone empty. Using this term requires what the whole first half of this book was about, a credible causal estimate, and no forecast can substitute for it: a model that predicts attendance perfectly can still be silent about what a *call* would do to attendance.\n\nKleinberg's point is that decisions differ in which term dominates, and that the difference dictates the kind of research the decision needs. When the second term is (near) zero, as with the umbrella, prediction is the entire problem, and demanding a causal interpretation of a forecasting model asks for something the decision will not use. When the second term is substantial, no amount of predictive accuracy certifies the decision, because $\\partial Y / \\partial X_0$ is a causal quantity that held-out data do not contain. Real reminder policies involve both terms at once, because patients adapt. A clinic that reliably reminds its likely skippers teaches them to wait for the call, and when one day no call comes, they skip more often than before the policy existed. That is the causation part with the wrong sign, and a hospital that evaluates its model on forecasting accuracy alone will not detect it.\n\n::: {.callout-tip icon=\"false\" title=\"Exercise 5.4\"}\nPut numbers to the decomposition. A reminder call costs €2 of staff time. If a patient who would have skipped is called, the clinic can rebook the slot, which is worth €40; calling a patient who would have come anyway gains nothing. The model gives each patient a predicted probability $p$ of skipping.\n\n(a) Suppose the call has no causal effect on attendance. For which $p$ is calling worth it? Which term of the decomposition did you use?\n(b) Now suppose a call also raises every patient's probability of attending by 0.10, and that an attended appointment is worth €30 to the clinic. Add the causal term to your rule from (a) and recompute it.\n(c) In (b), does the ranking of patients by the prediction model still matter for the decision?\n(d) Suppose that after a year patients have learned to wait for the call, so that the effect in (b) has turned to $-0.10$. Which term of the decomposition changed sign, and what kind of evaluation would have detected the change?\n:::\n\n::: {.callout-note collapse=\"true\" icon=\"false\" title=\"Answer 5.4\"}\n(a) The expected gain from a call is $40p - 2$, which is positive when $p > 0.05$: call every patient whose predicted probability of skipping exceeds 5 percent. Only the first, umbrella term is involved; the payoff depends on $Y$ through the rebooking, but the call does not change $Y$.\n(b) Every call now also earns $0.10 \\times 30 = 3$ through the causal term, so the expected gain is $40p + 3 - 2 = 40p + 1$, which is positive for every $p$: call everyone.\n(c) Not for the call-or-not decision: when the causal term is the same for everyone and large enough to make the gain positive at $p = 0$, the forecast no longer changes what the clinic does. The ranking would matter again only if calls were rationed (then call the patients with the highest $p$ first) or if the causal effect differed between patients.\n(d) The causal effect $\\partial Y / \\partial X_0$ changed sign; the rule becomes $40p - 3 - 2 > 0$, or $p > 0.125$, and calling now harms the patients it was meant to help. No accuracy metric of the forecast can detect this, because forecasting accuracy measures the first term only. Only a comparison of called with uncalled patients, a trial of the calling policy against no calls, reveals the second term; @sec-evaluation makes this argument in its closing section.\n:::\n\n@hofman2021 make the same point at the scale of a research field. Reviewing computational social science, they sort studies along two dimensions that by now should look familiar. The first is whether a study aims to *explain*: to identify and estimate causal effects, the second term of the payoff. The second is whether a study *tests its predictions*: whether its claims are evaluated against data the model has not seen, the discipline behind the first term. Crossing the two dimensions gives four kinds of research (@tbl-hofman):\n\n|  | **predictions not tested out of sample** | **predictions tested out of sample** |\n|---|---|---|\n| **no causal ambition** | descriptive modelling | predictive modelling |\n| **causal ambition** | explanatory modelling | integrative modelling |\n\n: The organization of research proposed by @hofman2021: what a study estimates (rows) crossed with how it is validated (columns). {#tbl-hofman}\n\nMost quantitative social science, including most of what the first four chapters of this book covered, sits in the lower-left cell: models with causal ambitions whose predictive performance is never checked. Most machine learning sits in the upper-right: models checked rigorously on held-out data, with no causal ambitions at all. Each cell inherits the weakness the payoff formula predicts for it. Work in the lower-left makes rain-dance claims whose predictions are never tested: its estimated effects may be credible, but nobody knows whether the model captures enough of the outcome to matter, which was Verhagen's complaint above. Work in the upper-right can fail as soon as a policy changes the world it learned from, because everything it knows is an association in the training distribution, which was the Google Flu failure described below and the adapting patients of the reminder example.\n\nThe sparsest cell, Hofman and colleagues report, is the lower-right, which they name **integrative modelling**: research that estimates effects credibly *and* tests whether its predictions survive out of sample, including under interventions and in shifted circumstances. That cell is where the two terms of the payoff meet: a decision-maker who must weigh both terms needs a model whose causal claims are identified and whose predictive claims are verified. Their recommendation follows directly: judge a claim of understanding on both performances at once. A high $R^2$ without a design is not understanding, and neither is a clean identification strategy for a model that explains almost nothing of what happens.\n\n::: {.callout-tip icon=\"false\" title=\"Exercise 5.5\"}\nClassify each decision as mainly a prediction problem (the first term), mainly a causation problem (the second term), or mixed, and name for each the main failure mode of treating it as pure prediction. (a) A judge decides whether to detain a defendant until trial; the worry is flight or a new offence upon release. (b) An agency with limited slots assigns applicants to a job-training programme, aiming to raise employment. (c) A city allocates a fixed team of fire and health inspectors across thousands of commercial buildings. (d) An ICU streams vital signs into a monitor that alerts nurses when a patient appears to be developing sepsis.\n:::\n\n::: {.callout-note collapse=\"true\" icon=\"false\" title=\"Answer 5.5\"}\n(a) Prediction. Detention works through incapacitation: it keeps a risky defendant off the street no matter why the risk is high, and releasing someone does not cause their riskiness, so the decision turns on forecasting $Y$ accurately. The characteristic failure here runs the other way: demanding a causal account of how defendants become risky before acting, when a plain forecast already improves on unaided judges. (b) Causation. The payoff turns on the treatment effect, on who gains employment because of the training. Ranking applicants by predicted unemployment risk fills the slots with people facing barriers the programme cannot touch; ranking by predicted employability cream-skims people who would have found work anyway. Pure prediction wastes the slots from either end. (c) Mixed. The city needs a forecast of which sites are hazardous, and an inspection changes behaviour, since owners fix hazards because an inspector came. Pure prediction sends the team back to the same persistently high-risk sites year after year while ignoring responsive sites that a single visit would fix. (d) Mixed. Detecting incipient sepsis is a forecasting task, but the alert intervenes on clinicians: false alarms cause alert fatigue, and a model with excellent held-out accuracy can then slow the response to true alarms and raise mortality. Accuracy metrics cannot detect this failure, because it is part of $\\partial Y / \\partial X_0$.\n:::\n\n## The bitter lesson: language models as the extreme case\n\nThe algorithmic culture's approach has been pushed furthest in language technology. For decades, the path to language technology was assumed to run through understanding: formal grammars and hand-built linguistic knowledge. A rival tradition, from the earliest corpus statisticians to the French data-analysis school of Jean-Paul Benzécri [@benzecri1973], treated language as data for counting rather than a system to axiomatize, and was long dismissed as shallow, on the grounds that a machine would need to know *why* a sentence means what it means before it could use it. The outcome emerged in stages. In the 1970s, statistical models beat linguistically informed systems at speech recognition; over the decades that pattern repeated until @sutton2019 distilled it into the \"bitter lesson\" of seventy years of artificial intelligence: general methods that leverage computation and data eventually beat methods built on human domain knowledge. The simulation above shows on a small scale how this is possible: the model with no causal content predicted best, because it used whatever carried signal. Large language models are the current endpoint. Their original training objective was pure prediction, the next word, with no explanatory ambition, and yet they translate, summarize, diagnose, and tutor.\n\nThe extreme case offers social and health science concrete tools, with concrete caveats. As *measurement instruments*, language models annotate text (stance, emotion, frames) at a quality approaching trained human coders on many tasks, though unevenly, which argues for using them as one coder on a human team rather than as an oracle [@ziems2024]. As *simulated participants*, the results are impressive but open to doubt: one large evaluation by Hewitt and colleagues, reported in a position paper reviewing the method, found a model predicting most of the variation in average treatment effects across dozens of preregistered experiments [@anthis2025], yet the same systems compress the variance of human opinion, misrepresent minorities, and may simply be remembering the studies they were trained on [@bail2024; @grossmann2023]. As *agents*, they revive agent-based modelling with actors that talk. A purely predictive model of human text is a new scientific instrument, and every use of it requires asking, as throughout this book, what assumptions connect the instrument's output to the quantity we care about.\n\n## Two mass collaborations and a systematic review\n\nThe Fragile Families Challenge that opened this chapter, and its European successor, are together the cleanest measurements yet of how predictable individual lives are. A systematic review of clinical prediction models reaches a related conclusion by another route.\n\n**The Fragile Families Challenge** [@salganik2020] borrowed machine learning's **common task framework**: one dataset, one holdout, one metric, many independent teams, so that failure cannot be blamed on any single researcher's skill. The borrowing was deliberate. Donoho's history of data science credits this framework, public data, enrolled competitors, and a neutral referee scoring held-out predictions, as \"the 'secret sauce' of machine learning\", the source of decades of steady gains in speech and language systems [@donoho2017]. The challenge applied the same framework to a social-science question. The material was rich by any social-science standard: 4,242 families, 12,942 variables spanning birth through age nine, purpose-built survey data rather than found data. Performance was scored as $R^2$ on held-out families, relative to simply predicting the average, and the best values are the ones quoted at the start of this chapter: about a fifth of the variance for material hardship and grade point average, and almost none for grit, eviction, caregiver layoff, and job training. The four-variable expert benchmark was \"only slightly worse than the most accurate submission\". There were two further findings. The 160 teams' predictions, for all their methodological diversity, agreed with each other far more than any of them agreed with reality; and prediction error concentrated in particular *families*, not particular methods. The authors draw the conclusion carefully: the results \"suggest practical limits to the predictability of life outcomes in some settings\", and policymakers buying predictive tools for child protection or criminal justice should ask for this kind of evidence before believing vendor accuracy claims.\n\nThe finding that flexible methods did not beat a small regression is not peculiar to social surveys. @christodoulou2019 systematically reviewed 71 clinical studies, together containing 282 comparisons of machine learning methods with logistic regression for predicting a binary health outcome from tabular patient data. In the comparisons with a low risk of bias, machine learning had no performance advantage on average, measured by the AUC, a ranking-accuracy measure that @sec-evaluation defines; the comparisons that did favour machine learning were disproportionately the ones at high risk of bias, for instance because the two methods were not validated in the same way. The review also found that calibration, whether the predicted probabilities mean what they say, went unassessed in 79 percent of the studies. On tabular data of ordinary size, then, a simple model is usually hard to beat, and the appearance of a large gain is more often a sign of a flawed comparison than of a better method. @sec-overfitting explains why in terms of bias and variance, and @sec-evaluation covers the evaluation standards the review applied.\n\n**PreFer** [@sivak2024] is the designed follow-up to the Fragile Families Challenge. The task: predict which Dutch residents aged 18 to 45 will have a child in 2021 through 2023, from data through 2020, one well-theorized outcome with a deliberately short horizon. Two data sources compete. The LISS panel is wide in variables, over 30,000, including stated fertility intentions, the kind of subjective variable registers never contain, but has roughly 1,400 outcome-labelled cases; the Dutch population registers are long in cases, millions, from 1995 through 2023, including the full kinship network, but limited to objective variables. LISS is run by Centerdata and is part of ODISSEI, the Dutch national research infrastructure for the social sciences (<https://odissei-data.nl>), which also organized PreFer and gives researchers access to the registers of Statistics Netherlands. The headline metric is F1, chosen because with about one in five positives, raw accuracy flatters a model that predicts \"no child\" for everyone. **Precision** is the share of predicted births that happen; **recall** (also called sensitivity) is the share of actual births that were predicted; **F1** is their harmonic mean, $2PR/(P + R)$, which is zero as soon as either is zero, so that a model predicting no births at all scores zero. @sec-evaluation defines all three properly. Teams submit runnable methods rather than predictions, which fixes a reproducibility weakness the Fragile Families organizers discovered in their own archive. Above all, the design turns the earlier puzzle into a decomposition: if prediction fails on the survey but succeeds on the registers, the bottleneck was sample size; if the reverse, the subjective variables were what mattered; if both fail, the unpredictability starts to look like a property of lives rather than of datasets.\n\nMore than 130 participants took part; the challenge was organized by the sociology department of the University of Groningen, ODISSEI, Eyra and Centerdata, with the eScience Center, SURF and Statistics Netherlands. The most accurate models on both data sources, by F1, were those of Hanzhang Ren and Emily Cantrell [@ren2026]. Their account of the win says little about algorithms and much about data engineering. They made the survey training set larger by *time-shift augmentation*: recomputing the outcome for an earlier three-year window, 2018 through 2020, dropping the features measured after 2017, and renaming the remaining ones so that a 2017 measurement stands where a 2020 measurement stood, which turns each panel member's earlier waves into a second training row with the same temporal distance to the outcome. And they made the data wider by *partner linkage*: adding the variables of a person's spouse or cohabiting partner as features of that person, in the survey and in the registers alike. The prize for the most innovative approach went to a fourteen-person team that turned the registers into text. For four million people they generated more than 100 million \"books of life\", each a plain-language chronology of a few pages compiled from many separate register files on education, work, family and residence, and fine-tuned a large language model on those texts to predict the outcome [@verhagen2025]. The paper describes the construction of the books and releases the toolkit; the predictive results are left to a companion paper. In the organizers' summary of the results, predictive performance remained modest on both data sources; the survey-based predictions did slightly better than the register-based ones, so the subjective variables carry information that millions of register records do not replace; and combining the two sources improved predictions only slightly further. With full-population registers in play, modest accuracy can no longer be blamed primarily on small samples, which moves the Fragile Families puzzle a step closer to a conclusion about lives rather than about datasets.\n\n::: {.callout-tip icon=\"false\" title=\"Exercise 5.6\"}\n(a) In the Fragile Families Challenge, why does the common task method make \"low predictability\" a conclusion about the phenomenon rather than about the researchers? (b) The best GPA model reached $R^2 \\approx 0.19$ against a mean-prediction baseline. A press release announces: \"algorithm predicts children's school success\". Write the two-sentence correction. (c) Explain why PreFer's organizers chose F1 rather than accuracy, using the base rates given above.\n:::\n\n::: {.callout-note collapse=\"true\" icon=\"false\" title=\"Answer 5.6\"}\n(a) One hundred sixty independent teams with free choice of methods all faced the same holdout and the same metric; when the best of them barely beats a four-variable regression, \"a better analyst would have done better\" loses its plausibility, which was the design's purpose. (b) \"The best of 160 competing models explained about a fifth of the variation in GPA, leaving four fifths unexplained; it beat a four-variable regression by a few points. Individual children's outcomes remained largely unpredictable from thirteen thousand variables.\" (c) With roughly 15 to 22% positives, predicting \"no child\" for everyone scores about 80% accuracy while identifying no one; its recall is zero, so its F1, the harmonic mean of precision and recall, is zero as well.\n:::\n\n## Swings between explanation and prediction\n\nArguments about whether to focus on explanation or prediction or both are nothing new, and fields have moved from one emphasis to the other and back.\n\nMacroeconomics swung twice. In the 1970s, its large \"structural\" models, hundreds of equations of interpretable theory, predicted poorly, and @sims1980 argued for replacing them with atheoretical time-series models that let recent data forecast the near future. The forecasting improved; the approach earned Sims a Nobel prize in 2011. Then the pendulum returned: for questions about *policy*, rain-dance questions, forecasting models are silent by construction, and the following generation of economists rebuilt causal credibility with the designs and instruments of chapters 1 and 3, work honoured with its own Nobel a decade later. Both swings were rational: the field learned which of its questions were umbrella questions and which were not.\n\nPrediction has its cautionary tales too. Google Flu Trends estimated influenza incidence from search queries, faster than the official surveillance it aimed to complement, and for a while it worked; then it drifted, at one point overestimating flu prevalence by a factor of two, partly because the search engine and its users kept changing under the model [@lazer2014]. The failure is the mirror image of the Fragile Families lesson: an impressive fit on the past is a statement about the past, and a predictive model deployed in a changing world becomes a model of a world that no longer exists. Meanwhile, successes that attract less attention accumulate: clinical risk scores triage chest pain, predicted readmission risks schedule follow-up calls, and no one demands that these models explain anything, only that they keep predicting well.\n\n## What to carry forward {.unnumbered}\n\nFour results from this chapter are used in the chapters that follow. A wrong model can predict better than the true one, as the simulation of \"Prediction in its own right\" showed; this stops being a paradox once prediction error is split into bias and variance, which is the subject of @sec-overfitting. A prediction is a statement about unseen data (\"Prediction as a statement about unseen data\"), so evaluation always requires held-out data the model has not touched; @sec-overfitting names the failure, overfitting, and @sec-evaluation shows how to arrange the checking and how badly things go when the held-out data leak into the fitting. A decision's payoff has an umbrella term and a rain-dance term (\"One decision, two questions\"), and no accuracy metric can certify the second; the closing section of @sec-evaluation builds on this. The Fragile Families Challenge, PreFer and the clinical review of \"Two mass collaborations and a systematic review\" measured how far prediction gets with ordinary tabular data: a simple model is hard to beat, and much of what happens to a person is, from the standpoint of the available data, unpredictable, which @sec-overfitting reads as a high irreducible error. And the chain of @sec-rq-to-interpretation never went away: a predictive model answers its question under assumptions, chiefly that the future resembles the training data, and Google Flu (\"Swings between explanation and prediction\") shows what their violation looks like.\n\n**Terms and symbols introduced.** held-out data (holdout); root-mean-squared error (RMSE); $R^2$; overfitting performed by hand; umbrella and rain-dance decisions; action, outcome, payoff; integrative modelling; common task framework; precision, recall, F1; $X_0$ the action, $Y$ the outcome, $\\pi(X_0, Y)$ the payoff, $d\\pi/dX_0$ the total effect of the action on the payoff, $\\partial \\pi/\\partial X_0$ and $\\partial \\pi/\\partial Y$ partial derivatives of the payoff, $\\partial Y/\\partial X_0$ the causal effect of the action on the outcome; $g$, $b$ and `n_train` the three settings of the simulation.\n\n**Exercises that use R.** 5.2 and 5.3 (the simulation and the `contest()` function); 5.D (optional, a check of the population coefficient by simulation).\n\n## Further study {.unnumbered}\n\n@breiman2001 is the paper that named the two cultures, and the printed discussion that follows it, by Cox, Efron and others, is the best short statement of the data-modelling side. @shmueli2010 works out in detail why explanatory and predictive modelling call for different choices at every step, from variable selection to evaluation, and is the source of this chapter's \"wrong model wins\" argument. @kleinberg2015 introduces the umbrella and rain-dance images and the payoff decomposition, with examples from policy. @hofman2021 sets out the four-cell table and argues for integrative modelling, with a survey of computational social science to show how empty the fourth cell is. @salganik2020 and @sivak2024 describe the design and results of the Fragile Families Challenge and the design of PreFer, and repay reading in full for what the common task framework does and does not settle. @yarkoni2017 is the case for prediction in psychology, and the source of the \"overfitting by hand\" reading of the replication crisis. @james2021 is the textbook the next two chapters draw on for the machinery of prediction.\n\n## Test yourself {.unnumbered}\n\n::: {.callout-tip icon=\"false\" title=\"Exercise 5.A\"}\nA researcher has panel data on adolescents: social media use, sleep, exercise, parental monitoring, and depressive symptoms, over four years. Two goals are on the table. Goal 1: estimate the effect of social media use on depressive symptoms, for policy advice. Goal 2: flag adolescents at high risk of developing symptoms next year, so the school counsellor can reach out.\n\n(a) For each goal, which variables belong in the model, and by what criterion?\n(b) For each goal, what is the appropriate way to judge whether the model is good?\n(c) The Goal 2 model puts large weight on parental monitoring. A journalist concludes that monitoring causes depression. Explain the error, and what would go wrong if a school acted on it.\n(d) Conversely, suppose the researcher uses only the variables with credible causal effects for Goal 2's forecasting task. What is sacrificed, and why?\n:::\n\n::: {.callout-note collapse=\"true\" icon=\"false\" title=\"Answer 5.A\"}\n(a) Goal 1: variables chosen by the causal logic of chapters 1 and 3: confounders of use and symptoms must enter, mediators must stay out of the total-effect equation, and instruments or designs must carry the assumptions. Goal 2: anything measurable in advance that improves held-out prediction, including proxies with no causal standing. (b) Goal 1: by the credibility of the design and assumptions, plus uncertainty of the estimate; fit alone proves little. Goal 2: by predictive performance on held-out adolescents, with a metric suited to the base rate and to the costs of misses versus false alarms. (c) Predictors earn their weights by association, and monitoring may be a marker of parents already worried about a struggling child; acting on it causally (discouraging monitoring) could remove a response to risk rather than a cause of it, an umbrella-rain-dance confusion. (d) Predictive accuracy: causal variables are often few, weak, or hard to measure early, while non-causal markers carry real signal; a forecaster restricted to causes is a worse forecaster, which is Breiman's point.\n:::\n\n::: {.callout-tip icon=\"false\" title=\"Exercise 5.B\"}\nA team proposes to use a language model to code 40,000 open-ended survey answers about vaccine hesitancy into five categories, replacing two student coders.\n\n(a) Describe a validation design that would justify the substitution, including what quantity you would compute.\n(b) Name two failure modes specific to language models that your design should probe, and how.\n(c) The model classifies answers written in regional dialect noticeably worse. Which concept from this chapter (and from @sec-rq-to-interpretation) does this instantiate, and what would you do?\n:::\n\n::: {.callout-note collapse=\"true\" icon=\"false\" title=\"Answer 5.B\"}\n(a) Have the human coders label a random subsample (stratified over categories and respondent groups); compare model and human labels via agreement statistics such as Cohen's kappa, benchmarked against the two humans' agreement with each other; only substitute if model-human agreement approaches human-human agreement, and keep humans on a continuing audit sample. (b) Training-data contamination and drift: probe by testing on newly written answers the model cannot have seen. Systematic skew, such as sycophantic or majority-flavoured readings of ambiguous answers: probe by comparing error rates across answer types and demographic groups. (c) Differential measurement quality, a construct-validity threat, and a violation of the assumption that the instrument works equally well across units; remedies include dialect-specific validation, human coding for the affected group, or adjusting analyses for known error rates.\n:::\n\n::: {.callout-tip icon=\"false\" title=\"Exercise 5.C\"}\n\"Since the best Fragile Families models explained only a fifth of GPA variance, social science has learned nothing about child development.\" Write a short assessment (at most 200 words) that engages the strongest version of both sides.\n:::\n\n::: {.callout-note collapse=\"true\" icon=\"false\" title=\"Answer 5.C\"}\nA model answer engages both directions. For the provocation: if understanding is measured by out-of-sample prediction, the result is damning, since 750 papers' worth of variables barely beat four chosen by hand, and the shortfall was no one team's fault by design. Against it: explanation and prediction are different targets; a modest average causal effect can be real, replicable, and policy-relevant while individual outcomes stay dominated by idiosyncratic events, so low individual predictability does not refute the causal knowledge. The strong synthesis notes what the challenge actually adds: a measured ceiling, so far unexplained, which theories of development must now themselves explain; a warning for anyone deploying individual-level risk prediction in policy; and a template, extended by PreFer, for finding out whether the ceiling reflects data limits or genuine randomness in lives. \"Nothing\" overclaims; \"business as usual\" underclaims; the defensible position is that social science learned something painful and useful about the kind of knowledge it has.\n:::\n\n::: {.callout-tip icon=\"false\" title=\"Exercise 5.D (optional)\"}\nThis last exercise is optional and harder than the others: it derives, in algebra, the coefficient that the simulation of Exercise 5.2 converges to. Nothing later in the book depends on it, although @sec-overfitting uses the same calculation.\n\nIn the data-generating process of the simulation, `exercise` $= g\\,U + e_1$ and `symptoms` $= g\\,U + b\\,M + e_2$, where $U$ is motivation, $M$ is medication, and $U$, $M$, $e_1$, $e_2$ are independent standard normal variables.\n\n(a) Derive the population regression coefficient of `symptoms` on `exercise` alone, as a function of $g$, and evaluate it at $g = 3$. (The regression coefficient of $Y$ on $X$ is $\\operatorname{Cov}(X, Y)/\\operatorname{Var}(X)$.) How does it compare with the $0.99$ that `coef(fit_wrong)` printed?\n(b) Show that adding `medication` to the regression leaves the coefficient of `exercise` unchanged. Check both results by running `generate_data(1e6)` and fitting the two regressions.\n(c) Why, then, does the chapter say that no regression on the observed columns can fix the exercise coefficient? Which variable would fix it, and what does that say about adjustment in general?\n:::\n\n::: {.callout-note collapse=\"true\" icon=\"false\" title=\"Answer 5.D\"}\n(a) $\\operatorname{Cov}(\\text{exercise}, \\text{symptoms}) = g^2 \\operatorname{Var}(U) = g^2$, since the disturbances and $M$ are independent of everything else, and $\\operatorname{Var}(\\text{exercise}) = g^2 + 1$. The coefficient is $g^2/(g^2 + 1)$, which is $0.9$ at $g = 3$. The $0.99$ in the chapter is this value plus sampling noise from twenty observations; a sample of a million gives $0.90$.\n(b) `medication` is independent of both `exercise` and $U$, so partialling it out changes neither the covariance of `exercise` with `symptoms` nor its variance; the coefficient stays $g^2/(g^2 + 1)$, and the coefficient of `medication` converges to $b$. In a sample of a million both regressions put `exercise` at $0.90$.\n(c) The exercise coefficient is entirely the spurious part carried by $U$, and the only variable that would remove it is $U$ itself, motivation, which is not observed. Adjustment removes confounding only by measured confounders, which was Exercise 1.D(g), and the coefficient's gap from the true effect of zero is the bias term of @sec-overfitting: no sample size reduces it.\n:::\n",
    "supporting": [
      "05-explanation-prediction_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{},\"value\":[]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}