{
  "hash": "07b2ad6f4361cc35a8843b37356287d5",
  "result": {
    "engine": "knitr",
    "markdown": "# Machine learning II: evaluating predictions honestly {#sec-evaluation}\n\nBetween 2015 and 2020 the American Food and Drug Administration cleared 130 medical devices that run on artificial intelligence. Researchers who read every approval found that 126 of the 130 had been evaluated only retrospectively, on stored data, and that for 93 there was no publicly reported evaluation at more than one site [@wu2021]. None of the 54 highest-risk devices had been tested prospectively on the patients they would actually serve.\n\n@sec-overfitting ended with a claim and a caveat. Once the task and the performance measure are fixed, modelling choices can be settled empirically; but the settling has to be honest, because the same overfitting that inflates a model's apparent fit will inflate the evaluation of the model just as easily. Honesty here consists of three techniques: choosing a performance measure that fits the task, keeping the data that judge a model strictly out of the choices that built it, and recycling scarce data through resampling. After all three comes the question of how honestly evaluated models fare in actual use, which closes the chapter.\n\n::: {.callout-note appearance=\"simple\" icon=\"false\" title=\"Optional in this chapter\"}\nDecision curve analysis (net benefit compared with treating everyone and treating no one across a range of thresholds; the definition of net benefit that precedes it is required, because Exercise 7.3 uses it); the footnote on the jackknife and the out-of-bag error in \"Resampling: cross-validation, bootstrap, jackknife\". Everything else is required, as are all inline exercises.\n:::\n\n## Performance metrics for continuous and binary outcomes\n\nIn machine learning, defining the performance metric is defining success, so the metric should be chosen with care to fit the task. Many metrics exist, but in practice a modest number account for most use, and this section defines those, first for continuous outcomes and then for binary ones.\n\nFor a continuous outcome, write $y_i$ for the observed outcome of test case $i$, $\\hat y_i$ for the model's prediction of it, and $m$ for the number of test cases. The most common metric is the mean squared error familiar from @sec-overfitting, usually reported as its square root so that it is in the outcome's own units, the **root mean squared error**:\n\n$$\n\\text{RMSE} = \\sqrt{\\frac{1}{m} \\sum_{i=1}^{m} (y_i - \\hat y_i)^2} .\n$$\n\nAn RMSE of 1.3 days on a length-of-stay model means the predictions miss by about 1.3 days on a typical case. Because the errors are squared before averaging, large misses count disproportionately: one prediction that is off by ten days contributes as much as a hundred predictions off by one day. The more outlier-tolerant alternative, the **mean absolute error**,\n\n$$\n\\text{MAE} = \\frac{1}{m} \\sum_{i=1}^{m} \\lvert y_i - \\hat y_i \\rvert ,\n$$\n\nweighs every unit of error equally, so a few extreme cases cannot dominate the verdict. The third common metric compares the model against the simplest possible competitor, predicting the training mean $\\bar y$ for everyone. The **out-of-sample $R^2$** is the fraction by which the model's squared error improves on that benchmark:\n\n$$\nR^2_{\\text{oos}} = 1 - \\frac{\\sum_{i=1}^{m} (y_i - \\hat y_i)^2}{\\sum_{i=1}^{m} (y_i - \\bar y_{\\text{train}})^2} .\n$$\n\nUnlike the in-sample $R^2$ of @sec-explanation-prediction, this quantity can be negative: an overfitted model can predict fresh data *worse* than the mean does, in which case the numerator exceeds the denominator. A negative out-of-sample $R^2$ is a common and instructive experience for newcomers to prediction.\n\nAll three metrics are averages of a **loss function**, a rule $L(e)$ that converts one prediction error $e_i = y_i - \\hat y_i$ into a penalty, and the choice of metric is really the choice of that rule's shape. (The symbol is $L$, not the $\\ell$ of @def-likelihood, which is the log-likelihood; the log-likelihood reappears below as one such loss.) @fig-losses draws four. Squared error is a U: small penalties near zero, large ones in the tails. Absolute error is a V: every unit of error costs the same. The Huber loss splices the two, quadratic near zero and linear beyond, combining most of the squared loss's smoothness with most of the absolute loss's robustness to outliers. The fourth shape is less common but useful: an **asymmetric** loss charges more for errors in one direction than the other. Such losses are less used than the symmetric ones, but they are appropriate whenever the two directions of error have different costs, as they often do: understaffing a ward is worse than overstaffing it, and underestimating a flood level is worse than overestimating it. Minimizing an asymmetric linear loss amounts to predicting a chosen *quantile* of the outcome rather than its mean, which is why this loss is also called the quantile (or pinball) loss, and quantile regression is its regression form.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Four loss functions: the penalty (vertical) attached to a prediction error of a given size and sign (horizontal). Squared error is a U, absolute error a V, the Huber loss a splice of the two, and the asymmetric (quantile) loss a tilted V, here charging four times more for under-prediction than for over-prediction.](07-evaluation-resampling_files/figure-html/fig-losses-1.png){#fig-losses width=720}\n:::\n:::\n\n\n::: {.callout-tip icon=\"false\" title=\"Exercise 7.1\"}\nChoose the primary performance measure, and defend it in a sentence, for each task.\n\n(a) Predicting length of hospital stay in days, to plan staffing.\n(b) The same model, once the hospital says that a ward with too few staff costs it far more than a ward with too many.\n:::\n\n::: {.callout-note collapse=\"true\" icon=\"false\" title=\"Answer 7.1\"}\n(a) RMSE or MAE, in days: the outcome is continuous and the cost of error is roughly proportional to its size; MAE if a few extreme stays should not dominate.\n(b) An asymmetric (quantile) loss that charges more for predicting too short a stay than too long a one. Minimizing it predicts an upper quantile of the stay rather than its mean, which is what a planner who prefers to overstaff wants; RMSE would treat the two directions of error as equally costly, which the hospital has just said they are not.\n:::\n\nBinary outcomes are more complex, because a prediction model for a binary outcome produces a *probability*, and a probability can be good or bad in two different ways, discrimination and calibration, both defined below. The simplest way to use a predicted probability is to **threshold** it: declare everyone above some cutoff \"positive\". Each prediction then lands in one of four cells: a **true positive** (a case correctly flagged), a **false positive** (a non-case flagged), a **true negative** (a non-case left alone), or a **false negative** (a case missed). From the four counts come the two workhorses of diagnostic research. **Sensitivity** (also called *recall*, or the true-positive rate) is the fraction of true cases the model flags,\n\n$$\n\\text{sensitivity} = \\frac{\\text{TP}}{\\text{TP} + \\text{FN}},\n\\qquad\n\\text{specificity} = \\frac{\\text{TN}}{\\text{TN} + \\text{FP}},\n$$\n\nand **specificity** is the fraction of non-cases it does not flag. The two pull against each other as the threshold moves: lower the cutoff and more cases are flagged, so sensitivity rises, but more non-cases are flagged with them, so specificity falls. Neither number means anything alone, because either can be made perfect trivially: flag everyone and sensitivity is 1, flag no one and specificity is 1. The left panel of @fig-roc shows the trade for a real model, a logistic regression predicting diabetes that is introduced in full at the end of this section.\n\nThe same four counts yield **precision**, the fraction of flags that are right; **accuracy**, the fraction of all calls that are right; and the **F1 score**, a compromise between precision and sensitivity, their harmonic mean:\n\n$$\n\\text{precision} = \\frac{\\text{TP}}{\\text{TP} + \\text{FP}},\n\\qquad\n\\text{accuracy} = \\frac{\\text{TP} + \\text{TN}}{m},\n\\qquad\n\\text{F1} = \\frac{2 \\cdot \\text{precision} \\cdot \\text{sensitivity}}{\\text{precision} + \\text{sensitivity}} = \\frac{2\\,\\text{TP}}{2\\,\\text{TP} + \\text{FP} + \\text{FN}} .\n$$\n\nTwo warnings apply to this family. Their values depend on the threshold, which is a decision about costs, not a property of the model, so reporting them without defending the threshold conveys nothing. And accuracy in particular is misleading whenever one class is rare: a model that predicts \"no dropout\" for every pupil scores 91 percent accuracy on a 9 percent base rate, as Exercise 6.C showed. A third warning needs a definition. A performance measure, or a loss, is **proper** when a model that reports the true probabilities scores best on it; a proper measure cannot be improved by reporting something other than what the model believes. F1 is not proper: a model supplying the correct probabilities is not guaranteed to optimize it, and the recent guidance from the STRATOS initiative advises against F1 for clinical decisions on that ground [@vancalster2025]. The word returns below, where it separates methods whose outputs are probabilities from methods whose outputs only look like them.\n\nA threshold-free summary follows from sweeping the threshold across its whole range. As the cutoff falls from 1 to 0, the pair (sensitivity, specificity) traces out every operating point the model can offer; plotting sensitivity against $1 - \\text{specificity}$, the false-positive rate, draws the **receiver operating characteristic (ROC) curve**, shown in the right panel of @fig-roc. A model no better than chance runs along the diagonal, since flagging patients at random buys sensitivity and false positives in equal measure; a model with perfect separation hugs the upper-left corner. The area under this curve, the **AUC**, compresses the whole trade into one number between 0.5 (a coin flip) and 1 (perfect ranking), and it equals the **concordance statistic**, or c-statistic: take a random case and a random non-case, and the c-statistic is the probability that the model ranks them correctly [@riley2024part2]. This is the standard measure of **discrimination**, the first of the two ways a probability can be good: do the babies who will be born underweight get higher probabilities than the ones who will not? Discrimination uses only the *ordering* of the probabilities; their actual values could all be shifted or squeezed without changing it.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Building the ROC curve for the diabetes model of this section. Left: sensitivity and specificity as the threshold moves; each vertical slice is one confusion matrix. Right: the same information with the threshold swept from 1 to 0, plotting sensitivity against the false-positive rate; four thresholds are marked. The shaded area is the AUC (here 0.87); the diagonal is a model no better than chance.](07-evaluation-resampling_files/figure-html/fig-roc-1.png){#fig-roc width=768}\n:::\n:::\n\n\n**Calibration** is the second way a probability can be good, and it asks whether the probabilities mean what they say: among patients given a risk of 20 percent, do about 20 in 100 have the event [@vancalster2026]? A model can discriminate superbly and be badly calibrated, or the reverse, because ranking uses only the order of the probabilities and calibration only their values. The workhorse summaries are the **calibration intercept**, which catches predictions that are too high or too low overall (agreement between the mean prediction and the event rate is called *calibration-in-the-large*), and the **calibration slope**, which catches predictions that are too extreme or too timid: a slope below 1 means the model's high risks are too high and its low risks too low, the signature of overfitting [@vancalster2025]. Calibration has been called \"the Achilles heel of predictive analytics\" [@vancalster2019]: a systematic review found it unassessed in 79 percent of studies comparing prediction methods [@christodoulou2019]. Not every use of a model requires calibrated probabilities, but decision-making usually does: when a probability is weighed against the costs and benefits of acting on it, the probability itself must be right. Calibration therefore matters most in settings where the model's numbers feed decisions.\n\nCalibration is estimated in a test sample by grouping the cases into bins by predicted probability and comparing each bin's average prediction with its observed event rate, as in @fig-calibration. Perfectly calibrated predictions put every bin on the diagonal, and the vertical distances from the diagonal are the average deviations that the miscalibration term below summarizes. The intercept and slope are estimated by a logistic regression of the outcome on the model's own predicted log-odds, $\\log[\\hat p/(1 - \\hat p)]$, which R computes with `qlogis`, the inverse of the `plogis` of @sec-theory-to-glm. If the probabilities are right, that regression has intercept 0 and slope 1; the calibration slope is the slope of that regression, and the fitted curve through the points in @fig-calibration is that regression drawn on the probability scale. The left panel shows the logistic diabetes model of this section: its bins hug the diagonal, and its fitted slope is close to 1.\n\nThe right panel shows something practitioners meet constantly: a machine learning method whose output is *called* a probability but is not calibrated. Boosted classification trees, fitted to the same data with the classic AdaBoost loss, produce a number between 0 and 1 for each patient, and those numbers rank patients respectably (AUC 0.78). But they are pushed hard toward 0 and 1, far more extreme than the observed rates justify, and the calibration slope collapses to about 0.3.^[AdaBoost fits its trees by minimizing an exponential loss of the *margin*, the product of the outcome coded $\\pm 1$ and the model's score, and the score is a weighted vote of the trees. The number reported as a probability is a transformation of that vote, and neither the loss nor the vote was fitted on the probability scale; see chapter 10 of @hastie2009.] The difference between the panels comes from the loss each method minimized. Calibration can be expected only from a model fitted by minimizing a proper loss, in the sense defined above: one whose minimizer is the true probability, such as the negative of the log-likelihood of @def-likelihood (maximizing the one is minimizing the other) or the Brier score below. Logistic regression is fitted by maximum likelihood, so on its own training data its mean prediction equals the observed rate, and on new data its probabilities are approximately calibrated as long as the model is not overfitted. A proper loss makes calibration possible, not automatic: the overfitted logistic regression fitted later in this section has a calibration slope of 0.63, because it was fitted to noise as well as to signal. AdaBoost's exponential loss is not a proper loss for probabilities, and vote fractions, margins and similar scores are not fitted to any loss on the probability scale at all; such outputs can rank well while their values mean little, and they need recalibration before anyone treats them as probabilities.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Calibration in a test sample, for the logistic diabetes model (left) and boosted trees fitted with the AdaBoost loss on the same data (right). Points: tenths of the test sample by predicted probability, average prediction against observed event rate. The dashed diagonal is perfect calibration; the solid curve is the fitted calibration line, whose intercept and slope are the summaries in the text. The boosted trees' outputs rank patients respectably but are far too extreme: predictions near 0 and 1 correspond to observed rates nowhere near 0 and 1, and the slope collapses to 0.3.](07-evaluation-resampling_files/figure-html/fig-calibration-1.png){#fig-calibration width=768}\n:::\n:::\n\n\n::: {.callout-tip icon=\"false\" title=\"Exercise 7.2\"}\nChoose the primary performance measure, and defend it in a sentence, for each task.\n\n(a) Flagging one in a thousand transactions as fraud for human review, where a review costs little and a missed fraud costs much.\n(b) Giving women an individual probability of successful vaginal birth after a previous caesarean, to support their choice.\n(c) PreFer once more, from @sec-explanation-prediction: predicting which residents will have a child within three years, base rate about one in five.\n:::\n\n::: {.callout-note collapse=\"true\" icon=\"false\" title=\"Answer 7.2\"}\n(a) Sensitivity at a fixed, defensible review budget (equivalently precision among the flagged): the threshold is set by review capacity, and accuracy is worthless at a 0.1 percent base rate.\n(b) Calibration, above all: the number is handed to a person as a probability, so it must mean what it says; discrimination matters but a well-ranked, miscalibrated probability actively misleads the choice.\n(c) F1 was their choice, balancing precision and recall (sensitivity) against the one-in-five base rate; note the STRATOS caution that F1 is improper, which matters when the probabilities themselves, rather than a flag, are the product. For a leaderboard with a fixed flagging rule it is a defensible tournament metric.\n:::\n\nDiscrimination and calibration are the two components of a single overall error. Score each predicted probability $\\hat p_i$ against its 0/1 outcome by squared error, giving the mean squared error on the probability scale, known as the **Brier score**. Group the test cases into $K$ bins by their predicted probability, with $w_k$ the fraction of cases in bin $k$, $\\bar p_k$ the bin's mean prediction, $\\bar y_k$ its observed event rate, and $\\bar y$ the overall event rate. The Brier score then decomposes, approximately, as [@murphy1973]\n\n$$\n\\underbrace{\\frac{1}{m} \\sum_{i=1}^{m} (\\hat p_i - y_i)^2}_{\\text{Brier score}}\n\\;\\approx\\;\n\\underbrace{\\sum_k w_k (\\bar p_k - \\bar y_k)^2}_{\\text{miscalibration}}\n\\;-\\;\n\\underbrace{\\sum_k w_k (\\bar y_k - \\bar y)^2}_{\\text{discrimination}}\n\\;+\\;\n\\underbrace{\\bar y (1 - \\bar y)}_{\\text{irreducible}} .\n$$\n\nThe first term charges the model wherever a bin's predictions miss that bin's observed rate, which is miscalibration. The second term is subtracted, so it is a reward: it grows when the bins' event rates spread far from the base rate, that is, when the model sorts patients into genuinely different risk groups, which is discrimination. The last term is the outcome's own variance, the error that remains for a perfectly calibrated, maximally discriminating model, the binary counterpart of the noise floor $\\sigma^2$ in @eq-bias-variance. The decomposition is exact when every prediction in a bin equals the bin mean; with continuous predictions grouped into bins there is a small leftover term from the variation of the predictions within bins, which Exercise 7.D computes. A model improves its Brier score only by both discriminating well and being calibrated. The Brier score is a proper measure: like the negative log-likelihood, it is minimized by the true probabilities, and both are the kind of loss the previous paragraph asked for.\n\nThe measure that faces the decision directly is the **net benefit**. At a chosen treatment threshold $p_t$, the probability above which a patient is treated, it is the rate of true positives minus the rate of false positives, the latter weighted by the odds of the threshold:\n\n$$\n\\text{NB} = \\frac{\\text{TP}}{m} - \\frac{\\text{FP}}{m} \\cdot \\frac{p_t}{1 - p_t} .\n$$\n\nThe weight prices a false flag by the threshold itself: a clinician who treats at $p_t = 0.2$ has said that one unnecessary treatment costs a quarter of what one missed case costs, and the formula charges the model at that rate [@riley2024part2]. The natural comparisons are the two policies that need no model, treating everyone, whose net benefit is the event rate minus the non-event rate times the same odds, and treating no one, whose net benefit is zero.\n\nThe core set can now be computed once, on a real problem: the model behind @fig-roc. The `MASS` package ships a study of diabetes among 532 Pima women, already split by its curators into a training set of 200 and a test set of 332; the model is a logistic regression, the workhorse of @sec-theory-to-glm, here judged on held-out data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(MASS)\nfit_pima <- glm(type ~ ., data = Pima.tr, family = binomial)\np_hat    <- predict(fit_pima, newdata = Pima.te, type = \"response\")\ny     <- as.numeric(Pima.te$type == \"Yes\")\n\nauc <- function(p, y) {                    # P(random case outranks random non-case)\n  mean(outer(p[y == 1], p[y == 0], \">\")) +\n  0.5 * mean(outer(p[y == 1], p[y == 0], \"==\"))\n}\ncal <- glm(y ~ qlogis(p_hat), family = binomial)   # regress outcome on the log-odds\nround(c(AUC = auc(p_hat, y), cal_slope = coef(cal)[2],\n        mean_predicted = mean(p_hat), observed_rate = mean(y)), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                    AUC cal_slope.qlogis(p_hat)          mean_predicted \n                  0.866                   0.953                   0.337 \n          observed_rate \n                  0.328 \n```\n\n\n:::\n:::\n\n\nThe two-line `auc` function implements the definition directly: compare every case with every non-case and count the correctly ordered pairs. The line that defines `cal` is the calibration regression described above, the outcome on the model's own log-odds `qlogis(p_hat)`, so `coef(cal)[2]` is the calibration slope. The model discriminates well (0.87) and is well calibrated: slope 0.95, and a mean predicted risk of 0.337 against an observed rate of 0.328. Refitting the same model with twenty pure-noise predictors added, the overfitting recipe of @sec-overfitting, shows how calibration breaks:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(12)\ntr <- Pima.tr; te <- Pima.te\nfor (j in 1:20) { tr[[paste0(\"junk\", j)]] <- rnorm(nrow(tr))\n                  te[[paste0(\"junk\", j)]] <- rnorm(nrow(te)) }\np2   <- predict(glm(type ~ ., data = tr, family = binomial),\n                newdata = te, type = \"response\")\ncal2 <- glm(y ~ qlogis(p2), family = binomial)\nround(c(AUC = auc(p2, y), cal_slope = coef(cal2)[2]), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                 AUC cal_slope.qlogis(p2) \n               0.830                0.628 \n```\n\n\n:::\n:::\n\n\nThe AUC slips from 0.87 to 0.83, a modest deterioration. The calibration slope collapses to 0.63: the overfitted model pushes predictions toward 0 and 1 with a confidence the data do not support. This asymmetry is general. Overfitting degrades ranking slowly and degrades probabilities fast, so a report that gives only the AUC can hide most of the damage [@vancalster2019].\n\nChoosing the metric comes before everything else, and getting it wrong can do more harm than any error of modelling. A widely used American algorithm prioritized patients for extra care by predicting health care *costs*, a convenient label present in every record. It predicted costs well, but at any given risk score, Black patients were considerably sicker than White patients, because less money is spent on Black patients at the same level of need; the label was a biased proxy for the target, a failure of construct validity in the sense of @sec-rq-to-interpretation. Fixing the target roughly tripled the fraction of Black patients flagged for help, from 17.7 to 46.5 percent [@obermeyer2019]. The problem lay in the task, not in any metric of this section. By Mitchell's definition, performance is relative to the task as specified, not the task intended.\n\n::: {.callout-tip icon=\"false\" title=\"Exercise 7.3\"}\nTen patients receive predicted risks $0.05, 0.10, 0.15, 0.20, 0.35, 0.40, 0.60, 0.70, 0.80, 0.90$; their outcomes are $0, 0, 0, 1, 0, 1, 0, 1, 1, 1$.\n\n(a) Compute the c-statistic by counting concordant pairs. (There are $5 \\times 5 = 25$ pairs.)\n(b) Group the patients into \"low\" (the five smallest risks) and \"high\" (the five largest). Compare mean predicted risk with the observed rate in each group. What does this tell you that (a) does not?\n(c) At a treatment threshold of 50 percent, compute sensitivity, specificity, and net benefit, and compare the net benefit with treating everyone.\n:::\n\n::: {.callout-note collapse=\"true\" icon=\"false\" title=\"Answer 7.3\"}\n(a) Cases have risks $0.20, 0.40, 0.70, 0.80, 0.90$; non-cases $0.05, 0.10, 0.15, 0.35, 0.60$. Counting pairs where the case outranks the non-case: $0.20$ beats three, $0.40$ beats four, and $0.70$, $0.80$, and $0.90$ each beat all five: $3 + 4 + 5 + 5 + 5 = 22$ of 25, so $c = 0.88$.\n(b) Low group: mean prediction $0.17$, observed $1/5 = 0.20$. High group: mean prediction $0.68$, observed $4/5 = 0.80$. Predictions run slightly timid at the top, a slope slightly above 1; with ten patients this is a sketch of a calibration plot, not an estimate, which is why part 3 of the BMJ series finds that calibration needs hundreds of events to assess [@riley2024part3].\n(c) Flagged: the four with risk $\\ge 0.60$, of whom three are cases. Sensitivity $3/5 = 0.60$; specificity $4/5 = 0.80$. Net benefit $= 3/10 - (1/10)(0.5/0.5) = 0.20$. Treating everyone: $5/10 - (5/10)(1) = 0$. The model's policy beats both treat-all and treat-none at this threshold.\n:::\n\n### Decision curve analysis\n\n*Optional. If you skip this section, take with you that net benefit, unlike the other metrics, compares using the model with the two policies that need no model, and so answers whether deciding by the model does more good than harm.*\n\nA threshold is a statement about costs, and different clinicians and patients hold different ones. **Decision curve analysis** plots a model's net benefit against the threshold across the range of thresholds anyone might reasonably hold, and draws the net benefit of treating everyone and of treating no one on the same axes [@vickers2006; @riley2024part2]. Where the model's curve lies above both, deciding by the model does more good than harm for people who hold that threshold; where it lies below either, the model should not be used at that threshold, whatever its AUC. In Exercise 7.3, the net benefit of the model's policy at the 50 percent threshold, 0.20, exceeds both treat-all (0) and treat-none (0), which is one point of such a curve. The analysis answers a question the other metrics do not, and it needs no estimate of the actual costs: the threshold carries them. Its limits are those of every metric in this section. It measures a policy on the judging data, and whether the policy improves what happens to patients is the causal question that the section on external validation and deployment returns to.\n\n## Splitting the data: training, validation and test sets\n\nWith a metric in hand, the next question is which data may legitimately produce the number. In @sec-overfitting the answer was easy, because the world there was simulated: whenever fresh data were needed to judge a model, ten thousand new observations could be drawn directly from the data-generating process. Real research has no such source. There is one dataset, and the only way forward is to *assume* that this dataset comes from the same data-generating process as the future cases the model is meant to serve. This is a large assumption, and it is the assumption of external validity in the sense of @sec-rq-to-interpretation. No calculation on the data can establish it; it is supported, or undermined, by the design that produced the data. Under that assumption, however, the dataset itself can stand in for the data-generating process: parts of it can be set aside and treated as the \"fresh\" observations the simulation provided for free.\n\nThe standard way to do this divides the data three ways [@ng2018], as @fig-split shows. The **training set** is used to fit models: to estimate their coefficients, grow their trees, and so on. The **validation set** (or development set) is used to compare models and to make choices: which polynomial degree, which penalty $\\lambda$, which model family, which coding of the predictors. Each candidate is fitted on the training set and scored on the validation set, and the choices go to whichever scores best. The **test set** is used for one thing only, and only once: after every choice has been made, it estimates the performance of the final model. That estimate is trustworthy because the test set influenced none of the choices. (The word *validation* here has nothing to do with the validities of @sec-rq-to-interpretation; it names a check of a fitted model against data, and it returns in that sense later in the chapter as internal and external validation.) In practice the validation set is often not a separate block of data: cross-validation on the training set, described in the resampling section below, plays the role of the validation set in @fig-split, and the Pima example of this chapter uses that arrangement, a training set with cross-validation inside it and a separate test set.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![The three-way split. The training set fits each candidate model, the validation set scores the candidates and settles every choice among them, and the test set is touched once, at the very end, to estimate the performance of the final model.](07-evaluation-resampling_files/figure-html/fig-split-1.png){#fig-split width=624}\n:::\n:::\n\n\nWhy the middle set is necessary follows from the lesson of @sec-overfitting, now applied to the analyst rather than the model. Selection inflates performance estimates. When twenty modelling choices are compared on the same held-out data and the winner's score is reported, that score is optimistic, for the same reason that the winner of twenty coin-flipping contests appears skilled: the winner was partly selected for its luck on those particular data. The more choices are compared, the larger the inflation. A dedicated validation set contains this problem: it absorbs all the comparisons, so that the test set remains untouched. If the test set is used anyway, revisited after each adjustment, it gradually turns into a second validation set and its estimate inherits the same optimism. The practice is common enough to have names, leaderboard chasing and benchmark hacking, and it is the fishing of @sec-rq-to-interpretation in a new setting. (A shared benchmark used *once per team*, with a referee guarding the holdout, is the constructive version of the same arrangement, whose achievements @sec-explanation-prediction described; the problem begins when the holdout is used a second time.)\n\nThe most consequential advice concerns what the test set should contain: data that mirror the situation the model will actually face, in Ng's words \"data you expect to get in the future and want to do well on\" [@ng2018]. If the model will run on next year's patients, the test set should hold the most recent patients available, not a random shuffle of the past; if it will run in other schools, the test set should hold schools left out whole. A random split answers only the narrow question of how well the model does on more data exactly like its training data, and every step away from that ideal, in time, place, or population, is an unstated assumption of the evaluation. The composition of the test set is a design decision, and it determines which question the estimate answers.\n\n## Leakage\n\nRecall the argument of @sec-overfitting: questions about modelling choices can be settled by measuring output validity alone, without winning arguments about assumptions, *provided the measurement is honest*. That way of working rests entirely on honest evaluation, and this section is about the ways evaluation is compromised. When information from the held-out data reaches the model, or the choices around the model, the evaluation is contaminated; this is called **leakage**. It does not make the model worse; it makes the evaluation falsely optimistic.\n\n@fig-leakage shows the standard way this happens: a preprocessing step applied to the full dataset *before* the split. Once the step has seen every row, the rows later declared \"held out\" have already influenced the pipeline that will be judged on them, and the split no longer separates anything.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![How leakage happens. Top: a preprocessing choice (here, selecting promising variables) is made on the full dataset, so the rows that later serve as test data have already shaped the model that will be judged on them; the evaluation is contaminated. Bottom: the same choice made after the split, using training rows only, leaves the test set untouched by every choice it will judge.](07-evaluation-resampling_files/figure-html/fig-leakage-1.png){#fig-leakage width=624}\n:::\n:::\n\n\nStated in full generality, the principle behind leakage shows that overfitting the evaluation and the p-hacking of @sec-rq-to-interpretation are the same error. Any choice that could have come out differently had the data been different is part of the modelling procedure, and it belongs inside the evaluation loop: the held-out data must not have been able to influence it. Fitting coefficients is such a choice, and everyone remembers to hold data out from the fitting. But standardizing the predictors, imputing missing values, and, most dangerous of all, selecting promising variables are also such choices, and these are easy to forget, because they do not feel like modelling: they happen before the model, and often by hand rather than inside a fitting algorithm. Do them on the full dataset and only then split or cross-validate, and every fold's \"unseen\" data have already shaped the pipeline that predicts them. Hastie, Tibshirani and Friedman give a demonstration. Fifty observations, 5,000 pure-noise predictors, true error necessarily 50 percent: screen the 100 predictors most correlated with the outcome on all fifty observations, then cross-validate a classifier built on the survivors, and the cross-validation reports 3 percent error [@hastie2009]. Their diagnosis: the screened predictors \"have already seen\" the held-out samples. The same trap can be demonstrated at small scale, with the repair alongside:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(class)\nset.seed(11)\nn <- 50; p <- 2000\nX <- matrix(rnorm(n * p), n, p)              # pure noise\ny <- factor(rep(c(0, 1), each = n / 2))      # labels unrelated to X\nfolds <- sample(rep(1:5, length.out = n))\n\ncv_error <- function(screen) mean(sapply(1:5, function(f) {\n  tr   <- folds != f\n  keep <- screen(tr)                          # which 50 predictors to use\n  pred <- knn(X[tr, keep], X[!tr, keep], y[tr], k = 1)\n  mean(pred != y[!tr])\n}))\nscreen_all  <- local({                        # WRONG: screened on all 50 rows\n  top <- order(abs(cor(X, as.numeric(y))), decreasing = TRUE)[1:50]\n  function(tr) top\n})\nscreen_fold <- function(tr)                   # RIGHT: screened inside each fold\n  order(abs(cor(X[tr, ], as.numeric(y[tr]))), decreasing = TRUE)[1:50]\n\nc(wrong = cv_error(screen_all), right = cv_error(screen_fold))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nwrong right \n 0.08  0.46 \n```\n\n\n:::\n:::\n\n\nThe data are noise; no classifier can beat 50 percent. Screening before cross-validating reports 8 percent error, an apparently publishable classifier built from pure noise. Screening inside each fold reports 46 percent, the truth up to simulation error. The rule that generalizes, in ESL's words: \"with a multistep modeling procedure, cross-validation must be applied to the entire sequence of modeling steps. In particular, samples must be 'left out' before any selection or filtering steps are applied\" [@hastie2009]. Every decision that looked at the outcome belongs inside the loop. Steps that never touch the outcome, dropping constant columns, say, are exempt.\n\nWhen a decision is itself made by cross-validation, tuning $\\lambda$ for a lasso, say, the same principle leads to **nested cross-validation**. The outer loop is the ordinary one: each outer fold is held out in turn, and the whole pipeline is fitted to the remaining folds. Inside each outer training portion, a second cross-validation, the inner loop, compares the candidate values of $\\lambda$ and picks one; the pipeline is then refitted on the whole outer training portion with that value and scored on the outer held-out fold. The outer folds never judge a choice they influenced, because the choice was made without them, and the inner loop plays the role of the validation set of @fig-split inside each round of the outer loop. The cost is computation, $K$ inner cross-validations inside $K$ outer folds. Reporting the best cross-validated score from a single, un-nested loop instead reports the winner of a contest that the same data judged, which is the selection optimism of the previous section.\n\nTime is the other major source of leakage. Predicting this quarter's outcomes with a model whose features include next quarter's information, or randomly shuffling patients' repeated visits across the train-test boundary so the model meets the same patient on both sides, produces the same false optimism. The clustered version matters especially in this book. Pupils sit inside schools and measurements sit inside persons, the multilevel structure of @sec-anova; split such data by row and the split leaks identity, because the model meets the same school or person on both sides. The split that matches the claim holds out whole schools or whole persons, the unit the model must generalize across.\n\n::: {.callout-tip icon=\"false\" title=\"Exercise 7.4\"}\nA colleague's script, in outline: (1) load 400 patients with 5,000 gene expressions; (2) impute missing values using column means; (3) keep the 50 genes most correlated with relapse; (4) standardize them; (5) tune a lasso by 10-fold cross-validation; (6) report the best cross-validated AUC as the model's performance.\n\n(a) Identify each step that leaks, and say what information travels where.\n(b) Rewrite the outline so that it is honest, using only the same 400 patients.\n(c) Even your repaired pipeline yields a number with one remaining, subtler optimism. What is it, and which dataset would cure it?\n:::\n\n::: {.callout-note collapse=\"true\" icon=\"false\" title=\"Answer 7.4\"}\n(a) Step (3) is the fatal leak: screening on all 400 patients lets every fold's test cases influence which genes the model sees, the ESL trap. Steps (2) and (4) leak too, mildly: means and standard deviations computed on all rows carry test-fold information into the training folds. Step (6) adds selection optimism: the *best* cross-validated AUC over the tuning path is a maximum, not an estimate.\n(b) Split into folds first. Within each fold's training portion: impute from training means, screen genes, standardize by training statistics, fit the lasso path; then apply that frozen pipeline to the held-out fold. Choose $\\lambda$ by an inner cross-validation nested inside the training portion, so the outer folds never judge a choice they influenced.\n(c) All 400 patients come from one study, one lab, one moment; the number estimates performance for exchangeable patients from that same source, patients who could have been in the sample and differ from those who were only by chance. Only external validation, a dataset from different sites or later years, tests the transfer that clinical use assumes.\n:::\n\n## Resampling: cross-validation, bootstrap, jackknife\n\nA three-way split requires a large sample. With 200 observations, reserving a third of them for testing wastes data the model needs, and a single small test set gives a noisy verdict anyway; these are the two standard drawbacks of the simple holdout [@james2021]. Resampling methods let one dataset play both roles, repeatedly and honestly.\n\n**K-fold cross-validation** divides the data into $K$ equal parts, called folds; each fold in turn is held out while the model, the whole pipeline, is fitted to the remaining folds and scored on the held-out one, and the $K$ scores are averaged. @fig-kfold shows the scheme.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Five-fold cross-validation on twenty observations. Each row is one round: the whole modelling pipeline is fitted to the light observations and scored on the dark held-out fold, and the five scores are averaged into the cross-validated estimate.](07-evaluation-resampling_files/figure-html/fig-kfold-1.png){#fig-kfold width=624}\n:::\n:::\n\n\nThe choice of $K$ is itself a bias-variance trade. $K = n$, leave-one-out, trains on almost all the data every time, so it is nearly unbiased for the error of the full-sample model, but its $n$ training sets are nearly identical, and averaging highly correlated verdicts controls variance poorly; small $K$ trains on less data, biasing the error estimate upward. Both ISL and ESL land on the same compromise: five or ten [@james2021; @hastie2009]. Cross-validated performance on the Pima training set, next to the two numbers we already have:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(14)\nfolds  <- sample(rep(1:10, length.out = nrow(Pima.tr)))\ncv_auc <- sapply(1:10, function(f) {\n  fit <- glm(type ~ ., data = Pima.tr[folds != f, ], family = binomial)\n  p   <- predict(fit, newdata = Pima.tr[folds == f, ], type = \"response\")\n  auc(p, as.numeric(Pima.tr$type[folds == f] == \"Yes\"))\n})\np_app <- predict(fit_pima, newdata = Pima.tr, type = \"response\")  # judged on its own training data\nround(c(apparent = auc(p_app, as.numeric(Pima.tr$type == \"Yes\")),\n        cv = mean(cv_auc), fold_sd = sd(cv_auc)), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\napparent       cv  fold_sd \n   0.850    0.820    0.102 \n```\n\n\n:::\n:::\n\n\nThe apparent AUC, the model judged on the very data it was fitted to, is 0.85; cross-validation says 0.82. The gap is the **optimism**, the difference between apparent and honestly measured performance, that @sec-overfitting taught you to expect, modest here because the model is small. Note the fold standard deviation of 0.10, the standard deviation of the ten fold scores around their mean (the standard error of the mean of ten independent scores would be smaller by a factor of $\\sqrt{10}$, though fold scores are not independent, since their training sets overlap): with twenty patients per fold, each fold's verdict is rough, and a report worth trusting carries that uncertainty rather than the bare mean. The independent test set said 0.87 earlier, a reminder that these estimates have sampling error of their own; all three numbers are consistent.\n\nThree refinements matter for the kinds of data in this book. **Stratified** folds preserve the outcome rate in each fold, which stabilizes the estimates when events are rare. **Clustered** folds hold out whole schools, hospitals, or persons, for the reason the leakage section gave, and **temporal** splits hold out the most recent period; choose the folds to match the generalization the model claims. And when tuning, use the **one-standard-error rule**: prefer the simplest model within one standard error of the best, since the best is partly luck [@james2021].\n\nTwo cautions concern what cross-validation is. What it evaluates is a *procedure*, not a fitted model: ten fits were scored, and none of them is the model actually used, which is fitted on all the data. And it does not by itself prevent overfitting. Cross-validation measures generalization error, the expected test error of @sec-overfitting; only the modelling choices the measurement informs, a smaller $\\lambda$, a shallower tree, reduce overfitting, and a cross-validated score can itself be overfitted by the leaderboard chasing of the previous section.\n\n::: {.callout-tip icon=\"false\" title=\"Exercise 7.5\"}\nThis exercise uses R. Take the model with twenty junk predictors of the `pima-overfit` chunk, fitted to `tr`.\n\n(a) Compute its apparent AUC on `tr`, its ten-fold cross-validated AUC on `tr` (reuse the `folds` of the `pima-cv` chunk), and its AUC on the test set `te`.\n(b) Order the three numbers and explain each gap.\n(c) The cross-validated number is *below* the test-set number, although both are honest. Why?\n:::\n\n::: {.callout-note collapse=\"true\" icon=\"false\" title=\"Answer 7.5\"}\n(a) The code reuses `auc`, `tr`, `te` and `folds` from the chapter's chunks; the 0/1 outcomes are recomputed because the `leakage` chunk reused the name `y`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ny_tr     <- as.numeric(tr$type == \"Yes\")\ny_te     <- as.numeric(te$type == \"Yes\")\nfit_junk <- glm(type ~ ., data = tr, family = binomial)\ncv_junk  <- sapply(1:10, function(f) {\n  fit <- glm(type ~ ., data = tr[folds != f, ], family = binomial)\n  p   <- predict(fit, newdata = tr[folds == f, ], type = \"response\")\n  auc(p, y_tr[folds == f])\n})\nround(c(apparent = auc(predict(fit_junk, type = \"response\"), y_tr),\n        cv = mean(cv_junk), fold_sd = sd(cv_junk),\n        test = auc(predict(fit_junk, newdata = te,\n                           type = \"response\"), y_te)), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\napparent       cv  fold_sd     test \n   0.892    0.765    0.115    0.830 \n```\n\n\n:::\n:::\n\n\nApparent 0.89, cross-validated 0.76 (fold SD 0.12), test 0.83.\n(b) Apparent is highest: 28 coefficients fitted to 200 cases fit noise as well as signal, and the noise counts as correct on the training data; the gap to the honest numbers, 0.06 to 0.13, is the optimism, much larger than the 0.03 of the model without junk. The two honest numbers are both below the apparent one, and both below the junk-free model's 0.82 and 0.87: the junk predictors cost real performance, not only apparent performance.\n(c) Each cross-validation fit uses 180 cases rather than 200, so it is a slightly worse model than the one scored on `te`, which biases the cross-validated estimate down a little; and with twenty patients per fold the cross-validated mean has a fold SD of 0.12, so a difference of 0.07 between two honest estimates is within sampling error. The two numbers disagree because they are noisy estimates of nearly the same quantity, not because either is inflated.\n:::\n\nThe **bootstrap** answers a different question: not \"how well will this model predict?\" but \"how much would this number vary if the study were run again?\", which is the standard-error question of every earlier chapter, now answerable without formulas. The idea is the plug-in principle: treat the sample as if it were the population, draw $B$ new samples of size $n$ from it *with replacement*, recompute the statistic on each, and read the spread of the recomputed values [@efron1993]. @fig-bootstrap shows one round of this concretely: because the draws are made with replacement, each bootstrap sample repeats some of the original rows and omits others, so the refitted statistic comes out a little different each time, and the standard deviation of those values is the bootstrap standard error.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![The bootstrap on a sample of eight observations. Each bootstrap sample draws eight row numbers from the original data with replacement, so some rows appear more than once (dark) and others not at all; the statistic is recomputed on each bootstrap sample, and the spread of the recomputed values is the bootstrap standard error.](07-evaluation-resampling_files/figure-html/fig-bootstrap-1.png){#fig-bootstrap width=624}\n:::\n:::\n\n\nAn example on a second dataset from `MASS`. A logistic regression of low birth weight on the mother's smoking, hypertension and weight (`birthwt`, 189 births) gives an odds ratio of 1.98 for smoking, and the large-sample interval that `glm` computes from the standard error of the log-odds coefficient runs from 1.04 to 3.79:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit_bw <- glm(low ~ smoke + ht + lwt, family = binomial,\n              data = birthwt)\nor_bw  <- exp(coef(fit_bw)[\"smoke\"])\nround(c(or_bw, exp(confint.default(fit_bw)[\"smoke\", ])), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n smoke  2.5 % 97.5 % \n  1.98   1.04   3.79 \n```\n\n\n:::\n:::\n\n\nThe same interval by resampling:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(13)\nboot_or <- replicate(2000, {\n  d <- birthwt[sample(nrow(birthwt), replace = TRUE), ]\n  exp(coef(glm(low ~ smoke + ht + lwt, family = binomial,\n               data = d))[\"smoke\"])\n})\nround(c(estimate = unname(or_bw), se = sd(boot_or),\n        quantile(boot_or, c(.025, .975))), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nestimate       se     2.5%    97.5% \n    1.98     0.75     1.03     3.96 \n```\n\n\n:::\n:::\n\n\nThe odds ratio of 1.98 gets a standard error of 0.75 and a 95 percent interval from 1.03 to 3.96, computed by nothing more than resampling rows; the large-sample interval is close. The same procedure wraps an interval around an AUC, a calibration slope, an indirect effect, or any other computable statistic, which is its great strength. Its limit is the sample it plugs in: no resampling scheme can supply information about patients unlike any in the data, or repair an identification problem. As @sec-identification argued, a valid interval around an indirect effect does not make the effect causal; the bootstrap answers the standard-error question and leaves the identification question where the design left it.^[*Optional.* The bootstrap's deterministic predecessor, the **jackknife**, recomputes the statistic $n$ times leaving out one observation each time and reads the standard error from an inflated spread of the results [@efron2016]. On the odds ratio above it gives 0.68 to the bootstrap's 0.75. The same leave-one-out idea underlies a construction inside random forests: each observation is scored using only the trees whose bootstrap sample missed it, called the out-of-bag (OOB) error, an unbiased test-error estimate that comes free with the forest [@james2021].]\n\nThe bootstrap also estimates prediction error, by putting a number on the optimism itself [@efron1993]. Fit the model to a bootstrap sample, score it on that sample and on the original data, and the difference is one draw of the optimism, the inflation from scoring a model on its own training data; average many draws and subtract the result from the apparent performance:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(15)\ny_tr <- as.numeric(Pima.tr$type == \"Yes\")\noptimism <- replicate(200, {\n  i  <- sample(nrow(Pima.tr), replace = TRUE)\n  fb <- glm(type ~ ., data = Pima.tr[i, ], family = binomial)\n  auc(predict(fb, type = \"response\"), y_tr[i]) -\n  auc(predict(fb, newdata = Pima.tr, type = \"response\"), y_tr)\n})\nround(c(apparent = 0.850, optimism = mean(optimism),\n        corrected = 0.850 - mean(optimism)), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n apparent  optimism corrected \n    0.850     0.024     0.826 \n```\n\n\n:::\n:::\n\n\nThe optimism-corrected AUC, 0.826, is close to cross-validation's 0.82; the two methods agree. This correction is the standard **internal validation** of the clinical prediction literature [@collins2024part1]. The name is close to the *internal validity* of @sec-rq-to-interpretation but means something else: internal validation estimates how well a model performs in the population its data came from, external validation in the next section asks whether that performance transfers, which is the concern of external validity, and neither has anything to do with the causal question that internal validity asks.\n\n::: {.callout-tip icon=\"false\" title=\"Exercise 7.6\"}\nPick the resampling design, and justify it in a sentence.\n\n(a) Tuning $\\lambda$ for the lasso of @sec-overfitting on 100 observations.\n(b) Estimating how well a school-dropout model generalizes to schools not in the data, with 12,000 pupils in 40 schools.\n(c) Attaching a confidence interval to the indirect effect $ab$ in a mediation model.\n(d) Evaluating a model meant to forecast next year's hospital admissions from five years of records.\n(e) A colleague reports the *best* of the ten fold AUCs as the model's performance. What is wrong, and what would you report instead?\n:::\n\n::: {.callout-note collapse=\"true\" icon=\"false\" title=\"Answer 7.6\"}\n(a) Ten-fold cross-validation with the one-standard-error rule; the sample is too small to set aside a holdout.\n(b) Leave-whole-schools-out folds, since pupil-wise folds leak school identity and answer a different, easier question.\n(c) The bootstrap, resampling units and refitting both equations each time; and per @sec-identification, the interval is only as meaningful as the identification.\n(d) A temporal split: train on the first years, evaluate on the last, matching the deployment direction of time; shuffled folds would let the future inform the past.\n(e) A maximum over ten noisy fold scores is selection optimism: the best fold is partly the fold whose twenty patients happened to be easy, and in the `pima-cv` chunk the best fold scored 0.96 against a mean of 0.82. Report the mean with the fold standard deviation, or the AUC pooled over all held-out predictions.\n:::\n\n## External validation and deployment\n\nEverything so far measures a model against data; deployment measures it against the world. Prediction models multiply in the clinical literature, over 400 published for chronic obstructive pulmonary disease alone and more than 600 for COVID-19, yet next to none are used in care [@collins2024part1]. The reasons are not mainly algorithmic. Often the risk score feeds no decision: every patient gets the same action whatever the number says, so a better prediction changes nothing, and nobody redesigned the clinic's workflow so that a number could change anything. Often, too, the problem was built in at the design stage. A qualitative analysis of recently published clinical decision-support tools found a recurring pattern: the target variable was chosen because an available dataset happened to record it, rather than because it measured the clinical goal, so that construct invalidity of the kind @obermeyer2019 exemplifies was designed in from the start; when the resulting tool could not support the original clinical goal, alternative goals were formulated to justify its continued development; and the resulting limitations were rarely communicated clearly enough to be addressed [@kernahan2025]. A model justifies deployment the way any intervention does, by improving what happens next, and several terms describe the ways that fails.\n\n**External validation** means evaluating a model, exactly as frozen, on data from another setting, a later period, a different country, other hospitals, with no refitting [@riley2024part2]. It is the test-set idea carried across the boundary that matters for use, and it routinely shows worse performance, discrimination somewhat lower and calibration visibly off, because case mix, measurement, and base rates shift between settings. Performance is a property of a model in a population, not of the model alone. There are three practical consequences. Expect heterogeneity: a model's c-statistic can easily range 0.1 across hospitals, so with multi-site data the informative design is **internal-external cross-validation**, leaving out each site in turn, which makes transfer between sites a measured quantity [@collins2024part1; @vancalster2026]. Expect drift: populations and practices change under a deployed model, as the Google Flu Trends episode of @sec-explanation-prediction showed at scale, so evaluation must be repeated over time rather than done once. And expect recalibration: a transported model is usually worth re-tuning at its intercept before use, which costs little and repairs the most consequential failures.\n\nValidation studies have their own sample-size arithmetic. The old rule of thumb asked for 100 events; targeting a precise calibration slope for a realistic COVID deterioration model required 949 patients with 408 events, four times the rule of thumb, and calibration is typically the binding constraint [@riley2024part3]. Small validation studies produce calibration curves that fluctuate widely, and a model can be declared broken, or sound, on the basis of noise.\n\nTwo honesty problems remain even after all of this. The first is that most published evaluation falls short of the standards in this chapter: the reviews that motivated the current reporting guidelines found the median study deficient on the points of this chapter, unassessed calibration first among them [@christodoulou2019; @vancalster2026].^[The reporting guideline for prediction models is TRIPOD+AI, which lists what a study must report [@collins2024tripod]; its companion PROBAST+AI grades the risk of bias in what is reported [@moons2025]; and the STRATOS initiative's guidance on performance measures [@vancalster2025] is the source of this chapter's advice on proper measures. Exercise 7.A refers to the first of these.] The second is that a validated risk score is still only a score. Whether *acting* on it helps anyone is a causal question about an intervention, the rain-dance half of the Kleinberg decomposition from @sec-explanation-prediction, and it is settled by the designs of @sec-rq-to-interpretation, ultimately a trial of the model-guided policy against care as usual, not by any accuracy metric whatever [@vancalster2026]. The five questions of @sec-rq-to-interpretation translate intact: what is the task; what were the experience and the metric; how were the judging data produced; what must hold for the score to transfer; and what in the evaluation design makes that plausible. Prediction is subject to the same chain of questions; it enters it at a different link.\n\n## Held-out evaluation in the social sciences\n\nThe techniques of this chapter were presented as machine learning's, but the problem they solve is one the social and health sciences have met under other names. P-hacking, the garden of forking paths, fishing: all describe an analyst whose choices were shaped by the data that then judge the result, which is the definition of leakage given above. The remedies developed in the two traditions are therefore two answers to one question. Preregistration fixes the analytic choices before the data can influence them [@nosek2018]; a holdout sample lets the data influence the choices freely and then evaluates the result on data those choices could not touch. Yarkoni and Westfall made the general case that psychology's replication problems are, in this vocabulary, overfitting, and that the machinery of this chapter, held-out evaluation and cross-validation, addresses them directly [@yarkoni2017].\n\nThe transfer is practical, not just conceptual. Consider the structural equation models of @sec-theory-to-glm and @sec-identification. When a model fits poorly, software will report which restrictions to free. **Modification indices** are these reports: for every parameter the model fixes at zero, an arrow not drawn or a covariance assumed absent, the software estimates how much the chi-square would fall if that parameter were freed, and prints the list sorted from largest to smallest (`modindices(fit)` in `lavaan`). Respecifying the model on the advice of that list, then reporting the improved fit on the same sample, capitalizes on chance just as the leakage demonstration above did: the list was computed from the same data that will judge the modified model, and with different data, different modifications would have been suggested [@maccallum1992]. A holdout cures this: modify the model as freely as exploration demands on one half of the sample, then fit the final specification once on the untouched half and report that test. The same design serves any analysis in which exploration and confirmation compete for the same data: explore, generate hypotheses, and adjust on the training portion, then run a single preregistered-in-spirit test on the holdout. Split-sample designs of this kind have been formalized for causal inference as well [@fafchamps2017].\n\nThis tool remains underused in the social sciences, largely from a habit formed when samples were small and every observation was needed for estimation. That constraint has loosened: administrative registers, panel infrastructures like the LISS data of @sec-theory-to-glm, and routine digital measurement have made datasets of thousands to millions of rows ordinary, and at those sizes a holdout costs little precision. Where the sample really is small, the resampling methods of this chapter are the substitute, with their cautions attached.\n\n## What to carry forward {.unnumbered}\n\nFive results from this chapter are used in the chapter that follows and in reading the prediction literature. A performance metric is a choice that fixes what counts as success, and a predicted probability can be good in two separate ways, discrimination, measured by the AUC, and calibration, measured by the calibration intercept and slope, of which overfitting damages calibration first (\"Performance metrics for continuous and binary outcomes\"); @sec-unsupervised has no outcome to compute any of these against, which is its central difficulty. Under the assumption that the data come from the same process as the future cases, the training set fits, the validation set chooses and the test set is used once (\"Splitting the data: training, validation and test sets\"); @sec-unsupervised has to choose the number of clusters without any of the three. Any choice the data could have changed belongs inside the evaluation loop, and leakage, held-out data that shaped the model, makes an evaluation falsely optimistic without making the model worse (\"Leakage\"); this is the fishing of @sec-rq-to-interpretation in machine learning's vocabulary. Cross-validation estimates the generalization error of a procedure and the bootstrap estimates the sampling variation of a statistic, the optimism of an apparent score can be measured directly, and neither method can supply information the sample does not contain (\"Resampling: cross-validation, bootstrap, jackknife\"); @sec-unsupervised uses resampling to judge the stability of a clustering. A validated score transfers only to the extent that the validation data resemble the deployment setting, and whether acting on the score helps anyone is a causal question about an intervention that no accuracy metric answers (\"External validation and deployment\"); the same holdout logic applies to exploratory model modification in structural equation models (\"Held-out evaluation in the social sciences\").\n\n**Terms and symbols introduced.** root mean squared error, mean absolute error, out-of-sample $R^2$; loss function, asymmetric (quantile) loss; threshold; true and false positives and negatives; sensitivity (recall), specificity, precision, accuracy, F1; proper measure; ROC curve, AUC, concordance statistic, discrimination; calibration, calibration intercept and slope, calibration-in-the-large; Brier score; net benefit, decision curve analysis; training, validation and test set; leakage; nested cross-validation; K-fold cross-validation, stratified, clustered and temporal folds, one-standard-error rule; optimism; bootstrap, jackknife; internal validation, external validation, internal-external cross-validation; modification indices; $y_i$, $\\hat y_i$ and $m$ the observed outcome, its prediction and the number of test cases; $L(e)$ the loss attached to an error $e$ (distinct from $\\ell$, the log-likelihood); $\\hat p_i$ a predicted probability; $w_k$, $\\bar p_k$ and $\\bar y_k$ a bin's share, mean prediction and event rate; $p_t$ the treatment threshold; $K$ the number of folds; $B$ the number of bootstrap samples.\n\n**Exercises that use R.** 7.5 (apparent, cross-validated and test AUC of the junk model); 7.B(e) (recalibrating the junk model).\n\n## Further study {.unnumbered}\n\nChapter 5 of @james2021 is the textbook treatment of cross-validation and the bootstrap that this chapter follows, and chapter 7 of @hastie2009 is the graduate-level version, including the demonstration of leakage by screening that the leakage section reproduced. @steyerberg2019 is the standard book on clinical prediction models, with calibration, internal and external validation and recalibration worked out in full, and the BMJ series [@collins2024part1; @riley2024part2; @riley2024part3] is its short, current form. @vancalster2025 is the STRATOS guidance on which performance measures to use for medical decisions, with the argument against improper measures such as F1 and accuracy, and @vickers2006 is the paper that introduced decision curve analysis. @efron1993 is the original book on the bootstrap, with the optimism correction and the jackknife. @kapoor2023 surveys leakage across the sciences and proposes a checklist for reporting it, and @yarkoni2017 is the case that psychology's replication problems are overfitting and that held-out evaluation addresses them.\n\n## Test yourself {.unnumbered}\n\n::: {.callout-tip icon=\"false\" title=\"Exercise 7.A\"}\nYou must design the evaluation for a model predicting which pupils will leave school without a qualification, built on five cohorts of administrative records from 40 secondary schools, to be deployed next year across the region, including three schools that opened too recently to contribute training data. Pupils above a risk threshold will be offered a mentoring programme.\n\n(a) Specify the split or resampling structure, respecting both time and clustering, and say which question each layer answers.\n(b) List three leakage risks specific to this problem and the countermeasure for each.\n(c) Name the metrics you would report and the one you would treat as primary, given the mentoring decision.\n(d) The model performs well everywhere except in schools with many pupils who speak the national language at home as a second language, where calibration is poor. Give one reporting response and one modelling response.\n(e) A board member asks whether deploying the model will reduce dropout. Answer in two sentences, using the vocabulary of this book.\n:::\n\n::: {.callout-note collapse=\"true\" icon=\"false\" title=\"Answer 7.A\"}\n(a) Outer evaluation: hold out the most recent cohort entirely, all schools, as the test period, matching deployment in time; within the earlier cohorts, internal-external cross-validation leaving out whole schools estimates transfer to unseen schools, which is the question the three new schools pose. Inner loop: tuning by cross-validation nested within each training portion.\n(b) The same pupil appearing in several cohorts on both sides of a split: split by pupil as well as cohort. Features recorded after the dropout decision effectively is made (late-year absence records): restrict features to what exists at the moment the prediction would be issued. Imputation and standardization fitted on pooled data: fit them inside each training portion only.\n(c) AUC for discrimination, calibration slope and intercept with a plot, and, as primary, net benefit at the mentoring threshold, since the decision and its costs are known; report by school, not only pooled.\n(d) Reporting: publish the per-group and per-school results, including the failures, with intervals, rather than the more favourable pooled number, which is the subgroup reporting TRIPOD+AI asks for [@collins2024tripod]. Modelling: recalibrate for the affected schools (at minimum the intercept), or add the relevant school-level information; and flag that small subgroups make even their observed miscalibration uncertain, per the validation sample-size arithmetic [@riley2024part3].\n(e) The evaluation shows only that the model predicts dropout, an umbrella claim; whether offering mentoring to the flagged pupils reduces dropout is a rain-dance claim about an intervention, and it is settled by the designs of @sec-rq-to-interpretation, ideally a randomized comparison of the model-guided policy against practice as usual.\n:::\n\n::: {.callout-tip icon=\"false\" title=\"Exercise 7.B\"}\nA cardiovascular risk model reports AUC 0.88; on external validation its calibration intercept is $-0.80$ and its slope is 0.65. Clinicians prescribe statins above 10 percent predicted ten-year risk.\n\n(a) Describe in words what each of the three numbers says about the model.\n(b) A patient is given a predicted risk of 25 percent. Roughly what should the physician believe, and in which direction is the treatment decision biased at the 10 percent threshold, for high-risk and for low-risk patients?\n(c) Propose the minimal repair that uses no new predictors, and say what data it requires.\n(d) After your repair, the AUC is unchanged at 0.88. Explain why, and what that implies about which patients the repair did and did not help.\n(e) This part uses R. Simulate the repair on the junk model of the `pima-overfit` chunk: regress `y` on `qlogis(p2)`, then use the fitted values as recalibrated predictions. Report the intercept and slope, and the AUC and Brier score (the mean squared error of the probabilities) before and after. Then say why recalibrating on the same test set that scores the result is itself a small leak.\n:::\n\n::: {.callout-note collapse=\"true\" icon=\"false\" title=\"Answer 7.B\"}\n(a) The AUC says ranking is strong: cases sit above non-cases 88 percent of the time. The intercept of $-0.80$ says predictions are too high overall in this population (observed risks run lower than predicted at every level). The slope of 0.65 says predictions are also too spread out: high predictions too high, low predictions too low, the overfitting signature.\n(b) The 25 percent should be read as substantially less: applying the intercept and slope jointly on the log-odds scale, $\\operatorname{logit}^{-1}(-0.80 + 0.65 \\times \\operatorname{logit}(0.25))$, gives about 0.18, and reading the intercept as pure calibration-in-the-large gives about 0.13, so the teens, depending on how the two are estimated. At the 10 percent threshold, the model over-treats: patients whose true risk sits below 10 percent are pushed over the line by inflated predictions, so statins go to people who would not qualify on their true risk; genuinely high-risk patients are treated correctly, though for exaggerated reasons.\n(c) Recalibration: refit intercept and slope on local data by regressing the outcome on the model's linear predictor, then transform all predictions; the ranking is preserved and the probabilities are repaired. It requires a local validation sample with outcomes, sized per @riley2024part3, with calibration the binding constraint.\n(d) Recalibration is a monotone transformation of the predictions, and the AUC depends only on the ordering, which is untouched. So the repair helps every decision that depends on the probability's value, which is all threshold decisions, and does nothing for any patient mis-*ranked* by the model; improving the ranking requires new information rather than recalibration.\n(e) The code reuses `p2`, `te` and `auc` from the chapter's chunks.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ny_te   <- as.numeric(te$type == \"Yes\")\nrecal  <- glm(y_te ~ qlogis(p2), family = binomial)\np2_re  <- fitted(recal)                 # recalibrated predictions\nbrier  <- function(p, y) mean((p - y)^2)\nround(coef(recal), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(Intercept)  qlogis(p2) \n      -0.24        0.63 \n```\n\n\n:::\n\n```{.r .cell-code}\nround(c(auc_before = auc(p2, y_te), auc_after = auc(p2_re, y_te),\n        brier_before = brier(p2, y_te),\n        brier_after = brier(p2_re, y_te)), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  auc_before    auc_after brier_before  brier_after \n       0.830        0.830        0.161        0.157 \n```\n\n\n:::\n:::\n\n\nIntercept $-0.24$ and slope $0.63$, the slope of the `pima-overfit` chunk. The AUC is 0.830 before and after, and the Brier score falls from 0.161 to 0.157: the ranking is untouched and the probabilities improve, which is (d) in numbers. The leak: the two recalibration coefficients were estimated on `te`, the same 332 patients whose Brier score then reports the improvement, so the after-score is slightly optimistic, in the way that any apparent score is; an honest version estimates the recalibration on one sample and scores it on another, which is what (c) asked for with its local validation sample.\n:::\n\n::: {.callout-tip icon=\"false\" title=\"Exercise 7.C\"}\nReturn to the care-management algorithm of @obermeyer2019, which predicted costs as a proxy for health needs.\n\n(a) Locate the failure in Mitchell's triple: was it in T, P, or E? Explain.\n(b) The developers surely evaluated their model. Name a metric and evaluation design under which the model looked good, and the metric-and-data combination that would have exposed the problem before deployment.\n(c) The fix the authors negotiated with the manufacturer changed the label toward measures of health rather than cost. Which parts of the evaluation machinery of this chapter must be rerun after such a change, and which conclusions from the old evaluation survive?\n(d) State the general lesson in one sentence connecting @sec-rq-to-interpretation's construct validity to this chapter.\n:::\n\n::: {.callout-note collapse=\"true\" icon=\"false\" title=\"Answer 7.C\"}\n(a) In T, the task. The intended task was \"predict who needs extra care\"; the specified task was \"predict costs\". E and P were then adequate for the wrong T: the experience matched the label, and performance on that label was high.\n(b) It looked good on cost-prediction accuracy (say $R^2$ or calibration against realized costs) under a random holdout. The exposing design: evaluate against independent measures of health need (active chronic conditions, biomarkers) *by group*, comparing observed need at fixed risk score across Black and White patients, which is the authors' analysis, a fairness audit in this chapter's vocabulary of subgroup evaluation.\n(c) Everything downstream of the label: retraining, re-tuning, and full re-evaluation of discrimination, calibration, and net benefit against the new label, plus the subgroup audit, since a new target redefines every metric. What survives is the infrastructure (pipelines, features, and the evaluation design itself), not the verdicts; a changed label makes a new model.\n(d) A performance measure certifies a model only relative to its operationalized target, so construct validity, whether the label measures the thing you meant, is as decisive for prediction as it was for explanation. The connection is more than an analogy: this very case can be treated with a latent-variable measurement model, regarding cost as one error-prone indicator of the latent construct \"health need\" and combining several such indicators, which removes the unfairness that any single proxy leaves in place [@boeschoten2021]. Such models are not covered in this book; @sec-unsupervised asks the related question of where the indicators that define a class came from, and Beaujean's book in the preface's further reading is the entry point.\n:::\n\n::: {.callout-tip icon=\"false\" title=\"Exercise 7.D (optional)\"}\nThis exercise is optional and more challenging than the others: it works the Brier decomposition out by hand on the ten patients of Exercise 7.3, and nothing later in the book depends on it.\n\n(a) Compute the Brier score of the ten predictions.\n(b) Compute the three terms of the decomposition with the two bins of Exercise 7.3(b), and compare their sum with (a). Explain the discrepancy.\n(c) Replace every prediction $p$ by $p^2$. Recompute $c$ and the Brier score. What does the pair of results say about which metric a monotone recalibration can and cannot change?\n:::\n\n::: {.callout-note collapse=\"true\" icon=\"false\" title=\"Answer 7.D\"}\n(a) The squared errors are $0.0025, 0.01, 0.0225, 0.64, 0.1225, 0.36, 0.36, 0.09, 0.04, 0.01$, which sum to $1.6575$, so the Brier score is $0.166$.\n(b) With $w_1 = w_2 = 0.5$, $\\bar p_1 = 0.17$, $\\bar y_1 = 0.2$, $\\bar p_2 = 0.68$, $\\bar y_2 = 0.8$ and $\\bar y = 0.5$: miscalibration $0.5(0.03^2) + 0.5(0.12^2) = 0.0077$; discrimination $0.5(0.3^2) + 0.5(0.3^2) = 0.090$; irreducible $0.5 \\times 0.5 = 0.25$. The sum $0.0077 - 0.090 + 0.25 = 0.168$ differs from (a) by $0.002$. The decomposition is exact only when every prediction in a bin equals the bin mean; here the predictions vary within each bin, and the leftover term, which involves the within-bin variance of the predictions and their within-bin covariance with the outcomes, is $-0.002$.\n(c) Squaring is monotone, so every concordant pair stays concordant and $c$ stays $0.88$. The Brier score rises to $0.220$, because the squared predictions are too low everywhere (the mean prediction falls from $0.425$ to $0.27$ against an event rate of $0.5$). $c$ depends on the order of the predictions alone and the Brier score on their values, so a monotone recalibration moves the Brier score and never $c$, which is why the AUC in Exercise 7.B(d) did not change.\n:::\n",
    "supporting": [
      "07-evaluation-resampling_files/figure-html"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}