{
  "hash": "b510d27e2f0bbe0ec0168dc967438d02",
  "result": {
    "engine": "knitr",
    "markdown": "# From research question to interpretation {#sec-rq-to-interpretation}\n\nOn 9 October 1967 the British police acquired a new instrument. The Road Safety Act set a legal limit of 80 milligrams of alcohol per 100 millilitres of blood and let an officer who had stopped a driver for an offence or an accident hand him a glass tube packed with crystals and ask him to blow. Over the following three months road deaths fell by 23 percent and casualties by 16 percent [@ross1970].\n\nThe numbers fell, but whether a question was thereby answered is a different matter, and it is the subject of this book. Deaths could also fall when the weather is mild, when petrol is expensive, and when a publicity campaign frightens people into caution, and all three of those things were happening in Britain in the autumn of 1967. To claim that the new law saved those lives is to claim that nothing else would have. Nobody observed the Britain in which the Act was never passed.\n\nSo the researchers looked for a pattern that only the law could have produced. British pubs closed at half past ten. If the crackdown was doing the work, the drop should concentrate in the hours when people drive home from pubs and should be absent during the commuting hours, morning and late afternoon, when the pubs have been shut.^[Ross and colleagues added a note in press that the series would have been better labelled \"closed hours\", since it also covers the closed hours of Saturday and Sunday, and that the weekend-night series omits late Saturday night, which makes the contrast they report an understatement [@ross1970].] That is what the data showed (@fig-breathalyser): casualties on weekend nights fell by about a third and stayed down, while the commuting hours show no break at all [@ross1970]. Weather and petrol prices do not vary with the hours the pubs are open. In the vocabulary of this chapter, the study is an *interrupted time series* with a *control series*: one monthly series that the law should have broken, and a second series, counted by the same police forces in the same months, that it should have left alone.\n\n![British road casualties either side of the 1967 Breathalyser law. The two series are counted by the same police forces in the same months and differ only in the hours they cover. Monthly values digitized from the figure in @ross1970, which draws both series on one scale; the weekend-night series stops at November 1968 in the original.](images/ross-1970-breathalyser.png){#fig-breathalyser width=\"100%\" fig-align=\"center\"}\n\n## The chain from research question to interpretation {#sec-chain}\n\nEvery empirical study follows the same sequence. A researcher starts with a question. To answer it, they collect new data or organize existing data in a particular way; this is the **design**. A good design makes certain assumptions plausible, for example that the groups being compared were alike before the treatment. Written down explicitly, those assumptions are the **model**. Fitting the model to the data produces estimates, and those estimates answer the original question *to the extent that the assumptions hold*. @fig-chain shows the sequence.\n\n![The chain that every empirical study follows. The design's job is to make the assumptions plausible; the model's job is to turn data into an answer under those assumptions.](diagrams/chain.png){#fig-chain width=\"70%\" fig-align=\"center\"}\n\nA model is a set of assumptions specific enough to be written in mathematics: a straight line with normal errors, a logistic curve, a set of groups whose means are drawn from a common distribution, a tree that splits on one variable at a time, a neural network with a hundred billion weights, a Gaussian process, a hidden Markov chain, a factor model that treats an unobserved trait as the cause of what you can observe. These differ enormously in flexibility and cost. But they do not differ in their position in the chain. Each one turns data into numbers that answer questions under assumptions; and each one is only as good as the design that makes its assumptions plausible.\n\nPutting the design before the statistics in this way is not a new idea. It is the tradition that runs from Campbell and Stanley, who first catalogued the ways a study can fail and drew the designs that block them, through Cook and Campbell, to the modern statement of the framework by Shadish, Cook and Campbell that this chapter follows [@campbell1963; @cook1979; @shadish2002].\n\nEvery design is an argument, and arguments can be strong or weak. What a randomized experiment does is make \"the two groups had nothing systematically different about them\" plausible, because a coin flip is unrelated to who is sick, rich, or motivated. This, in turn, rules out the threat that systematic group differences were causing an observed treatment effect. A random sample makes \"these people stand in for a population\" plausible. In the Breathalyser example, comparing the pre-post change in casualties on weekend nights with the same change during commuting hours removes the influence of any factor that moves the two series equally: a general improvement in road safety, say, or a change in how administrative records define a casualty.\n\nTwo researchers who disagree about a finding are usually disagreeing about one link. Does the question mean what you think it means? Did the design produce data that could speak to it? Are the assumptions both the ones the design makes plausible and the ones the model requires?\n\n## What is the question? {#sec-question-types}\n\nResearch questions can be classified in many ways. Broadly, we might distinguish descriptive, causal (\"explanatory\"), and predictive questions [@hernan2019; @leek2015].^[Hernán, Hsu and Healy call causal inference *counterfactual prediction*, which makes causal questions a species of prediction rather than a kind of their own. Nothing below turns on that choice.]\n\nA **descriptive** question asks what is the case. How many adults in the Netherlands have never used a general practitioner's out-of-hours service? Is loneliness more common among the retired than among students? Descriptive questions look simple but can be hard to answer. Generalization to the target population is often a challenge, since true random samples and whole populations are difficult to obtain. Measurement of the intended variable is usually a challenge too, especially in the social and health sciences, which must often rely on self-reports or on administrative register data that are error-prone, or at least idiosyncratic. Survey methodologists gather these problems under the heading of **total survey error**, which separates errors of nonobservation, such as coverage and nonresponse, from errors of observation, such as measurement [@groves2010]. Register data are not exempt: because they are official they are often treated as exact, but their error rates can be estimated, and when they are estimated they are not zero [@oberski2017].\n\nA **causal** question asks what would happen if something were changed. Would raising the school leaving age reduce teenage births? Does this drug lower blood pressure more than that one? An effect is a comparison between what happened and what would have happened otherwise. Note that the question and its estimate are subtly different: the causal question is typically about the future, whereas causal effect estimation deals with a historical (quasi)experiment. Shadish, Cook and Campbell define an effect in these terms: \"the difference between what did happen and what would have happened\" [@shadish2002]. The second half of that comparison, the counterfactual, is never observed for anybody. Design entails constructing a substitute for it, an argument econometricians call the **identification strategy** [@angrist2009]; @sec-identification gives the word *identification* a precise meaning.\n\nNot every causal question is stated as one. Authors of nonexperimental work often report that X \"predicts\" or \"is associated with\" Y, and then, in the discussion, recommend an intervention, which makes sense only if the association is causal. Grosz, Rohrer and Thoemmes call this the taboo against explicit causal inference: the causal claim is still made, but implicitly, so the assumptions it needs are never stated and never defended [@grosz2020]. Hernán makes the same complaint about epidemiology, where the euphemism changes the wording and not the purpose of the study [@hernan2018]. Antonakis and colleagues put numbers on the consequences: reviewing 110 papers in leadership research, they found that between 66 and 90 percent of the conditions required for a causal reading went unaddressed [@antonakis2010]. So you should be aware that sometimes causal claims are made implicitly.\n\nA **predictive** question asks what *will* happen, for a unit whose outcome you have not seen. Which patients booked into tomorrow's clinic will fail to show up? How many children will be born next year? How high will inflation be? Predictive questions are easier to verify than causal ones, since they concern observable outcomes we can wait for and check rather than unobservable counterfactuals. For that reason some fields have focused almost exclusively on prediction. Within the social and health sciences the reverse held: purely predictive questions, asked without regard for causality, were traditionally treated as the less serious kind. More recently the two have come closer together.\n\n&nbsp;\n\nThis text focuses on causal questions (\"explanation\", chapters 1–4) and on prediction (chapters 5–8). The rest of this chapter sets out a systematic approach to explanatory research, drawn from two classic textbooks [@saris1984; @shadish2002].\n\n\n::: {.callout-tip icon=\"false\" title=\"Exercise 1.1\"}\nClassify each question as descriptive, causal, or predictive, and say in one sentence what a design would have to deliver for it to be answerable.\n\n(a) What fraction of primary school teachers in Belgium report burnout symptoms?\n(b) Does switching a school to a later start time improve pupils' grades?\n(c) Which of the patients discharged today will be readmitted within 30 days?\n(d) Are neighbourhoods with more green space healthier?\n:::\n\n::: {.callout-note collapse=\"true\" icon=\"false\" title=\"Answer 1.1\"}\n(a) Descriptive. It needs a sample that stands in for Belgian primary school teachers, and a measure of burnout that means the same thing to everyone who answers.\n(b) Causal. It needs schools that switch and comparable schools that do not, with the switching decided in a way unrelated to how the grades were going to move anyway.\n(c) Predictive. It needs data available at discharge and a way of checking the predictions against readmissions the model has never seen.\n(d) As written, descriptive: it asks about a pattern. Almost everyone who asks it means the causal version, \"would adding green space make people healthier\", and that version needs a design that separates the greenery from the wealth of the people who live near it. The slide from one to the other inside a single sentence is the taboo against explicit causal inference at work [@grosz2020].\n:::\n\n## Plausibility of assumptions behind an answer: threats to validity {#sec-validity}\n\nWe have seen that results only answer a question *given the assumptions*. For example, if we are comparing road deaths before and after an intervention, we need to assume nothing else was simultaneously influencing road deaths. **The plausibility of all such assumptions taken together is what we will call \"validity\"**. Shadish, Cook and Campbell put it in terms of the conclusion rather than of the assumptions, defining validity as the approximate truth of an inference, but the point that follows is theirs either way: validity is a property of a claim, not of a design or a model [@shadish2002]. A randomized trial can support an invalid inference, and an observational study can support a valid one.\n\n@shadish2002 sort validity into four kinds.\n\n**Internal validity** asks whether the covariation between the presumed cause and the presumed effect reflects a causal relationship, for these units and for these variables as they were actually manipulated or measured. The convenient concept of a \"threat to validity\", a potential violation of an assumption, goes back to Campbell and Stanley's original catalogue [@campbell1963]. The threats to internal validity are worth memorizing:\n\n| Threat | Alternative explanation |\n|---|---|\n| Ambiguous temporal precedence | We cannot tell which variable moved first |\n| Selection | The groups already differed before treatment |\n| History | Something else happened at the same time |\n| Maturation | People change on their own as time passes |\n| Regression to the mean | Units chosen for extreme scores drift back toward average |\n| Attrition | The people who dropped out differ between groups |\n| Testing | Being measured changes the thing measured |\n| Instrumentation | The measuring instrument itself changed |\n\nThese add up and interact. Groups that differ at the start (selection) may also improve at different rates (maturation), and the combination produces a widening gap that looks like an effect.\n\n**External validity** encompasses assumptions that a relationship will hold for other people, settings, treatments, and outcomes. We would like, ideally, to know what will happen if a particular policy is enacted in a target population, and that population will differ from the (quasi)experimental one. Medicines are given to children on the strength of trials run in adults. Patients who meet a trial's inclusion criteria are healthier than the patients who later receive the drug, so the effect measured under trial conditions and the effect obtained in routine practice differ; in medicine the discrepancy is called the efficacy–effectiveness gap, and there is a literature on what causes it [@nordon2016]. Or, outside medicine, a psychotherapy technique may work when performed by the therapist who devised it and not when performed by anyone else.\n\n**Construct validity** is the plausibility that the measurements employed reflect the intended target variables from the original theory. When a student studies to the test, this plausibility is reduced, since their score no longer reflects ability alone; any other kind of metric-chasing threatens construct validity in the same way, as formulated in Campbell's law:\n\n> The more any quantitative social indicator is used for social decision-making, the more subject it will be to corruption pressures and the more apt it will be to distort and corrupt the social processes it is intended to monitor [@campbell1979, p. 85].\n\nConstruct validity applies to both outcomes and treatment variables. For example, a hospital gives patients a nurse-led course before surgery and recovery improves. Was the active ingredient the information, the attention, the reassurance, or the fact that someone was watching?\n\n**Statistical conclusion validity** covers assumptions about statistical inference. The classical models of statistical testing developed by Neyman and Fisher assume that researchers predefine their analysis strategy and perform it once on newly collected data. That assumption is violated when the researcher picks a strategy after observing the data, or performs multiple tests without accounting for these choices: **fishing**, **p-hacking**, and, when the hypothesis is written up afterwards as though it had come first, **HARKing**. Other assumptions in this basket include large-sample approximations, distributional assumptions for small samples, priors in Bayesian inference, and so on.\n\nIn the chapters on explanatory research (chapters 1–4) we focus on internal validity. Prediction brings external validity with it, under the name out-of-domain generalization. Construct validity returns in @sec-evaluation, where a prediction model's target variable (cost) turns out to be a proxy for the thing that mattered (need for care), and in @sec-unsupervised, where the question is where the indicators that define a cluster came from. Statistical conclusion validity is not the focus of this text, though it returns in chapters 5–8, in the descriptive goal of quantifying how well a prediction model can be expected to perform on new data.\n\n::: {.callout-tip icon=\"false\" title=\"Exercise 1.2\"}\nSay which validity, if any, is threatened, and name the threat where the chapter has given it a name.\n\n(a) A reading programme is given to the worst-scoring 10 percent of pupils. They improve markedly by the end of the year.\n(b) A city introduces a knife-crime initiative and reports a jump in recorded knife offences. Police had been retrained that spring to record more incidents as knife-related.\n(c) A twelve-week weight-loss trial reports a large average loss among those who completed it. Two-fifths of the treatment group left before the end.\n(d) A workplace mindfulness course is evaluated by comparing volunteers who signed up with colleagues who did not.\n(e) A study finds that its therapy improves scores on a questionnaire the therapists themselves designed.\n(f) A smartphone app for depression is trialled on users recruited through advertisements inside the app, and works well. A health service proposes to offer it to everyone on its waiting list.\n(g) A team measures six symptom scales at three time points, tests each against treatment, and reports the one result that reached significance as the study's primary outcome.\n(h) This last item is a trap: it is not clear that any threat from the chapter applies, and the point of the item is to say why. A circus owner wants to know the total weight $T$ of his 50 elephants, so that he can ship them, but will pay for only one weighing. There is one perfectly average elephant (Norm) and one humongous one (Jumbo). The owner proposes to weigh Norm, but his highly trained statistician prevents this \"lethal design mistake\" and draws one elephant at random instead. Jumbo happens to be drawn, with weight $y_{\\text{Jumbo}}$, so the estimate of the total is $\\hat{T} = 50\\, y_{\\text{Jumbo}}$.\n:::\n\n::: {.callout-note collapse=\"true\" icon=\"false\" title=\"Answer 1.2\"}\n(a) Regression to the mean; internal validity. Pupils selected for extreme low scores score less extremely next time whatever you do to them. With a single group and no control, maturation, history and testing stand uncontrolled here as well; regression is the leading candidate only because selection was on extreme scores.\n(b) Instrumentation; internal validity. The recording rule changed at the same time as the initiative, so the series measures something different before and after.\n(c) Attrition; internal validity. Those who stayed are probably those for whom it was working, so the average among completers is not the average effect.\n(d) Selection; internal validity. Volunteers differ from non-volunteers in ways likely to affect wellbeing on their own.\n(e) Construct validity. The outcome is measured one way only, by people with a stake in the answer, and the instrument may encode the therapy's own vocabulary. The inference in trouble concerns what the outcome measure stands for.\n(f) External validity. People who answered an advertisement inside the app are more motivated and more able to use it than people waiting for care, so the effect measured is not the effect the service would obtain. Nothing here says the trial's own estimate is wrong.\n(g) Fishing; statistical conclusion validity. Eighteen tests at the 5 percent level give a $1 - 0.95^{18} = 0.60$ chance of at least one false positive when the treatment does nothing and the tests are independent. Six scales on the same people at three occasions are heavily correlated, which makes the real number smaller, though still substantial. Declaring the winner the primary outcome afterwards is HARKing, and the claim is credible only with a protocol dated before the analysis.\n(h) The story is adapted from @basu1971, and on the usual account nothing is wrong. The sample is drawn at random, the estimator is unbiased, and the arithmetic is correct. An estimator is *unbiased* if, averaged over all the samples that could have been drawn, it hits the truth; its *variance* is how much it swings from one sample to the next. Yet the answer is absurd, because an unbiased estimator with enormous variance tells you nothing from a sample of one, and the owner's disallowed plan of weighing the average elephant would have done far better. The one thing to take from the item is that \"unbiased\" is not a certificate of statistical conclusion validity, which is the validity at stake if a threat has to be named. Basu's own point was larger: he used the story to argue against the whole frequentist abstraction of repeated sampling, in which an estimator is judged by its behaviour over samples that were never drawn rather than by what the sample in hand actually says.\n:::\n\n## Designs remove threats to validity {#sec-designs}\n\nMethodology should be mostly about how to get things right, and we have seen that this means removing threats to validity. That is what research designs are for. Each design below makes particular alternative explanations implausible, and so improves validity. A design and a model are two views of one list of assumptions: the design argues that the assumptions are plausible, and the model writes them down. So a design points to a particular model directly. In the examples below those models are linear regression equations; in general they need not be, and the models of @sec-overfitting and @sec-unsupervised are not.\n\nCampbell and Stanley introduced a convenient way of depicting some designs in a small table, which Shadish, Cook and Campbell carry forward [@campbell1963]. It does not encompass every possible research design, but it is useful in many specific cases. Read the tables like a timetable: columns run left to right in time, $O$ marks a measurement, $X$ marks the treatment, and $R$ means that the row was formed by a random device. A row is a group, so the group indicator $T_i$ in the equations below says which row a unit sits in; a column is a time, so a period indicator such as $\\text{Post}_t$ says which column an observation sits in. Each design below is given with the model typically used to estimate effects from it.\n\nThe equations share a notation. The subscript $i$ indexes units, whatever the units of the study are: people, restaurants, municipalities. The subscript $t$ indexes time, and $p$ indexes the two periods of a crossover. Throughout, $y$ is the outcome, $\\beta_0$ is the intercept, and $\\varepsilon$ is the **disturbance**, which stands for everything about the outcome the equation does not model. Later chapters also call this term the *error* or the *noise*, and its estimated counterpart in a fitted model the *residual*; the four words will alternate. $T_i = 1$ if unit $i$ belongs to the treated group and 0 otherwise, and $X_{ip} = 1$ when unit $i$ is actually receiving treatment in period $p$. Remaining symbols are defined where they appear.\n\n**Randomized experiment, posttest only.**\n\n| Group | assignment | treatment | measure |\n|---|---|---|---|\n| 1 | $R$ | $X$ | $O$ |\n| 2 | $R$ | — | $O$ |\n\n$$y_i = \\beta_0 + \\beta_1 T_i + \\varepsilon_i$$\n\nwith $T_i = 1$ for the treated, so $\\beta_1$ is the effect. Randomization removes selection bias by construction: the assignment mechanism is a coin flip, which shares no common causes with anything, so whatever differences remain between the groups are chance differences, and chance differences shrink predictably as the sample grows. Randomization does not stop history or maturation from happening; it makes them happen equally in both groups, up to that same chance. The threats that remain are attrition after assignment, people assigned to a treatment who do not take it (noncompliance), everything about construct validity, and every question of external validity (out-of-domain generalization).\n\n**Two groups, before and after (difference-in-differences).**\n\n| Group | measure | treatment | measure |\n|---|---|---|---|\n| 1 | $O$ | $X$ | $O$ |\n| 2 | $O$ | — | $O$ |\n\n$$y_{it} = \\beta_0 + \\beta_1 T_i + \\beta_2 \\text{Post}_t + \\beta_3\\,(T_i \\times \\text{Post}_t) + \\varepsilon_{it}$$\n\nThe product term $T_i \\times \\text{Post}_t$ is an **interaction**, a term whose coefficient says how much the effect of one variable changes with the value of another; here $\\beta_3$ is how much the before–after change differs between the treated group and the control group, so $\\beta_3$ estimates the effect. @sec-theory-to-glm treats interactions in general. The pretest lets the two groups start at different levels, so stable differences between them do not contaminate the estimate, and the control group absorbs whatever happened to everyone during the period. The assumption is that the two groups would have *changed* in parallel without the treatment. Selection combined with maturation breaks it. Two time points cannot reveal the break; more pre-treatment periods can, which is why careful difference-in-differences studies plot the trends for many periods before the treatment.\n\nThe famous instance is Card and Krueger's study of the minimum wage [@card1994]. New Jersey raised its minimum from \\$4.25 to \\$5.05 an hour in April 1992 and Pennsylvania did not, so they surveyed 410 fast-food restaurants on both sides of the border before and after. Employment in New Jersey rose relative to Pennsylvania by 2.76 full-time-equivalent workers per restaurant, against the prediction of the standard competitive model that it would fall. The finding was contested for years on the ground that telephone surveys measure employment badly, which is a dispute about construct validity [@neumark2000; @card2000].\n\n**Crossover.**\n\n| Group | assignment | period 1 | measure | period 2 | measure |\n|---|---|---|---|---|---|\n| 1 | $R$ | $X$ | $O$ | — | $O$ |\n| 2 | $R$ | — | $O$ | $X$ | $O$ |\n\n$$y_{ip} = \\beta_0 + \\beta_1 X_{ip} + \\alpha_i + \\varepsilon_{ip}$$\n\nEveryone receives both conditions in a randomized order. The person-specific term $\\alpha_i$ is a separate intercept for each person, a **fixed effect** for persons in the vocabulary of panel data; @sec-anova returns to this term and to the choice between treating it as fixed or as random. It absorbs everything stable about person $i$, so $\\beta_1$ compares each person with themselves, and every stable difference between people disappears at once. Anything that changes between the two periods for everyone alike needs a term of its own, which is why the analysis usually carries a period effect as well. The price is a new assumption: no carryover. If the first treatment is still working when the second begins, the within-person contrast is contaminated. The design fits treatments that wash out quickly, and chronic conditions that return when treatment stops.\n\n**Matched case–control.** Here units are sampled *on the outcome*: people with the disease, and people without it chosen to resemble them on age, sex, and neighbourhood. There is no time axis to draw, because exposure is reconstructed backwards. The analysis is a *conditional* logistic regression of case status on exposure, with one stratum per matched set,\n\n$$\\log\\frac{P(\\text{case}_i)}{1 - P(\\text{case}_i)} = \\alpha_{s(i)} + \\beta_1 E_i,$$\n\nwhere $E_i = 1$ if person $i$ was exposed, and $s(i)$ is the matched set that person $i$ belongs to. The left-hand side is the log-odds of being a case, the scale on which logistic regression works; @sec-theory-to-glm explains that scale and the odds ratio. Each matched set has its own intercept $\\alpha_{s(i)}$, so the comparison of exposed with unexposed is made only within sets; $\\exp(\\beta_1)$ estimates the odds ratio, the factor by which exposure multiplies the odds of being a case. Matching that is not carried into the analysis biases the estimate toward zero, because the controls were chosen to resemble the cases and so look more like them than a random sample would; design and model have to agree. This is the weakest member of the catalogue, because matching handles only the variables you matched on, and only if you measured them well. It also has a measurement problem of its own, called **recall bias**. Exposure is reported after the disease is known, and someone who has spent a year wondering what caused their illness searches their memory harder than a healthy control does. If cases report past exposures more completely than controls, that difference in reporting is enough to produce an association on its own.\n\n**Interrupted time series.**\n\n| Group | | | | | | | | |\n|---|---|---|---|---|---|---|---|---|\n| 1 | $O$ | $O$ | $O$ | $O$ | $X$ | $O$ | $O$ | $O$ |\n\n$$y_t = \\beta_0 + \\beta_1 t + \\beta_2 \\text{After}_t + \\beta_3\\,(t - t_0)\\,\\text{After}_t + \\varepsilon_t,$$\n\nwhere $t_0$ is the period in which the intervention arrives and $\\text{After}_t = 1$ from then on. So $\\beta_2$ is the jump in level at the intervention and $\\beta_3$ the change in slope afterwards. Many observations before the interruption make maturation and regression to the mean visible rather than merely possible, since you can see the trend. The main remaining threat is history, with instrumentation second, and there is a technical problem as well: consecutive observations of the same series are correlated, usually positively, so the ordinary standard errors are too small and the model needs a term for that correlation. Ruling out history is why the Breathalyser analysis added a control series and looked for a pattern that only the law could produce, leading to what we would now call a difference-in-differences design.\n\n**Regression discontinuity** turns a sharp administrative rule into an experiment. Scholarships, remedial classes, and reimbursement for a drug are routinely allocated by a threshold on a measured score, and such a rule is the opposite of random: it assigns treatment according to a variable that is itself related to the outcome, which would ordinarily be the worst case for selection bias. Here it is the basis of the design, because the rule is known exactly. Units a little below and a little above the cutoff are alike in everything except which side of the line they landed on. So compare them, writing $c_i$ for the score and $c_0$ for the cutoff:\n\n$$y_i = \\beta_0 + \\beta_1 (c_i - c_0) + \\beta_2 D_i + \\beta_3 (c_i - c_0) D_i + \\varepsilon_i, \\qquad D_i = \\mathbb{1}[c_i \\ge c_0],$$\n\nwhere the bracket $\\mathbb{1}[\\cdot]$ is an *indicator*, equal to 1 when the condition inside it holds and 0 otherwise, so that $D_i = 1$ for units on the treated side of the cutoff, and $\\beta_2$ is the effect at the cutoff [@shadish2002]. Britain raised its school leaving age twice, in 1947 and in 1972, and each change took effect sharply at one birth month, which let Clark and Royer compare cohorts either side of the cutoff: schooling and wages moved, and adult mortality did not [@clark2013]. Three things have to be granted. Nothing else may change at the cutoff. Nobody may manipulate their score to cross it. And the curve has to be right: a bend mistaken for a straight line will manufacture a jump that is not there, which is why the equation lets the slope differ on each side, and why in practice the comparison is restricted to a window around the cutoff rather than fitted to units at any distance from it.\n\nThis catalogue is not general, but the approach behind it is: for a given design, ask which alternative explanations it removes by construction, which it leaves standing, and which assumption you are being asked to grant. @tbl-designs answers those questions for the six designs above.\n\n| Design | Assumption the design makes plausible | Threats left standing |\n|---|---|---|\n| Randomized experiment | The groups differ only by chance | Attrition; noncompliance; construct validity; external validity |\n| Difference-in-differences | The groups would have changed in parallel without the treatment | Selection combined with maturation (different trajectories); history that affects one group only |\n| Crossover | Each person is their own control, so stable differences between people cancel | Carryover; anything that changes between periods, unless a period term is included |\n| Matched case–control | The matched variables account for selection | Confounders not matched on, or matched on badly; recall bias |\n| Interrupted time series | The pre-intervention trend would have continued | History; instrumentation; serial correlation in the standard errors |\n| Regression discontinuity | Units just either side of the cutoff are alike except in treatment | Something else changing at the cutoff; manipulation of the score; a wrong curve |\n\n: The six designs of this section: what each one makes plausible, and what it leaves for argument. {#tbl-designs}\n\n::: {.callout-tip icon=\"false\" title=\"Exercise 1.3\"}\nA regional government offers free flu vaccination in half of its municipalities and not in the other half; municipalities were not randomized. Hospital admissions for respiratory illness are recorded in both, in the year before and the year after.\n\n(a) Draw the design in the notation above.\n(b) Write the regression equation and say which coefficient estimates the effect.\n(c) What does that coefficient assume?\n(d) The untreated municipalities are more rural. Does that, by itself, break the design? What would?\n:::\n\n::: {.callout-note collapse=\"true\" icon=\"false\" title=\"Answer 1.3\"}\n(a) Row 1: $O \\; X \\; O$. Row 2: $O \\; \\; O$. No $R$ in either row.\n(b) $y_{it} = \\beta_0 + \\beta_1 T_i + \\beta_2 \\text{Post}_t + \\beta_3 (T_i \\times \\text{Post}_t) + \\varepsilon_{it}$; the effect is $\\beta_3$.\n(c) That admissions in the two sets of municipalities would have moved in parallel had nobody been vaccinated.\n(d) A constant rural–urban difference in the level of admissions is what the design tolerates: $\\beta_1$ absorbs it. The design breaks if rural and urban areas were on different *trajectories*, for example because rural populations were ageing faster, or if a flu strain happened to hit cities harder that winter.\n:::\n\n::: {.callout-tip icon=\"false\" title=\"Exercise 1.4\"}\nAn interrupted time series has 24 monthly counts, and the intervention arrives at $t_0 = 12$.\n\n(a) Using the interrupted time series equation, write the fitted value at $t = 11$ and at $t = 13$, and simplify their difference.\n(b) A fit gives $\\beta_1 = -0.5$, $\\beta_2 = -15$ and $\\beta_3 = 0$. Say in words what happened.\n(c) Which threat does a nonzero $\\beta_1$ make *visible*, and which threat does the design still leave standing?\n:::\n\n::: {.callout-note collapse=\"true\" icon=\"false\" title=\"Answer 1.4\"}\n(a) At $t = 11$, $\\text{After}_t = 0$, so $\\hat y_{11} = \\beta_0 + 11\\beta_1$. At $t = 13$, $\\text{After}_t = 1$ and $t - t_0 = 1$, so $\\hat y_{13} = \\beta_0 + 13\\beta_1 + \\beta_2 + \\beta_3$. The difference is $2\\beta_1 + \\beta_2 + \\beta_3$: two months of the old trend, the jump, and one month of the change in slope.\n(b) The counts were already falling by 0.5 a month before the intervention. At the intervention the level dropped by 15, and the trend afterwards was the same as before.\n(c) Maturation, in the form of a trend that was under way before the intervention, becomes visible and is taken out by $\\beta_1$. History, something else happening at $t_0$, is untouched by the design, which is why the Breathalyser analysis needed the commuting-hours control series.\n:::\n\n## Elements of a verbal theory {#sec-verbal-theory}\n\nThe approach of @shadish2002 is useful because it encourages design-first thinking and lets you identify some of the potential problems with a proposed design. It is, however, quite limited in the types of question and design it can easily accommodate, and it does not systematically identify which threats to internal validity matter most in a given study. So this chapter and the next turn to a more systematic approach: identifying a research question, formulating a design that suits it, building and analysing a model that the design motivates, stating the assumptions explicitly, checking the ones that can be checked, and drawing careful conclusions. This approach comes from the classic text by @saris1984.^[It resembles the now more popular framework of *structural causal modeling* (SCM) [@pearl2009], in that it builds up a path diagram that can answer causal questions. It differs in emphasis: Saris and Stronkhorst spend most of their effort on how the diagram should be arrived at, whereas Pearl usually takes the diagram as given and analyses its properties nonparametrically.]\n\nSaris and Stronkhorst start from the idea that there is a \"verbal theory\". They break every substantive theory into three ingredients.\n\n**Units of analysis.** Who or what carries the properties you are studying? Individuals, households, schools, hospital admissions, districts, countries, published studies, or a person on a particular day. A theory about how earthquakes affect a person's trust in government is about people, not about regions, even though the earthquakes happen to regions. The distinction matters because data are often available only at the regional level while the question is about people, and the mismatch introduces a fresh set of potential confounders, a problem known as **ecological bias**.\n\n**Variables.** A variable is a property of a unit that varies across units. \"Poverty\" can be a variable; \"poor\" cannot, because it is a value of one. A constant explains nothing. Nor can a whole social process be treated as a single variable and called a cause: \"discrimination\" is a phenomenon with many measurable components, not a column in a spreadsheet.\n\n**Relationships.** An **association** says that units high on one variable tend to be high on the other, or low, for a negative association. It is symmetric: reading it backwards changes nothing. An **effect** says that changing one variable would change the other. It is asymmetric, and it is a claim about a world we do not observe. An association without an effect behind it is a **spurious relationship**, one due to a common cause of both variables, like drownings and ice cream sales, which rise together because both rise with the temperature; @sec-theory-to-glm gives spurious relationships a precise place in the decomposition rule, which splits an association into the effects and common causes that produce it.\n\nEffects come in a few kinds, drawn in @fig-relationships, and the rest of the book uses this vocabulary constantly. A **direct** effect runs straight from cause to outcome. An **indirect** effect runs through an intervening variable. **Reciprocal** effects run both ways. A **conditional** effect is an effect whose size depends on a third variable.\n\nTwo further words describe the shape of an effect, and Exercise 1.A asks about both. An effect is **linear** when a one-unit change in the cause produces the same change in the outcome wherever you start, so that the relationship is a straight line. Effects are **additive** when the effect of one cause does not depend on the value of another, so that the two contributions can be added; a conditional effect is the non-additive case. @sec-theory-to-glm shows how both properties are written into a model and what happens when a theory denies one of them.\n\n![The vocabulary of relationships. An association is drawn with a two-headed arrow, an effect with a single-headed one. A conditional effect is drawn as an arrow pointing at an arrow: the size of the effect of x on y depends on the value of z.](diagrams/relationships.png){#fig-relationships width=\"95%\" fig-align=\"center\"}\n\nDiagrams of this kind have a settled grammar, and @sec-theory-to-glm sets it out in full. Three conventions are enough for now: a box holds a variable you measured, a single-headed arrow means an effect, and a curved two-headed arrow means an association you are not explaining. Variables that nothing in the model explains are called **exogenous**, and any association among them gets a curved arrow, since leaving it out would claim they are unrelated. Not shown are *unmeasured* variables, which occur in theories just as often: these go in circles rather than boxes.\n\nTake a familiar example. Ajzen's theory of planned behaviour gives intention three determinants; the one that concerns us here is **perceived behavioral control**, a person's sense of how easy or hard the action would be. Intention captures the motivation behind an action, and stronger intentions make the action more likely. But intention converts into behaviour only when the person can actually do the thing, since an action needs time, money, skill, or the cooperation of others, which Ajzen calls actual behavioral control and we will shorten to **actual control**. And people's perception of their own control shapes both what they intend and what they manage to do [@ajzen1991]. @fig-tpb draws the part of the theory we need.\n\n![The theory of planned behaviour, in part. Perceived control affects intention and behaviour; actual control governs whether an intention can be converted into behaviour at all, which is a conditional effect.](diagrams/tpb.png){#fig-tpb width=\"75%\" fig-align=\"center\"}\n\nRead as a set of claims, the theory has these elements.\n\n- **Units of analysis.** Individual people.\n- **Variables.** Intention, perceived behavioral control, actual control, behaviour.\n- **Effects.** Perceived control on intention; intention on behaviour; perceived control on behaviour.\n- **A conditional effect.** Actual control governs how far an intention converts into behaviour. Ajzen draws the implication explicitly: \"intentions and perceptions of behavioral control should interact in the prediction of behaviour\" [@ajzen1991].\n\n::: {.callout-tip icon=\"false\" title=\"Exercise 1.5\"}\nA researcher writes: \"Students who feel more in control of their studies plan to study more, and those plans translate into hours at the desk, particularly for students who live alone and can organize their own time.\"\n\n(a) What are the units of analysis?\n(b) List the variables.\n(c) Name each relationship and say whether it is an association or an effect, and of which kind.\n(d) Are there any conditional effects?\n:::\n\n::: {.callout-note collapse=\"true\" icon=\"false\" title=\"Answer 1.5\"}\n(a) Individual students.\n(b) Perceived control over studying, intention to study, hours studied, and living alone.\n(c) Perceived control → intention (direct effect); intention → hours (direct effect); perceived control → hours through intention (indirect effect).\n(d) Yes, one. Living alone does not act on hours by itself in this sentence: \"particularly for students who live alone\" says that the size of the intention → hours effect depends on it. That is a conditional effect, drawn as an arrow into the intention → hours arrow.\n:::\n\n## Five questions to ask of any study {#sec-five-questions}\n\nHere are five questions you can use to think about applications of statistics and data science.\n\n1. **What is the question?** Descriptive, causal, or predictive, and stated precisely enough that two people would agree on what would answer it.\n2. **What are the units, the variables, and the claimed relationships?** Associations or effects; direct, indirect, reciprocal, conditional.\n3. **How were these data produced?** Who was measured, when, by what mechanism, and who is missing.\n4. **What must be true for the model's numbers to answer the question?** Write the assumptions down.\n5. **What in the design makes those assumptions plausible, and what happens if they fail?** Which alternative explanations does the design remove by construction, and which are left to argument?\n\nQuestion 5 is the one this book keeps coming back to. In @sec-theory-to-glm a theory becomes a model whose numbers mean something only if the model is true. In @sec-identification the question takes its most difficult form: some questions cannot be answered by any amount of data, because the design produced no information about the answer.\n\n## What to carry forward {.unnumbered}\n\nEvery empirical study follows the chain question → design → assumptions → model → answer, and the numbers answer the question only to the extent that the assumptions hold (@sec-chain). Questions are descriptive, causal or predictive, and a causal question always compares what happened with a counterfactual that nobody observed (@sec-question-types). Validity is the plausibility of the assumptions behind a claim, sorted into internal, external, construct and statistical conclusion validity, and the named threats to internal validity are the alternative explanations a design has to remove (@sec-validity). Each design removes some threats by construction and leaves others for argument, and it points to a model that writes its assumptions down; the randomized experiment, difference-in-differences and the rest are summarized in @tbl-designs (@sec-designs). A verbal theory has units, variables and relationships, and the vocabulary of associations and direct, indirect, reciprocal and conditional effects, with the theory of planned behaviour as the example, is what @sec-theory-to-glm turns into path diagrams and equations (@sec-verbal-theory). The five questions of @sec-five-questions return at the end of @sec-identification, @sec-explanation-prediction and @sec-evaluation; the fishing of @sec-validity returns in @sec-evaluation as leakage; and the Oregon lottery of Exercise 1.B returns in @sec-identification as an instrumental variable.\n\n**Terms and symbols introduced.** design; model; descriptive, causal and predictive questions; total survey error; identification strategy; validity (internal, external, construct, statistical conclusion); threat to validity, with the eight named threats; fishing, p-hacking, HARKing; disturbance; interaction; fixed effect; recall bias; ecological bias; association; effect (direct, indirect, reciprocal, conditional); spurious relationship; linear; additive; exogenous; perceived behavioral control and actual control; $y$ the outcome, $\\beta_0$ the intercept, $\\varepsilon$ the disturbance, $T_i$ the group indicator, $\\text{Post}_t$ and $\\text{After}_t$ period indicators, $X_{ip}$ treatment received in period $p$, $\\alpha_i$ a person's fixed effect, $\\mathbb{1}[\\cdot]$ the indicator function; in the design tables, $O$ a measurement, $X$ the treatment, $R$ random assignment.\n\n**Exercises that use R.** 1.D (a simulation of confounding); 1.F, optional, uses R for one integral.\n\n## Further study {.unnumbered}\n\n@shadish2002 is the full statement of the validity framework, with a longer catalogue of threats and of the designs that block them than this chapter could give, and is the book to open when planning a quasi-experiment. @saris1984 is the source of the verbal-theory approach of this chapter and of the path-model treatment of @sec-theory-to-glm, and remains the most careful account of how to get from a theory in words to a diagram. @angrist2014 covers the randomized experiment, regression, instrumental variables, regression discontinuity and difference-in-differences with worked examples and no more mathematics than this chapter, and is the natural companion for the design catalogue. @rohrer2018 introduces the graphical language for confounding that @sec-theory-to-glm and @sec-identification use, written for psychologists and at the level of this chapter. @hernan2019 is the source of the descriptive–causal–predictive taxonomy and argues, in a few pages, for stating which kind of question a study answers. @groves2010 is the reference for total survey error, the framework for the descriptive questions this book treats only briefly.\n\n## Test yourself {.unnumbered}\n\n::: {.callout-tip icon=\"false\" title=\"Exercise 1.A\"}\nThe general aggression model describes single episodes of aggression in three stages [@allen2018]. Person factors (such as believing that aggression is normal) and situation factors (such as being provoked, or a hot and noisy room) influence a person's present internal state, which consists of cognition, affect, and arousal. Those three influence one another in reciprocal ways: anger produces hostile thoughts, and hostile interpretations produce anger. The internal state feeds appraisal and decision processes, which issue in an aggressive or non-aggressive action. The action changes the encounter, which changes the person and situation factors, and the cycle begins again. Person and situation factors, the authors write, \"can work additively or interactively\".\n\n(a) Specify the units of analysis.\n(b) List the variables.\n(c) Name the causal relationships. Are they all linear and additive? Why or why not?\n(d) Draw the path diagram, including correlations among any exogenous variables.\n:::\n\n::: {.callout-note collapse=\"true\" icon=\"false\" title=\"Answer 1.A\"}\n(a) Episodes of social encounter, experienced by persons. Answering \"persons\" works only if you add that each person contributes many episodes; the theory is about what happens within one encounter and then across encounters.\n(b) Person factors, situation factors, cognition, affect, arousal, appraisal and decision processes, and the aggressive or non-aggressive outcome.\n(c) Person and situation factors affect the three internal-state variables; the internal-state variables affect each other reciprocally; the internal state affects appraisal; appraisal affects the outcome; the outcome feeds back to the inputs. So: direct effects, indirect effects through the internal state, reciprocal effects among cognition, affect and arousal, and a feedback loop across episodes. Not additive, since the authors say inputs can work interactively and give the example of believing aggression is normal, being provoked, and sitting in a hot, noisy room all at once. Linearity is a separate question, and the theory says nothing about it, so straight lines are the analyst's choice rather than the theory's claim.\n(d) @fig-gam. Count the arrows as you draw them. Person factors and situation factors each affect cognition, affect and arousal, which is six. Each pair among those three carries an arrow in each direction, which is six more. All three feed appraisal, appraisal feeds the action, and the action feeds back on both inputs in the next episode. The curved two-headed arrow between the exogenous variables is the element readers forget most often. It belongs there because nothing in the theory explains their covariation, and provoking situations are not distributed at random across people; leaving it out would claim that they are.\n\n![The general aggression model as a path diagram. Cognition, affect and arousal are the present internal state, and each pair among them carries an arrow in each direction, because the theory says they influence one another reciprocally. Person and situation factors are exogenous, so their covariation is drawn with a two-headed arrow rather than explained.](images/gam-path-diagram.png){#fig-gam width=\"100%\" fig-align=\"center\"}\n:::\n\n::: {.callout-tip icon=\"false\" title=\"Exercise 1.B\"}\nIn 2008 the state of Oregon had money to add about 10,000 adults to its Medicaid programme and far more applicants than places. It ran a lottery. Roughly 90,000 people put their names on the list in a five-week window, and 35,000 were drawn. Being drawn gave a household the right to apply; among those drawn, coverage ended up about 25 percentage points higher than among those not drawn, since many never returned the paperwork and others were found ineligible. Two years later, researchers compared those drawn with those not drawn on blood pressure, cholesterol, blood sugar, depression, and financial strain [@finkelstein2012; @baicker2013].\n\n(a) What are the units of analysis, and what is the treatment?\n(b) Which assumption does the lottery make plausible, and which threats does it leave standing?\n(c) The comparison of drawn with not-drawn estimates one thing; the effect of actually having Medicaid is another. Explain the difference and say which one the lottery speaks to unaided.\n(d) The study found no detectable effect on blood pressure, cholesterol, or blood sugar, and a substantial reduction in depression. A commentator concludes that health insurance does not improve physical health. Give two reasons to be careful with that conclusion.\n:::\n\n::: {.callout-note collapse=\"true\" icon=\"false\" title=\"Answer 1.B\"}\n(a) Units are individual adults, drawn as households. The treatment is the right to apply for Medicaid coverage; coverage itself is what people did with that right.\n(b) The lottery makes selection implausible: drawn and undrawn people differ only by chance, so no common cause explains any difference in outcomes. It leaves attrition and non-response, since people who agree to be interviewed two years later may differ by arm; construct validity, since \"Medicaid\" is a package of coverage, cost, and access to particular providers; and external validity, since these were low-income adults in one state who had actively signed up.\n(c) Comparing everyone drawn with everyone not drawn estimates the effect of winning the lottery, the intention-to-treat effect, and that is what the lottery speaks to unaided. Coverage rose by only about 25 percentage points, so the effect of coverage itself must be roughly four times larger, and recovering it requires the extra assumption that being drawn changed health only by way of coverage. Dividing an effect on those offered a treatment by the shift in how many took it up is a standard procedure with assumptions of its own; @sec-identification describes the procedure and its assumptions.\n(d) First, \"no detectable effect\" is a statement about power, the probability that a study of this size would detect an effect of a given size if it were there, and the intervals around the blood-pressure effect comfortably include changes that would matter clinically. Second, two years is a short window for cholesterol and blood sugar, and the treatment was insurance rather than care, so it can only work through the care people then seek.\n:::\n\n::: {.callout-tip icon=\"false\" title=\"Exercise 1.C\"}\nThrough the 1980s and 1990s, large observational cohorts reported that women taking hormone replacement therapy after menopause had much less coronary heart disease than women who did not; in the Nurses' Health Study the relative risk for combined oestrogen and progestin was 0.39, meaning about 60 percent fewer events among users [@grodstein1996]. Hormone therapy was widely prescribed for heart protection. In 2002 the Women's Health Initiative, a randomized trial in 16,608 women, was stopped early: the treated group had *more* coronary heart disease, with a hazard ratio of 1.29 (a relative risk computed over the follow-up time), and more strokes and invasive breast cancer as well [@whi2002].\n\n(a) Which threat to internal validity is the leading candidate, and in which direction would it bias the observational estimate?\n(b) The cohort studies adjusted for age, smoking, blood pressure, cholesterol, and body mass index. Why did that not solve the problem?\n(c) Name one feature of the trial that could, by itself, explain part of the discrepancy without any bias in the cohorts.\n(d) You are asked in 1995 to design a study that would have settled the question. Sketch it, and say which threats your design removes by construction.\n(e) A colleague concludes that observational research on drug effects is worthless. Give the strongest version of the counterargument.\n:::\n\n::: {.callout-note collapse=\"true\" icon=\"false\" title=\"Answer 1.C\"}\n(a) Selection, in the specific form known as healthy-user bias: the women who took hormones were richer, better educated, more physically active, and more likely to see a doctor. All of those lower heart disease on their own, so the observational estimate was biased toward showing protection.\n(b) Adjustment removes only the part of the difference captured by the variables you measured, at the moment you measured them. Socioeconomic position acts across a whole life, and one adult measurement of smoking and body mass index does not stand in for it; analyses that reconstruct socioeconomic position across the life course move the estimate toward the trial's [@lawlor2004]. This is the simulation of Exercise 1.D with a partially measured confounder.\n(c) Timing, in a specific sense. The cohorts were weighted toward women who had been taking hormones for years, while the trial measured mainly the first few years of use. Prentice and colleagues show that the hazard ratio falls with time since a woman starts, so the two designs were summarizing different stretches of one time course; allowing for that, together with confounding, brings the two sets of estimates much closer together [@prentice2005]. Part of the gap, then, is a question about which treatment was being studied rather than about bias in the cohorts.\n(d) A randomized, masked, placebo-controlled trial in women recruited at menopause, with coronary events as the primary outcome, sized for the event rate in that age group and run long enough to see them, with intention-to-treat analysis and tracking of everyone who stops. Randomization removes selection by construction; masking and a placebo control remove differential care and reporting; intention-to-treat protects against selection creeping back in through who stays on treatment. The design has costs: many years, many women, and a population healthy enough to consent, which trades external validity for internal validity.\n(e) That the cohorts were right about many other things, that a trial is impossible for most exposures anyone cares about, and that this failure was diagnosable in advance: the exposure was chosen by people, was strongly related to social position, and the outcome was strongly related to social position too. The lesson is to ask what a design does about selection, and to treat \"we adjusted for covariates\" as a claim requiring an argument.\n:::\n::: {.callout-tip icon=\"false\" title=\"Exercise 1.D\"}\nConfounding is easier to believe once you have simulated it in a world where you set the truth yourself. In this world, motivated people exercise more, and motivated people have fewer symptoms for reasons of their own. Exercise itself does nothing at all. Work in `R`.\n\n(a) Write a function `sim_study(randomize, n = 200)` that draws `motivation` from a standard normal distribution; sets `exercise` to `rbinom(n, 1, 0.5)` when `randomize` is `TRUE` and to `rbinom(n, 1, plogis(motivation))` otherwise; sets `symptoms` to `10 - 1.5 * motivation + 0 * exercise` plus standard normal noise; and returns the coefficient of `exercise` from `lm(symptoms ~ exercise)`. Which piece of that function states that exercise does nothing, and which states that people who exercise are different to begin with?\n(b) Run the function 1,000 times with `randomize = FALSE` and 1,000 times with `randomize = TRUE`. Draw the two sets of estimates as histograms on a common horizontal axis, and mark the truth. What is the average estimate in each set?\n(c) Compare the standard deviations of the two sets. Does confounding show up as extra noise?\n(d) Each of those studies would report a confidence interval, a range of values consistent with the data, computed so that it covers the true value in 95 percent of repeated samples (`confint()` gives it). Count how many of the thousand observational intervals exclude zero. What does the count say about the relationship between precision and correctness?\n(e) Raise the sample size to 10,000 and rerun the observational arm (call `sim_study(FALSE, n = 10000)` inside `replicate`). What happens to the average estimate, and what happens to the spread?\n(f) Back at $n = 200$, suppose motivation had been measured, and fit `lm(symptoms ~ exercise + motivation)` instead (copy `sim_study` and change the `lm` formula). What happens?\n(g) In a real study of exercise and symptoms, why is (f) less reassuring than it looks?\n:::\n\n::: {.callout-note collapse=\"true\" icon=\"false\" title=\"Answer 1.D\"}\n(a) The term `0 * exercise` in the line for `symptoms` sets the true effect to zero. The line for `exercise` in the `else` branch, `rbinom(n, 1, plogis(motivation))`, is what makes the exercisers different: their chance of exercising rises with motivation, and motivation lowers symptoms on its own.\n\n(b), (c), (d) The code below does all three; the summaries are printed underneath.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsim_study <- function(randomize, n = 200) {\n  motivation <- rnorm(n)\n  exercise   <- if (randomize) rbinom(n, 1, 0.5) else rbinom(n, 1, plogis(motivation))\n  symptoms   <- 10 - 1.5 * motivation + 0 * exercise + rnorm(n)\n  coef(lm(symptoms ~ exercise))[[\"exercise\"]]\n}\nset.seed(1)\nobservational <- replicate(1000, sim_study(randomize = FALSE))\nrandomized    <- replicate(1000, sim_study(randomize = TRUE))\n\nbins <- seq(-2.2, 1.0, by = 0.1)\npar(mfrow = c(1, 2))\nhist(observational, breaks = bins, xlim = c(-2.2, 1.0),\n     main = \"People chose\", xlab = \"estimated effect of exercise\")\nabline(v = 0, lwd = 2)\nhist(randomized, breaks = bins, xlim = c(-2.2, 1.0),\n     main = \"A coin chose\", xlab = \"estimated effect of exercise\")\nabline(v = 0, lwd = 2)\n```\n\n::: {.cell-output-display}\n![One thousand simulated studies of each kind, n = 200. The true effect of exercise is zero, marked by the vertical line. Observational studies (left) are wrong by about 1.2 points and know nothing of it; randomized ones (right) are centred on the truth and are just as noisy.](01-research-question-to-interpretation_files/figure-html/fig-confounding-1.png){#fig-confounding width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nround(c(obs_mean = mean(observational), rand_mean = mean(randomized),\n        obs_sd   = sd(observational),   rand_sd   = sd(randomized)), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n obs_mean rand_mean    obs_sd   rand_sd \n   -1.241    -0.002     0.235     0.245 \n```\n\n\n:::\n\n```{.r .cell-code}\nci_excludes_zero <- function(n = 200) {\n  motivation <- rnorm(n)\n  exercise   <- rbinom(n, 1, plogis(motivation))\n  symptoms   <- 10 - 1.5 * motivation + rnorm(n)\n  ci <- confint(lm(symptoms ~ exercise))[\"exercise\", ]\n  ci[1] > 0 || ci[2] < 0\n}\nset.seed(1)\nsum(replicate(1000, ci_excludes_zero()))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 998\n```\n\n\n:::\n:::\n\n\nAveraged over the thousand observational studies the estimated effect is $-1.24$; the truth is zero. Averaged over the randomized studies it is $0.00$. The two histograms in @fig-confounding are equally wide, with standard deviations of 0.235 and 0.245, so confounding is not noise and does not show up as instability. And 998 of the thousand observational confidence intervals exclude zero, so precision is no guarantee of correctness.\n\n(e) The spread collapses, from about 0.24 to about 0.03, and the average estimate stays at about $-1.24$. The two parts of the error now have names. The part that shrinks with the sample is the **variance** of the estimator, the noise of sampling; the part that stays, the gap of $-1.24$ between the average estimate and the truth, is its **bias**, a systematic error that survives any sample size. Bias does not shrink as the sample grows; this is the most useful thing to know about confounding. This sense of bias, a systematic error caused here by confounding, is the one chapters 1–3 use; @sec-overfitting uses the word for the related but distinct idea of a model that is too simple for the truth, and says there how the two are connected.\n\n(f) The estimates centre on zero, with a standard deviation of about 0.15. Adjusting for a confounder you have measured works.\n\n(g) In a real study you adjust for the confounders you thought of and measured well, and the assumption that this is all of them cannot be checked from the data. Randomization handles the ones you never thought of; regression cannot. The next chapters keep returning to this asymmetry.\n:::\n\n::: {.callout-tip icon=\"false\" title=\"Exercise 1.E\"}\nApply the five questions of @sec-five-questions to the Breathalyser study of the opening pages. For question 5, list the alternative explanations that the comparison of weekend nights with commuting hours removes, and the one it does not.\n:::\n\n::: {.callout-note collapse=\"true\" icon=\"false\" title=\"Answer 1.E\"}\n1. The question is causal: did the Road Safety Act reduce road casualties? The counterfactual is the Britain in which the Act was never passed.\n2. The units are blocks of hours within a month (weekend nights, commuting hours), observed month by month. The variables are the casualty count, which series the block belongs to, and whether the month is before or after October 1967. The claimed relationship is an effect of the law on casualties that is conditional on the series: present on weekend nights and absent during commuting hours.\n3. The data are police records of casualties, aggregated by month and by hour of the day. The question to ask is whether recording practice changed in October 1967, which would be an instrumentation threat.\n4. The assumption is that, without the law, the two series would have moved in parallel, so that the commuting-hours series shows what the weekend-night series would have done. The design is an interrupted time series with a control series, and the model is the difference-in-differences equation of @sec-designs.\n5. Because both series are counted by the same police forces in the same months, the comparison removes anything that moves both alike: the weather, petrol prices, a general improvement in road safety, and any change in how a casualty is defined or recorded. It does not remove anything that affected late-night driving alone at the same moment, such as the publicity campaign that accompanied the Act, mentioned in the opening pages. That explanation is left to argument rather than removed by construction.\n:::\n\n::: {.callout-tip icon=\"false\" title=\"Exercise 1.F (optional)\"}\nThis last exercise is optional and harder than the others: it derives, in algebra, the number the observational estimator of Exercise 1.D converges to. Nothing later in the book depends on it.\n\nWrite $m$ for motivation and $e$ for exercise, so that in the world of Exercise 1.D, $m$ is standard normal, $P(e = 1 \\mid m) = \\text{plogis}(m)$, and symptoms are $s = 10 - 1.5\\,m + \\varepsilon$ with $\\varepsilon$ independent of everything else.\n\n(a) Show that the least-squares slope of $s$ on $e$ converges, as $n$ grows, to $-1.5\\,\\mathrm{Cov}(m, e)/\\mathrm{Var}(e)$.\n(b) By symmetry $P(e = 1) = 0.5$, so $\\mathrm{Var}(e) = 0.25$. Compute $\\mathrm{Cov}(m, e) = E[m \\cdot \\text{plogis}(m)]$ numerically, either with `integrate(function(m) m * plogis(m) * dnorm(m), -Inf, Inf)` or from a draw of a million values, and give the limit.\n(c) Why does $n$ not appear in the answer?\n:::\n\n::: {.callout-note collapse=\"true\" icon=\"false\" title=\"Answer 1.F\"}\n(a) The least-squares slope of $s$ on $e$ is the sample covariance of $s$ and $e$ divided by the sample variance of $e$, and as $n$ grows these converge to the population quantities $\\mathrm{Cov}(s, e)/\\mathrm{Var}(e)$. Since $s = 10 - 1.5\\,m + \\varepsilon$ and $\\varepsilon$ is independent of $e$, $\\mathrm{Cov}(s, e) = -1.5\\,\\mathrm{Cov}(m, e)$, which gives the expression.\n\n(b) Because $E(m) = 0$, $\\mathrm{Cov}(m, e) = E(m e) = E[m \\cdot P(e = 1 \\mid m)] = E[m \\cdot \\text{plogis}(m)]$.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncov_me <- integrate(function(m) m * plogis(m) * dnorm(m),\n                    -Inf, Inf)$value\nround(c(cov_me = cov_me, limit = -1.5 * cov_me / 0.25), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ncov_me  limit \n 0.207 -1.240 \n```\n\n\n:::\n:::\n\n\nSo $\\mathrm{Cov}(m, e) = 0.207$ and the limit is $-1.5 \\times 0.207/0.25 = -1.24$, the average that the simulation in Exercise 1.D found at $n = 200$ and again at $n = 10{,}000$.\n\n(c) The limit is a property of the population: of how strongly motivation drives exercise and how strongly it drives symptoms. Sampling only adds noise around it, which shrinks with $n$; the limit itself does not move. This is part (e) of Exercise 1.D in algebra: the variance of the estimator goes to zero and the bias stays.\n:::\n",
    "supporting": [
      "01-research-question-to-interpretation_files/figure-html"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}