{
  "hash": "b179dda6196fdfbb7aa6a51f53edcc33",
  "result": {
    "engine": "knitr",
    "markdown": "# From ANOVA to multilevel models and meta-analysis {#sec-anova}\n\nIn a famous sleep laboratory study, eighteen volunteers slept three hours a night for ten days while researchers measured their reaction times daily.^[The data ship with the R package lme4 as `sleepstudy` [@gelmanhill2007 discuss closely related designs]. The original study is by Belenky and colleagues; the dataset has become a standard example in multilevel modelling.] Two things drive those reaction times: how sleep-deprived you are, and who you are. The analysis of this ordinary design, persons crossed with conditions, is called **analysis of variance**, ANOVA, and ANOVA has a poor reputation. The name evokes agricultural experiments and tables full of capital letters. Econometricians see a dull special case of regression; Bayesians see an inflexible classical ritual [@gelman2005]. Both views overlook the one idea behind ANOVA, an idea that underlies much of modern statistics: group the coefficients of a (generalized) linear model into batches, and study the variation within each batch. This chapter follows that idea in four steps, from the century-old F table to Bayesian multilevel models, and from there to meta-analysis.\n\n## A regression with 27 coefficients {#sec-coefficient-wall}\n\nTake the regression machinery of @sec-theory-to-glm and regress reaction time on day and person. Both predictors are categorical, so each becomes a set of 0/1 variables:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(lme4)   # provides the sleepstudy data\nsleep <- transform(sleepstudy, Days = factor(Days), Subject = factor(Subject))\nfit_lm <- lm(Reaction ~ Days + Subject, data = sleep)\nlength(coef(fit_lm))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 27\n```\n\n\n:::\n\n```{.r .cell-code}\nround(coef(fit_lm)[c(\"Days9\", \"Subject309\")], 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     Days9 Subject309 \n      94.2     -126.9 \n```\n\n\n:::\n:::\n\n\nThe first line loads the data, the second turns day and person into factors, and the third fits the regression, which has 27 coefficients: an intercept, nine day effects (day 0 is the reference), and seventeen person effects (subject 308 is the reference). Some of them are informative. The day-9 coefficient is 94.2: after nine days of deprivation, people react on average 94 milliseconds slower than on day 0, a large effect, and a dangerous one for anyone who drives. The subject coefficients run from $-127$ to $+34$: people differ from the reference person by up to a tenth of a second in either direction. The seventeen person coefficients, however, answer a question nobody asked. Nobody cares that subject 309 is 126.9 ms faster than subject 308; what we want to know is how much people differ in general. The regression answers the wrong question, and the list of coefficients only grows with the data: a study with 500 subjects would print 499 of these numbers.\n\nANOVA is the classical answer to this complaint. Instead of printing every coefficient, summarize each *batch* of coefficients, the day batch and the person batch, by how much variation it accounts for.\n\n## Sums of squares: the classical machinery {#sec-sums-of-squares}\n\nOne batch shows the machinery at its simplest, so ignore days for a moment and ask only: how much of the variation in reaction time lies between persons, and how much within? Write $y_{ij}$ for measurement $j$ of person $i$, $\\bar y_i$ for person $i$'s mean, and $\\bar y$ for the grand mean. Every observation's deviation from the grand mean splits into two pieces,\n\n$$\ny_{ij} - \\bar y = (\\bar y_i - \\bar y) + (y_{ij} - \\bar y_i),\n$$\n\na between-person piece and a within-person piece. Square everything, sum over the whole dataset, and the total variation splits the same way, because the cross-terms cancel:\n\n$$\n\\underbrace{\\textstyle\\sum_{ij} (y_{ij} - \\bar y)^2}_{\\text{total SS}} \\;=\\;\n\\underbrace{\\textstyle\\sum_i n_i (\\bar y_i - \\bar y)^2}_{\\text{between SS}} \\;+\\;\n\\underbrace{\\textstyle\\sum_{ij} (y_{ij} - \\bar y_i)^2}_{\\text{within SS}} .\n$$\n\n\"SS\" stands for sum of squares, and this decomposition is the analysis of variance, literally: variance, analysed into parts. With two batches the same logic splits the total into a days part, a persons part, and a residual. R's `aov()` prints the result as the classical table:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit_aov <- aov(Reaction ~ Days + Subject, data = sleep)\nsummary(fit_aov)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             Df Sum Sq Mean Sq F value Pr(>F)    \nDays          9 166235   18471   18.70 <2e-16 ***\nSubject      17 250618   14742   14.93 <2e-16 ***\nResiduals   153 151101     988                   \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nRead the table column by column. The sums of squares say how much variation each batch accounts for: about 166,000 for days, 251,000 for persons, 151,000 left over. The degrees of freedom (df) count the coefficients in each batch: 9, 17, and 153 for the residuals. This is the same count that gave the chi-square its degrees of freedom in @sec-theory-to-glm, one per restriction, because testing a batch means restricting all of its coefficients to zero. The **mean square**, SS divided by df, is variation per coefficient, which puts big and small batches on the same footing. And each $F$ statistic divides a batch's mean square by the residual mean square, asking how much more variation the batch carries than chance would produce for a batch of its size. If a batch's coefficients were all zero, its $F$ would be around 1. The observed values, 18.7 for days and 14.9 for persons, are far from 1, and the $p$-values are correspondingly small.\n\nBuild one habit immediately: compare mean squares, never raw sums of squares. Persons have the larger SS (251,000 against 166,000) but the smaller mean square, because the persons batch has 17 coefficients and the days batch 9. A sum of squares grows with the size of a batch; a mean square measures how strong a source of variation is.\n\n::: {.callout-tip icon=\"false\" title=\"Exercise 4.1\"}\nA one-way ANOVA of test scores across 4 schools (25 students each) gives between-groups SS = 1,200 and within-groups SS = 19,200. (a) Fill in the degrees of freedom, mean squares, and $F$. (b) What proportion of the variance do school differences account for? (c) Your colleague concludes from the significant $F$ that \"the schools differ a lot\". What is a better summary?\n:::\n\n::: {.callout-note collapse=\"true\" icon=\"false\" title=\"Answer 4.1\"}\n(a) df between $= 3$, within $= 96$; MS between $= 400$, within $= 200$; $F = 2.0$. (b) The proportion of variance is $1200/20400 \\approx 0.06$, about 6% (the ANOVA literature calls this ratio eta-squared; it has nothing to do with the $\\eta$ of @sec-theory-to-glm). (c) With $F = 2.0$ on (3, 96) df the evidence for any difference is weak ($p \\approx .12$), and even taking the estimates at face value the schools account for 6% of score variance. \"Differ a lot\" confuses a test statistic with an effect size; report the proportion of variance or the between-school standard deviation.\n:::\n\n## ANOVA is regression {#sec-anova-is-regression}\n\nThe first result can be checked in one line:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nanova(fit_lm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nResponse: Reaction\n           Df Sum Sq Mean Sq F value    Pr(>F)    \nDays        9 166235 18470.6  18.703 < 2.2e-16 ***\nSubject    17 250618 14742.2  14.928 < 2.2e-16 ***\nResiduals 153 151101   987.6                      \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nThis is the 27-coefficient regression again, summarized by `anova()`, and the table matches the `aov()` table number for number: same sums of squares, same $F$s. ANOVA and regression are one fit with two summaries. `summary(fit_lm)` prints every coefficient; `anova(fit_lm)` groups the coefficients into batches and reports the variation per batch.^[For balanced data, as here, the order of terms does not matter. In unbalanced data the sequential sums of squares depend on the order in which terms enter, a classical problem that the multilevel view below sidesteps.] The $F$ test also has a regression reading that applied papers use constantly: the $F$ for a batch compares the model with that batch's coefficients to the model without them. \"Does drinking improve the prediction of health, given everything else in the model?\" is settled by fitting both models and calling `anova(fit_without, fit_with)`. This is the regression version of the block test named in @sec-theory-to-glm: several restrictions tested at once, one degree of freedom each.\n\n## Batching coefficients: the multilevel step {#sec-batching}\n\nThe classical table summarizes the batches only after least squares has fit all 27 coefficients. The modern move builds the batching into the model itself. Seventeen person effects, viewed together, look like draws from a distribution: most people near the middle, a few fast, a few slow. So model them that way [@gelman2005; @gelmanhill2007]:\n\n$$\ny_{ij} = \\mu + \\beta_{d(j)} + u_i + \\varepsilon_{ij},\n\\qquad u_i \\sim N(0, \\sigma^2_{\\text{Subject}}),\n\\qquad \\varepsilon_{ij} \\sim N(0, \\sigma^2) .\n$$\n\nRead the second statement aloud as \"each $u_i$ is drawn from a normal distribution with mean 0 and standard deviation $\\sigma_{\\text{Subject}}$\"; the $\\sim$ sign means \"is distributed as\", and the same notation recurs throughout this chapter. The day effects $\\beta$ stay ordinary coefficients; the person effects $u_i$ now come from a normal distribution whose standard deviation is *estimated from the data*. The distribution does two things. The parameter of interest is no longer any single $u_i$ but $\\sigma_{\\text{Subject}}$: how much do people vary? And each person's estimate is **shrunk** toward the overall mean, by a factor computed below, most strongly for the people measured least, since an extreme average from a few noisy measurements is more plausibly noise than a real difference. The same idea returns as *shrinkage* in @sec-overfitting, where it is applied to regression coefficients. Gelman and Hill summarize the shift in one sentence: instead of testing whether a variance component is zero, estimate the standard deviation of the corresponding batch of coefficients. In R the model is `lmer()`, with `(1 | Subject)` read as \"an intercept per subject, batched\":\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit_lmer <- lmer(Reaction ~ Days + (1 | Subject), data = sleep)\nvc <- as.data.frame(VarCorr(fit_lmer))\ndata.frame(source = vc$grp, variance = round(vc$vcov, 1), sd = round(vc$sdcor, 2))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    source variance    sd\n1  Subject   1375.5 37.09\n2 Residual    987.6 31.43\n```\n\n\n:::\n:::\n\n\nTwo numbers summarize what seventeen coefficients could not: people vary with a standard deviation of about 37 ms, and the residual noise is about 31 ms. Set both against the largest day effect, 94 ms, and the three sources of variation are of the same order of magnitude: who you are matters about as much as how sleep-deprived you are. That comparison is the ANOVA of this dataset, stated more directly than an $F$ table can. The two variances also give the share of the variation that lies between persons, $1376/(1376 + 988) = 0.58$, called the **intraclass correlation**: it is the correlation between two measurements of the same person, and it appears in every multilevel paper as the first summary of how much the grouping matters.\n\nThe classical and multilevel approaches are connected, and for balanced data the connection is exact. The expected mean squares satisfy $E(\\text{MS}_{\\text{Subject}}) = \\sigma^2 + n\\,\\sigma^2_{\\text{Subject}}$ with $n = 10$ measurements per person, so the classical table implies\n\n$$\n\\hat\\sigma^2_{\\text{Subject}} = \\frac{\\text{MS}_{\\text{Subject}} - \\text{MS}_{\\text{Residual}}}{n}\n= \\frac{14742.24 - 987.59}{10} = 1375.5,\n$$\n\nwhich matches, to the decimal, the variance `lmer` just reported ($37.09^2 \\approx 1376$). The old $F$ table and the multilevel model estimate the same quantity; the multilevel model reports it directly, and it keeps working where the classical formulas do not: in unbalanced designs and in models with many batches or a binary outcome.\n\nThe shrinkage factor can now be computed too. A person's batched estimate is their observed deviation from the grand mean multiplied by\n\n$$\n\\lambda = \\frac{\\sigma^2_{\\text{Subject}}}{\\sigma^2_{\\text{Subject}} + \\sigma^2/n}\n= \\frac{1375.5}{1375.5 + 987.6/10} = 0.93,\n$$\n\nthe share of the variance of a person's mean that is real person difference rather than averaged noise. With ten measurements per person the shrinkage is mild: subject 309, whose mean is 83.3 ms below the grand mean, is placed 77.7 ms below it. With fewer measurements per person, $\\sigma^2/n$ grows and $\\lambda$ falls, which is the precise form of \"most strongly for the people measured least\". Exercise 4.E derives the factor.\n\n::: {.callout-tip icon=\"false\" title=\"Exercise 4.2\"}\nThis exercise uses R; `fit_lmer` and `vc` are the objects above. (a) Compute $\\lambda$ from `vc$vcov` with $n = 10$ and check it against the text. (b) Subject 309's mean reaction time is 83.3 ms below the grand mean (`mean(sleep$Reaction)` is 298.5; check the subject mean with `tapply`). Predict what `ranef(fit_lmer)$Subject[\"309\", ]` will print before you run it, then run it. (c) What would $\\lambda$ be for a subject measured on only two days, and what does that say about whom shrinkage affects most?\n:::\n\n::: {.callout-note collapse=\"true\" icon=\"false\" title=\"Answer 4.2\"}\n(a) `vc$vcov[1] / (vc$vcov[1] + vc$vcov[2] / 10)` gives $1375.5/(1375.5 + 98.8) = 0.933$. (b) $0.933 \\times (-83.3) = -77.7$, which is what `ranef` prints; every subject's batched deviation is their observed deviation times the same $0.933$, because everyone was measured ten times. (c) $1375.5/(1375.5 + 493.8) = 0.74$: a quarter of the way back to the mean rather than 7%. The less a unit is measured, the more it is shrunk, which is the sentence in the text in numbers.\n:::\n\n::: {.callout-tip icon=\"false\" title=\"Exercise 4.3\"}\n(a) In the model above, what would $\\sigma_{\\text{Subject}} = 0$ mean substantively, and which classical hypothesis does it correspond to? (b) A colleague fits the same data with 17 subject dummies and reports subject 310's coefficient with a confidence interval. You fit `lmer` and report $\\sigma_{\\text{Subject}}$ with an interval. Describe one research goal for which each output is the right one.\n:::\n\n::: {.callout-note collapse=\"true\" icon=\"false\" title=\"Answer 4.3\"}\n(a) People do not differ in baseline reaction time; all variation is noise and day effects. It corresponds to the classical $F$ test of the Subject batch (all subject coefficients zero). (b) The dummies answer questions about *these* people, as when subject 310 is a patient being monitored or a machine being audited. The batch SD answers questions about people in general, as when planning how large future studies must be, or comparing person variation with treatment effects. The choice previews the fixed-versus-random question below.\n:::\n\n## The Bayesian version and the ANOVA display {#sec-bayesian-anova}\n\nEvery batch SD is a parameter we are uncertain about, the classical table never shows that uncertainty, and so the next step is a Bayesian treatment of the multilevel model.^[There is also a practical reason: when a batch has few levels or its SD sits near zero, the likelihood-based point estimate often collapses to exactly zero, hiding real but modest variation. A posterior distribution reports how uncertain the SD is rather than a false certainty [@gelman2005].] The words that this involves are defined in @def-bayes.\n\n::: {#def-bayes}\n## Prior, posterior, and MCMC\nA Bayesian analysis treats each parameter as an uncertain quantity that has a probability distribution. Before the data are seen, that distribution is the **prior**, which says which values are plausible on the basis of what was known beforehand; the analysis below uses the software's default priors, vague enough to let the data decide. The likelihood (@def-likelihood) is the same as in a classical analysis, and Bayes' rule combines prior and likelihood into the **posterior**, the distribution of the parameter given the data, which says which values are plausible now. For a model like this one the posterior cannot be written down in closed form, so the software draws thousands of random values from it by simulation, a method called **Markov chain Monte Carlo** (MCMC), and everything reported is a summary of those draws: the mean or median of the draws is the estimate, and the 95% interval is the range that holds 95% of them, which, unlike a confidence interval, may be read as \"the parameter is probably in here\". @sec-unsupervised uses the same word, posterior, for the probability that a person belongs to a latent class; the logic is the same, applied to a discrete unknown.\n:::\n\nThe brms package [@burkner2017] fits the same model by MCMC with one changed function name. In the call, `chains = 4` runs four independent simulations, `iter = 2000` makes 2,000 draws in each, and `warmup = 1000` discards the first 1,000 of those, made while the simulation is still finding the region of plausible values; the remaining 4,000 draws are the posterior sample:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(brms)\nfit_brm <- brm(Reaction ~ Days + (1 | Subject), data = sleep,\n               chains = 4, iter = 2000, warmup = 1000, seed = 1234,\n               refresh = 0, silent = 2)\nfit_brm2 <- brm(Reaction ~ (1 | Days) + (1 | Subject), data = sleep,\n                chains = 4, iter = 2000, warmup = 1000, seed = 1234,\n                refresh = 0, silent = 2)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nround(summary(fit_brm)$random$Subject[, 1:4], 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n              Estimate Est.Error l-95% CI u-95% CI\nsd(Intercept)     39.1       7.4     27.3     56.8\n```\n\n\n:::\n:::\n\n\nThe posterior for $\\sigma_{\\text{Subject}}$ centres near 40 ms with a 95% interval running from roughly 28 to 57: people definitely differ, by an amount known only to within a factor of two. The second model, `fit_brm2`, batches *both* factors, days as well as subjects, so that every row of the old ANOVA table becomes an estimated standard deviation:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlapply(summary(fit_brm2)$random, function(r) round(r[, 1:4], 1))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$Days\n              Estimate Est.Error l-95% CI u-95% CI\nsd(Intercept)       35       9.8     21.3     60.3\n\n$Subject\n              Estimate Est.Error l-95% CI u-95% CI\nsd(Intercept)     39.5       7.8     27.1     57.4\n```\n\n\n:::\n\n```{.r .cell-code}\nround(summary(fit_brm2)$spec_pars[, 1:4], 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      Estimate Est.Error l-95% CI u-95% CI\nsigma     31.7       1.8     28.3     35.4\n```\n\n\n:::\n:::\n\n\nThe day batch has an SD of about 35 ms and the subject batch about 39 ms, each with a wide interval, and the residual SD is about 32 ms. Plot the posteriors of the batch SDs side by side and you get @fig-anova-display, what @gelman2005 proposed as the modern replacement for the $F$ table:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggdist); library(dplyr); library(tidyr); library(ggplot2)\nposterior::as_draws_df(fit_brm2) |>\n  select(starts_with(\"sd_\"), sigma) |>\n  pivot_longer(everything()) |>\n  mutate(name = recode(name,\n    \"sd_Days__Intercept\" = \"Days\",\n    \"sd_Subject__Intercept\" = \"Subjects\",\n    \"sigma\" = \"Residual\")) |>\n  ggplot(aes(x = value, y = name)) +\n  stat_halfeye() +\n  labs(x = \"standard deviation (ms)\", y = NULL) +\n  xlim(0, 100) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![An ANOVA display: posterior distributions of the batch standard deviations (points: medians; bars: 50% and 95% intervals) and the residual SD, in milliseconds. Larger SD means that source contributes more variation to reaction times.](04-anova_files/figure-pdf/fig-anova-display-1.png){#fig-anova-display fig-pos='H'}\n:::\n:::\n\n\nThe pipeline collects the posterior draws, keeps the columns that hold the batch standard deviations and the residual SD, relabels them, and draws one density per row, with the median and the intervals marked underneath it (a \"half-eye\" plot). Read the display as the answer to \"where does the variation come from?\": days and subjects each contribute variation on the order of 30 to 40 ms around their means, comparable to the residual noise.^[The Days SD summarizes the spread of the ten day means; it does not show that the day effects are steadily *increasing*, which the coefficients themselves reveal.] This picture answers the question the classical table is usually misread as answering: sums of squares cannot be compared across rows, and mean squares only indirectly, but the batch SDs compare directly, with their uncertainty on display.\n\n## Fixed or random: decide by the goal {#sec-fixed-or-random}\n\nThe person effects above are called **random effects**, the day coefficients **fixed effects**, and the terminology is a common source of confusion. @gelman2005 collects five incompatible definitions of the pair from the literature and shows that they contradict each other in ordinary datasets; his advice is to drop the words and say *constant* versus *varying* coefficients. Constant and varying are alternative names for the same pair; this book uses fixed and random from here on, because that is what the literature the reader will meet uses. Whatever the words, the decision remains and turns on the inferential goal:\n\n> Model a batch with dummies (\"fixed\") when the levels in the data are the whole story and you want to control for or estimate *these particular* levels. Model a batch with a distribution (\"random\") when the levels stand in for a larger population you care about, so the target is the population's variation, or a prediction for a level you have not seen.\n\nFour versions of the same decision come up constantly in real research, summarized in @tbl-fixed-random. Repeated measurements of the same panel respondents, where the goal is to control for all stable person characteristics with no wish to generalize to other people: person dummies, fixed, because these persons stand in for no larger population. Each respondent rated by three interviewers drawn from a large interviewer pool: random, because the interviewers stand in for interviewers in general and their variation is itself of interest. Had the goal been only to net out these three interviewers, dummies would have sufficed; only the question differs. Survey respondents nested in 24 countries, where the goal is to generalize to all countries: random, because the question is about the population of countries. And thirteen historical studies of a vaccine, where the goal is to predict what a new study would find: random, a case so common that it has its own name, meta-analysis.\n\n| Batch | Goal | The levels stand for | Choice |\n|---|---|---|---|\n| Persons in a panel | Control for everything stable about each person | Nobody but themselves | Fixed: person dummies |\n| Interviewers from a pool | How much do interviewers matter? | Interviewers in general | Random: $\\sigma_{\\text{Interviewer}}$ |\n| 24 countries | Generalize to all countries | The population of countries | Random: $\\sigma_{\\text{Country}}$ |\n| 13 vaccine trials | Predict what a new trial would find | Trials in other settings | Random: meta-analysis |\n\n: Four versions of the fixed-or-random decision, decided by the goal. {#tbl-fixed-random}\n\nThe first row may seem to contradict @sec-batching, where the sleep study's persons, also measured repeatedly, were batched. Both are right. In the sleep study, persons were batched because $\\sigma_{\\text{Subject}}$ was a quantity of interest, and every person saw every day, so the person effects cannot be correlated with the day effects. A panel analysis that only wants to *remove* person differences, such as the crossover design of @sec-rq-to-interpretation with its person effect $\\alpha_i$, uses dummies, and it needs them when what a person received depends on who the person is.\n\nThat last clause is the econometric rule for the same decision, and readers who have met it should see how it relates to the goal-based rule. In econometrics the choice is made by asking whether the group effects $u_i$ are correlated with the other predictors: modelling $u_i$ as draws from a distribution assumes that they are not, whereas a dummy per group absorbs any such correlation, so if the correlation exists the random-effects estimate of the predictor's coefficient is biased and the fixed-effects (within-group) estimate is not; the Hausman test [@hausman1978] compares the two estimates to detect it. @mundlak1978 showed how to have both: add the group means of the predictors to the random-effects model, and its estimate of the within-group effect equals the fixed-effects estimate, while the model still reports $\\sigma_u$ and still shrinks the group effects [@bell2015]. So the two rules answer different questions. Whether the group effects are correlated with the predictors decides what goes into the model as predictors; the goal decides what you report, a variance or particular levels; and a random-effects model with group means as predictors satisfies both.\n\n::: {.callout-tip icon=\"false\" title=\"Exercise 4.4\"}\nChoose fixed or random, and justify from the goal, for each: (a) hospital effects, in a study auditing which of the country's 8 academic hospitals have excess mortality; (b) school effects, in a study of how much schools in general differ in value-added; (c) year effects for 2015 to 2024, controlling for macroeconomic shocks in a wage analysis; (d) word effects, in a psycholinguistic experiment where 60 words were sampled from the dictionary to represent \"concrete nouns\".\n:::\n\n::: {.callout-note collapse=\"true\" icon=\"false\" title=\"Answer 4.4\"}\n(a) Fixed: the 8 hospitals are the complete population of interest, and the goal is estimates for each one by name. (b) Random: schools stand in for schools in general and the target is their variation, $\\sigma_{\\text{School}}$. (c) Fixed: the years are these years, included as controls, with no population of years to generalize to. (d) Random: the words are a sample from a larger population of possible stimuli, and treating them as fixed would license conclusions only about these 60 words, a classic error in that field.\n:::\n\n## Meta-analysis: batching study effects {#sec-meta-analysis}\n\nThe batching idea has a famous application in which the \"units\" are entire studies. Between 1948 and 1980, thirteen trials on several continents tested whether the BCG vaccine protects against tuberculosis [@colditz1994]. Each study $i$ reports an effect estimate $y_i$, here a log odds ratio as in @sec-theory-to-glm, together with its standard error $\\sigma_i$, which the meta-analysis takes as known; it says how noisy each estimate is:\n\n$$\ny_i \\sim N(\\theta_i, \\sigma_i^2),\n$$\n\nwhere $\\theta_i$ is the true effect *in study $i$'s setting*. This is a meta-analysis: the data are estimates. Thirteen $\\theta_i$ form a batch of coefficients. We can force them to be identical, $\\theta_i = \\theta$ for all $i$, the **fixed-effects** (equal-effects) model, or we can batch them, $\\theta_i \\sim N(\\mu, \\tau^2)$, the **random-effects** model, in which studies have genuinely different true effects that vary with standard deviation $\\tau$. The metafor package fits both; `method = \"REML\"` is restricted maximum likelihood, a variant of maximum likelihood (@def-likelihood) that estimates variance components without the downward bias that plain maximum likelihood has in small samples, and `lmer()` used it too:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(metafor)\nbcg <- data.frame(\n  author = c(\"Aronson\", \"Ferguson & Simes\", \"Stein & Aronson\",\n             \"Rosenthal et al\", \"Rosenthal et al\", \"Coetzee & Berjak\",\n             \"Comstock & Webster\", \"Frimodt-Moller et al\", \"Vandiviere et al\",\n             \"Comstock et al\", \"Comstock et al\", \"Hart & Sutherland\",\n             \"TPT Madras\"),\n  year  = c(1948, 1949, 1953, 1960, 1961, 1968, 1969,\n            1973, 1973, 1974, 1976, 1977, 1980),\n  alloc = c(\"random\", \"random\", \"alternate\", \"random\", \"systematic\",\n            \"random\", \"systematic\", \"alternate\", \"random\", \"systematic\",\n            \"systematic\", \"random\", \"random\"),\n  yi  = c(-0.94, -1.67, -0.96, -1.39, -1.40, -0.47, 0.45,\n          -0.22, -1.63, -0.34, -0.02, -1.46, 0.01),\n  sei = c(0.598, 0.456, 0.100, 0.658, 0.275, 0.239, 0.731,\n          0.228, 0.476, 0.112, 0.268, 0.143, 0.063))\nfe <- rma(yi, sei = sei, data = bcg, method = \"FE\")\nre <- rma(yi, sei = sei, data = bcg, method = \"REML\")\nround(c(fixed = coef(fe), se = fe$se, random = coef(re), se = re$se,\n        tau = sqrt(re$tau2)), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n fixed.intrcpt             se random.intrcpt             se            tau \n        -0.434          0.042         -0.746          0.186          0.581 \n```\n\n\n:::\n:::\n\n\nInterpret the estimates first. Both are negative: the vaccine protects. The fixed-effects estimate, $-0.434$, says the common log odds ratio cuts the odds of tuberculosis by about a third ($e^{-0.43} \\approx 0.65$); the random-effects estimate, $-0.746$, says the *average* study effect cuts them by half, with individual studies varying around that average with $\\hat\\tau = 0.58$, a spread as large as the average effect itself. The two models answer different questions: \"what is the one common effect?\" versus \"what is the distribution of effects across settings?\".\n\nThe random-effects model fits this problem better. Substantively, thirteen studies spanning four decades, several continents, and three allocation methods can hardly share one true effect; BCG's efficacy is known to vary with latitude, among other things. Statistically the data agree. AIC is a fit measure that penalizes parameters, lower being better (defined in @sec-unsupervised); it is computed from the log-likelihood, so both models must be fitted by the same kind of likelihood for the comparison to be fair, which means refitting the random-effects model by plain maximum likelihood:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nre_ml <- rma(yi, sei = sei, data = bcg, method = \"ML\")\nround(c(AIC_fixed = AIC(fe), AIC_random = AIC(re_ml)), 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n AIC_fixed AIC_random \n     154.0       30.2 \n```\n\n\n:::\n:::\n\n\nThe score is 154 for fixed against 30 for random. The choice has visible consequences: the random-effects standard error (0.186) is more than four times the fixed-effects one (0.042). The larger standard error is not a flaw. The fixed-effects analysis, by *assuming* all studies estimate the same number, treats 13 studies as one big sample and reports a precision that is real only if the assumption is; the random-effects analysis admits between-study variation as an extra source of uncertainty, because with heterogeneous true effects, seeing 13 of them still leaves you unsure about the average over all possible settings.\n\nThere are two further extensions. First, heterogeneity can be explained: the studies differ in year and in how patients were allocated (randomized, alternated, or physician-selected), and regressing the $\\theta_i$ on such study characteristics is called **meta-regression**, ordinary regression one level up. Second, the random-effects model can predict: ask what a new study in a new setting would find and it answers $\\theta_{\\text{new}} \\sim N(\\hat\\mu, \\hat\\tau^2 + \\text{SE}(\\hat\\mu)^2)$, a new draw from the batch plus the uncertainty about where the batch is centred. Here that is a standard deviation of $\\sqrt{0.338 + 0.186^2} = 0.61$ around $-0.746$, a 95% prediction interval from $-1.94$ to $0.45$ on the log-odds scale, or an odds ratio between 0.14 and 1.57: from strong protection to mild harm, a wide interval that the fixed-effects model, with its single $\\theta$, cannot formulate. Prediction returns in @sec-explanation-prediction.\n\n::: {.callout-tip icon=\"false\" title=\"Exercise 4.5\"}\n(a) Write down the random-effects model for the $\\theta_i$ in one line, defining each symbol. (b) Explain conceptually, without formulas, why the random-effects standard error is larger than the fixed-effects one. (c) Study 13 (Madras, 1980, $y_i = 0.01$, the largest trial, $\\sigma_i = 0.063$) found no protection. Under each model, what do you make of it?\n:::\n\n::: {.callout-note collapse=\"true\" icon=\"false\" title=\"Answer 4.5\"}\n(a) $\\theta_i \\sim N(\\mu, \\tau^2)$: study-specific true effects $\\theta_i$ scatter around a grand mean $\\mu$ with between-study standard deviation $\\tau$. (b) The fixed-effects model assumes every study measures the same quantity, so all data pool into one precise estimate; the random-effects model adds real between-study variation to the uncertainty, since even perfectly measured studies would disagree, and the average of a varying quantity is harder to pin down. (c) Under the fixed-effects model Madras is a problem: the most precise study contradicts the common effect, which is evidence against the model itself. Under the random-effects model Madras is a low-$\\theta_i$ setting, informative about $\\tau$ and expected given $\\hat\\tau = 0.58$; the model invites the follow-up question *why* (climate, strain, population), which meta-regression pursues.\n:::\n\n## Where the batching idea leads {#sec-batching-leads}\n\nThe sequence in this chapter, from dummies to batches to batch distributions to distributions of study effects, leads into multilevel modelling, one of the main tools of modern social and health research. It generalizes: batches of slopes rather than intercepts (Exercise 4.D), batches in logistic regressions, crossed batches (persons and stimuli), batches of batches. The idea never changes: group the coefficients and make each batch's variation the target, choosing dummies or distributions by what you want to generalize to. The next chapter changes direction: after four chapters of models whose parameters we interpret, we ask what it means for a model to predict, and why anyone would want a model whose parameters they never interpret at all.\n\n## What to carry forward {.unnumbered}\n\nA regression with a categorical predictor produces one coefficient per level, and ANOVA summarizes each batch of coefficients by the variation it accounts for, in sums of squares, mean squares and an $F$ statistic; the $F$ for a batch is the block test of @sec-theory-to-glm in regression form, and mean squares, not sums of squares, are what to compare (@sec-sums-of-squares, @sec-anova-is-regression). A multilevel model builds the batching into the model by treating the batch as draws from a normal distribution whose standard deviation is estimated, which replaces seventeen coefficients by $\\sigma_{\\text{Subject}}$, shrinks each level's estimate toward the mean by the factor $\\lambda$, and gives the intraclass correlation as the share of variation between groups; @sec-overfitting reuses shrinkage and @sec-evaluation reuses the grouping when it splits data (@sec-batching). The Bayesian version reports each batch standard deviation as a posterior distribution, and the vocabulary of prior, posterior and MCMC in @def-bayes is what @sec-unsupervised uses for posterior class membership (@sec-bayesian-anova). Fixed or random is decided by the goal, particular levels or a population's variation, and the econometric question of whether group effects are correlated with the predictors is a separate question with its own fix (@sec-fixed-or-random). Meta-analysis is the same model with studies as the units, and its random-effects version is the first model in this book that makes a prediction, for a study not yet run, which @sec-explanation-prediction and @sec-overfitting take up (@sec-meta-analysis).\n\n**Terms and symbols introduced.** analysis of variance; batch; sum of squares; mean square; degrees of freedom of a batch; intraclass correlation; shrinkage; multilevel model; restricted maximum likelihood (REML); prior, posterior, Markov chain Monte Carlo; fixed effects and random effects (constant and varying coefficients); Hausman test; Mundlak's group means; meta-analysis, fixed-effects and random-effects meta-analysis, meta-regression; AIC; $y_{ij}$ measurement $j$ of unit $i$, $\\bar y_i$ and $\\bar y$ the unit mean and the grand mean, $F$ the ratio of mean squares, $u_i$ a unit's random effect, $\\sigma^2_{\\text{Subject}}$ and $\\sigma^2$ the between-unit and residual variances, $\\lambda$ the shrinkage factor, $\\theta_i$ a study's true effect, $\\sigma_i$ its reported standard error, $\\mu$ and $\\tau^2$ the mean and variance of the study effects.\n\n**Exercises that use R.** 4.2 (the shrinkage factor and `ranef()` from the `lmer` fit); 4.D (a random slope for days).\n\n## Further study {.unnumbered}\n\n@gelman2005 is the paper this chapter follows: it makes the case that ANOVA is about batches of coefficients and introduces the ANOVA display of batch standard deviations. @gelmanhill2007 is the applied book to read next on multilevel models, with the sleep-study kind of analysis worked through in R and much advice on when to batch. @snijders2012 is the standard textbook for the social-science multilevel model, including random slopes, the intraclass correlation and the design questions of Exercise 4.C. @bell2015 sets out the fixed-versus-random debate between econometrics and multilevel modelling and explains the within–between formulation that reconciles them. @borenstein2009 is a readable introduction to meta-analysis, and @viechtbauer2010 documents the metafor package used here, with the BCG data as its running example. @burkner2017 describes brms, the package that fitted the Bayesian models.\n\n## Test yourself {.unnumbered}\n\n::: {.callout-tip icon=\"false\" title=\"Exercise 4.A\"}\n@tbl-bcg lists the 13 BCG studies: log odds ratios $y_i$, standard errors $\\sigma_i$, the year, and how patients were allocated (at random, by alternating as they arrived, or systematically, for example by a clinician's judgement). Output for the fixed-effects model: estimate $-0.434$ (SE 0.042). For the random-effects model: estimate $-0.746$ (SE 0.186), $\\hat\\tau^2 = 0.34$.\n\n| Study | Author | Year | $y_i$ | $\\sigma_i$ | Allocation |\n|---|---|---|---|---|---|\n| 1 | Aronson | 1948 | −0.94 | 0.598 | random |\n| 2 | Ferguson & Simes | 1949 | −1.67 | 0.456 | random |\n| 3 | Stein & Aronson | 1953 | −0.96 | 0.100 | alternate |\n| 4 | Rosenthal et al. | 1960 | −1.39 | 0.658 | random |\n| 5 | Rosenthal et al. | 1961 | −1.40 | 0.275 | systematic |\n| 6 | Coetzee & Berjak | 1968 | −0.47 | 0.239 | random |\n| 7 | Comstock & Webster | 1969 | 0.45 | 0.731 | systematic |\n| 8 | Frimodt-Moller et al. | 1973 | −0.22 | 0.228 | alternate |\n| 9 | Vandiviere et al. | 1973 | −1.63 | 0.476 | random |\n| 10 | Comstock et al. | 1974 | −0.34 | 0.112 | systematic |\n| 11 | Comstock et al. | 1976 | −0.02 | 0.268 | systematic |\n| 12 | Hart & Sutherland | 1977 | −1.46 | 0.143 | random |\n| 13 | TPT Madras | 1980 | 0.01 | 0.063 | random |\n\n: The thirteen BCG vaccine trials [@colditz1994]. {#tbl-bcg}\n\n(a) Interpret both estimates on the odds scale.\n(b) Which model do you find more appropriate here? Give one substantive and one data-fit argument.\n(c) Using $\\hat\\mu = -0.746$, SE 0.186 and $\\hat\\tau^2 = 0.34$, compute a 95% prediction interval for the log odds ratio in a new trial by hand, and convert it to the odds scale. Which of the two variance components dominates? (If you have `re` from the text, `predict(re)` checks your answer.)\n(d) Suppose the goal is to predict the log odds ratio $\\theta'$ in a newly planned trial. Explain why the random-effects model is the natural tool, and what two quantities determine the width of the prediction.\n(e) Do you think allocation method or study year matter here? How would you incorporate them?\n:::\n\n::: {.callout-note collapse=\"true\" icon=\"false\" title=\"Answer 4.A\"}\n(a) Fixed: one common effect, odds of tuberculosis multiplied by $e^{-0.434} \\approx 0.65$, a 35% reduction. Random: the average of the study-specific effects multiplies the odds by $e^{-0.746} \\approx 0.47$, about a halving, with true effects varying around this average ($\\tau \\approx 0.58$). (b) Substantive: studies span 1948-1980, several continents, and three allocation methods; one shared true effect is implausible, and BCG efficacy is known to vary by setting. Fit: with both models fitted by maximum likelihood, AIC favours the random-effects model overwhelmingly (about 154 versus 30). (c) Variance $0.34 + 0.186^2 = 0.373$, SD $0.61$; interval $-0.746 \\pm 1.96 \\times 0.61 = (-1.94, 0.45)$; on the odds scale $e^{-1.94} = 0.14$ to $e^{0.45} = 1.57$, from strong protection to mild harm. The between-study variance ($0.34$) dominates the uncertainty about the mean ($0.186^2 = 0.035$) by a factor of ten. (d) A new trial is a new draw from the batch: $\\theta' \\sim N(\\hat\\mu, \\hat\\tau^2)$, plus the uncertainty in $\\hat\\mu$ itself; the prediction's width is driven by $\\hat\\tau$ (between-study variation) and by the standard error of $\\hat\\mu$, as (c) computed. (e) Plausibly: nonrandomized allocation may exaggerate effects, and efficacy may drift over time; incorporate them by meta-regression, regressing the study effects on allocation type and year, and see whether $\\tau$ shrinks.\n:::\n\n::: {.callout-tip icon=\"false\" title=\"Exercise 4.B\"}\nA colleague analyses the sleep data with `lm(Reaction ~ Days + Subject)` and, separately, with `lmer(Reaction ~ Days + (1|Subject))`, and is puzzled: \"the Days coefficients are the same in both, so what did the multilevel model buy me?\"\n\n(a) Explain why the Days coefficients (and their standard errors) agree here.\n(b) Name two things the multilevel output provides that the dummy regression does not.\n(c) Describe a version of this study, with a different design or goal, where the two analyses would give importantly different answers, and say which you would trust.\n:::\n\n::: {.callout-note collapse=\"true\" icon=\"false\" title=\"Answer 4.B\"}\n(a) The design is balanced: every person is measured on every day, so person differences cancel out of the day contrasts, and both models estimate the same within-person comparisons. The standard errors agree because in both models the precision of a day contrast depends only on the within-person residual variance, and both estimate that variance from the same residuals. (b) The batch standard deviation $\\sigma_{\\text{Subject}}$ with its uncertainty (the answer to \"how much do people differ?\"), and sensible predictions for new persons; also shrunken person-level estimates rather than 17 noisy dummies. (c) Unbalanced data, for instance if slower subjects dropped out on later days, or a goal involving generalization, such as predicting reaction times for new recruits. With imbalance the dummy regression's day contrasts lean on the observed persons in an uncontrolled way, while the multilevel model weighs information by its precision; for generalization the batch distribution is the only defensible tool.\n:::\n\n::: {.callout-tip icon=\"false\" title=\"Exercise 4.C\"}\nAn education researcher studies grading strictness. Each of 2,000 essays is graded by 3 of the university's 40 graders; essays are also scored by a text-analysis algorithm as a benchmark.\n\n(a) Write a model for the grade of essay $e$ by grader $x$, batching what should be batched, and define each term.\n(b) The department head wants to know whether grader 17, up for promotion, grades too strictly. The dean wants to know whether grader differences are large enough to justify double grading in general. Which output answers each question, and why are they different questions?\n(c) The variance components come out as: essays 60%, graders 8%, residual 32% of the total. Draft the one-sentence summary you would give the dean.\n:::\n\n::: {.callout-note collapse=\"true\" icon=\"false\" title=\"Answer 4.C\"}\n(a) $g_{ex} = \\mu + \\beta\\, s_e + u_e + v_x + \\varepsilon_{ex}$, with $s_e$ the algorithm score (fixed coefficient), $u_e \\sim N(0, \\sigma^2_{\\text{essay}})$ essay quality beyond the algorithm, $v_x \\sim N(0, \\sigma^2_{\\text{grader}})$ grader strictness, and $\\varepsilon_{ex}$ the noise of one grader reading one essay. (b) Grader 17's question is about a particular level: their (shrunken) $v_{17}$ with an interval, or a fixed-effect estimate for that grader. The dean's question is about the batch: $\\sigma_{\\text{grader}}$, compared with the other components. One asks about a coefficient, the other about a variance. (c) \"Graders differ systematically, but their strictness accounts for about 8% of grade variation (the intraclass correlation for graders), small relative to genuine essay differences (60%) and to the noise of any single reading (32%), which argues more for a second reading of borderline essays than for double-grading everything.\"\n:::\n\n::: {.callout-tip icon=\"false\" title=\"Exercise 4.D\"}\nThis exercise uses R. The model in the text gives every person the same day effects; only the intercepts vary. Treat `Days` as a number and let the slope vary as well:\n\n```r\nfit_slopes <- lmer(Reaction ~ Days + (Days | Subject),\n                   data = sleepstudy)\nas.data.frame(VarCorr(fit_slopes))\nfixef(fit_slopes)\n```\n\nReport the SD of the intercepts, the SD of the slopes and the average slope, and write one sentence for a journal on how much people differ in their *response* to sleep deprivation.\n:::\n\n::: {.callout-note collapse=\"true\" icon=\"false\" title=\"Answer 4.D\"}\nIntercept SD 24.7 ms, slope SD 5.9 ms per day, average slope 10.5 ms per day (the third row of the `VarCorr` table is the covariance between intercepts and slopes, here close to zero). The slope batch has an SD more than half its mean, so a person within two SDs of the average slows by anywhere from about 0 to 22 ms per day: individual differences in vulnerability to sleep loss are as large as the average effect, a question the common-slope model of the text assumed away.\n:::\n\n::: {.callout-tip icon=\"false\" title=\"Exercise 4.E (optional)\"}\nThis last exercise is optional: it asks for the derivations behind two numbers in the text, and it is more challenging than the others. Nothing later in the book depends on it, but the first part is the calculation that @sec-overfitting reuses.\n\n(a) Derive the shrinkage factor. Under the model $\\bar y_i = \\mu + u_i + \\bar\\varepsilon_i$ with $u_i \\sim N(0, \\sigma^2_u)$ and $\\bar\\varepsilon_i \\sim N(0, \\sigma^2/n)$ independent, show that $E(u_i \\mid \\bar y_i) = \\lambda(\\bar y_i - \\mu)$ with $\\lambda = \\sigma^2_u/(\\sigma^2_u + \\sigma^2/n)$. Hint: for jointly normal variables, $E(u \\mid \\bar y) = \\operatorname{Cov}(u, \\bar y)\\,\\operatorname{Var}(\\bar y)^{-1}(\\bar y - E\\bar y)$; the same fact drives the calculation of $E(U \\mid X_1)$ in @sec-overfitting.\n(b) Show that $E(\\text{MS}_{\\text{Subject}}) = \\sigma^2 + n\\sigma^2_u$ for balanced data with $I$ persons and $n$ measurements each, where $\\text{MS}_{\\text{Subject}} = n\\sum_i (\\bar y_i - \\bar y)^2/(I - 1)$.\n:::\n\n::: {.callout-note collapse=\"true\" icon=\"false\" title=\"Answer 4.E\"}\n(a) $\\operatorname{Cov}(u_i, \\bar y_i) = \\operatorname{Cov}(u_i, \\mu + u_i + \\bar\\varepsilon_i) = \\sigma^2_u$ and $\\operatorname{Var}(\\bar y_i) = \\sigma^2_u + \\sigma^2/n$, so the ratio is $\\lambda$, and $E\\bar y_i = \\mu$. In the sleep study $\\mu$ is replaced by the grand mean and the variances by their estimates, which gives the $0.93$ of the text.\n(b) $\\bar y_i - \\bar y = (u_i - \\bar u) + (\\bar\\varepsilon_i - \\bar\\varepsilon)$, where $\\bar u$ and $\\bar\\varepsilon$ average over the $I$ persons. Each of the two pieces is a deviation from a mean of $I$ independent draws, so $\\operatorname{Var}(\\bar y_i - \\bar y) = (1 - 1/I)(\\sigma^2_u + \\sigma^2/n)$, and summing over $i$ gives $E\\sum_i (\\bar y_i - \\bar y)^2 = (I - 1)(\\sigma^2_u + \\sigma^2/n)$. Multiplying by $n/(I - 1)$ gives $E(\\text{MS}_{\\text{Subject}}) = n\\sigma^2_u + \\sigma^2$, which is why $(\\text{MS}_{\\text{Subject}} - \\text{MS}_{\\text{Residual}})/n$ estimates $\\sigma^2_u$.\n:::\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{},\"value\":[]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}