{
  "hash": "6f8b080eaa48b70f742567f5df68500e",
  "result": {
    "engine": "knitr",
    "markdown": "# Machine learning without a teacher: clustering and mixture models {#sec-unsupervised}\n\nThe machine learning of the last three chapters was **supervised**: every observation in the experience carried the outcome, the recorded outcomes supervised the fit, and the performance measure compared predictions against outcomes the model had not seen. This chapter removes the supervisor. In **unsupervised learning** there is no outcome variable: the data are a set of observations on some features, and the task is to find structure among them, most commonly *groups* of observations that resemble each other. Return to Mitchell's definition from @sec-overfitting and notice what breaks. The task and the experience survive: find groups, using these data. The performance measure does not, because there is no recorded outcome against which a proposed grouping can be scored. The judge that chapters 6 and 7 relied on has left the room, and the central question of this chapter is what to do about that.\n\nSocial and health scientists want hidden groups for several recurring reasons. Sometimes the variable of real interest was never measured, but other variables carry information about it: how students answer exam questions is indicative of whether they have mastered the material, and how a chat partner responds is indicative of whether they are human or a bot. Sometimes an effect is suspected to differ between kinds of people, without the kinds being directly observed. And sometimes there are simply too many variables to interpret, and the analyst wants to reduce them to a few interpretable groups, as marketing does when it builds \"segments\". The techniques of this chapter serve all three purposes, and they come in two families that the chapter treats in turn: **clustering algorithms**, which group observations by their distances to each other, and **mixture models**, which posit an explicit statistical model in which an unobserved, discrete variable produces the groups.\n\n## Two kinds of eruption\n\nThe Old Faithful geyser in Yellowstone erupts every 35 to 120 minutes, and each eruption lasts between one and five minutes. The `faithful` dataset records 272 eruptions on two features: the duration of the eruption and the waiting time since the previous one. @fig-faithful plots them.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(faithful$eruptions, faithful$waiting,\n     xlab = \"eruption duration (min)\", ylab = \"waiting time (min)\")\n```\n\n::: {.cell-output-display}\n![Old Faithful: duration of 272 eruptions against the waiting time since the previous eruption. Two kinds of eruption suggest themselves: short ones after a short wait, and long ones after a long wait.](08-unsupervised-clustering-mixtures_files/figure-pdf/fig-faithful-1.png){#fig-faithful fig-pos='H'}\n:::\n:::\n\n\nNobody labelled these eruptions, yet the picture shows two groups: short eruptions after short waits, and long eruptions after long waits. The eye performs unsupervised learning effortlessly in two dimensions. The methods of this chapter exist because real problems have ten or a thousand dimensions, where the eye fails, and because even in two dimensions the eye cannot say *how many* groups there are when the picture is less obliging than this one.\n\n## Clustering by distance\n\nThe algorithmic family starts from a simple idea: a cluster is a set of observations that are close together, so the raw material is the **distance** between every pair of observations. For continuous features the default is Euclidean distance, the ordinary straight-line distance in feature space, but the choice matters and is wider than it first appears. Before any distance is computed, the features should usually be put on a comparable scale, typically by **standardization**: subtracting each feature's mean and dividing by its standard deviation. Otherwise a feature measured in centimetres contributes a hundred times more to the distance than the same information measured in metres, and the clustering quietly becomes a clustering on whichever feature has the largest numbers. And beyond continuous features, distances have been defined for almost any kind of object: edit distance for text and DNA sequences, dynamic time warping and Fréchet distance for time series and curves, shortest-path distances for networks. Any method that accepts a distance matrix can therefore cluster any kind of object for which a distance can be defined, which is a large part of clustering's flexibility.\n\n**Hierarchical clustering** uses the distance matrix directly. The agglomerative version starts with every observation as its own cluster, repeatedly merges the two most similar clusters, and stops when only one cluster remains; the analyst then chooses the number of clusters afterwards, by cutting the resulting tree at some height. How similar two *clusters* are, given the distances between their *members*, is a choice called the **linkage**: complete linkage uses the largest distance between members, single linkage the smallest, average linkage the mean. The linkage is a hyperparameter, and different choices can produce quite different trees from the same data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nd_f  <- dist(scale(faithful))\nhc_f <- hclust(d_f, method = \"complete\")\nplot(hc_f, labels = FALSE, hang = -1, main = \"\", xlab = \"\", sub = \"\", ylab = \"merge height\")\nabline(h = 4, lty = 2)\n```\n\n::: {.cell-output-display}\n![Dendrogram of hierarchical clustering (complete linkage) on the standardized Old Faithful data. The height at which two branches join is the distance at which their clusters merged; cutting the tree at the dashed line yields two clusters.](08-unsupervised-clustering-mixtures_files/figure-pdf/fig-dendro-1.png){#fig-dendro fig-pos='H'}\n:::\n:::\n\n\n@fig-dendro shows the result for the standardized Old Faithful data as a **dendrogram**: a tree in which the height at which two branches join is the distance at which the corresponding clusters were merged. Long vertical stretches without merges indicate well-separated clusters, and cutting the tree at the dashed height produces the two clusters the scatterplot suggested. The dendrogram displays every number of clusters at once, from $n$ down to one, which is informative but also a reminder that the method itself never decides how many clusters there are. Because hierarchical clustering needs the full $n \\times n$ distance matrix, it becomes expensive when $n$ is large.\n\n**K-means** takes the opposite route: fix the number of clusters $K$ in advance, and search for the partition of the observations into $K$ clusters that minimizes the total squared Euclidean distance between each observation and the mean of its cluster, its **centroid**. The exact search is infeasible, since the number of possible partitions is astronomical, so the standard algorithm iterates two steps from a random starting assignment: assign each observation to its nearest centroid, then recompute each centroid as the mean of its assigned observations, and repeat until nothing changes. Each step lowers the criterion, so the algorithm always converges, but only to a *local* minimum that depends on the random start. Two consequences follow for practice. The labels of the clusters are arbitrary, so cluster 1 in one run can be cluster 2 in the next, a phenomenon called **label switching** that also matters for the mixture models later in this chapter. And a single run can simply find a poor solution, so the algorithm should always be run from many random starts, keeping the best result; in R, `kmeans(x, centers = K, nstart = 25)`. @fig-kmeans shows the result for the geyser data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(8)\nkm <- kmeans(scale(faithful), centers = 2, nstart = 25)\nplot(faithful$eruptions, faithful$waiting, pch = c(1, 16)[km$cluster],\n     xlab = \"eruption duration (min)\", ylab = \"waiting time (min)\")\ncent <- aggregate(faithful, list(km$cluster), mean)\npoints(cent$eruptions, cent$waiting, pch = 4, cex = 2, lwd = 3)\n```\n\n::: {.cell-output-display}\n![K-means with K = 2 on the standardized Old Faithful data, mapped back to the original units. Crosses mark the cluster centroids.](08-unsupervised-clustering-mixtures_files/figure-pdf/fig-kmeans-1.png){#fig-kmeans fig-pos='H'}\n:::\n:::\n\n\nA useful way to understand what K-means produces is **vector quantization**, its application to images. Treat every pixel as an observation (its colour values as features), cluster the pixels into $K$ groups, and replace each pixel by its cluster centroid: the image now contains only $K$ distinct colours and can be stored in far less space. With $K = 100$ the compressed image is hard to distinguish from the original; with $K = 5$ it is visibly posterized; with $K = 1$ it is a single grey rectangle. There is no correct $K$ here, only a trade: more clusters reconstruct the data more faithfully, and more clusters take more space to store. Reconstruction error and model complexity pull against each other, exactly as training fit and model complexity did in @sec-overfitting, and this trade returns in earnest when the number of clusters must be chosen in the model-based framework below.\n\n::: {.callout-tip icon=\"false\" title=\"Exercise 8.1\"}\n(a) A dataset records height in centimetres and monthly income in euros. What happens if these two features are given to `dist()` unstandardized, and why?\n(b) A researcher wants to cluster daily activity curves from accelerometers, where the same activity pattern can be shifted in time between persons. Why is Euclidean distance between the raw curves a poor choice, and what kind of distance addresses this?\n(c) In @fig-dendro, what would cutting the tree at height 2.5 instead of 4 have produced, and which of the two cuts is \"correct\"?\n(d) A colleague reports \"the K-means clustering\" of a dataset, run once with `nstart = 1`. Name two distinct reasons the reported clusters might not be reproducible.\n:::\n\n::: {.callout-note collapse=\"true\" icon=\"false\" title=\"Answer 8.1\"}\n(a) Income has a standard deviation in the hundreds or thousands, height in the tens, so squared income differences dominate the sum: the \"clustering\" is effectively a clustering on income alone. Standardization gives the features equal weight.\n(b) Euclidean distance compares the curves minute by minute, so two persons doing identical things an hour apart appear maximally different. Elastic distances such as dynamic time warping align the curves before comparing them.\n(c) A lower cut crosses more branches, so it produces more, smaller clusters. Neither cut is correct in any absolute sense: the tree represents the data, and the number of clusters is a choice the analyst brings to it, ideally on the grounds discussed at the end of this chapter.\n(d) The random start can land the algorithm in different local minima with genuinely different partitions, and even when the partition is identical the arbitrary labels can switch, so cluster \"1\" need not be the same group across runs.\n:::\n\n## Two cultures, again\n\nBefore moving to the second family, it is worth noticing what kind of object K-means is, because the difference from everything in chapters 1 to 4 illustrates a cultural divide as sharp as the one @sec-explanation-prediction described. In classical statistical modelling the analyst starts from a *model*: a probabilistic description of how the data could have arisen, with parameters that are interesting *if the model holds*. Once the model is written down, how to estimate its parameters usually follows from standard statistical theory, typically by optimizing a likelihood; the computation is a consequence, not the contribution. Machine learning often works in the opposite direction. It starts from a *computation* that produces something apparently useful, K-means being a perfect example: an intuitive procedure with no probability model in sight. The questions come afterwards: what is this computation good for, and how should it be evaluated, given the task? That order of operations, compute first and justify by usefulness, was proposed as a legitimate mode of data analysis as early as Tukey's \"The future of data analysis\" [@tukey1962], decades before machine learning made it routine. Neither direction is superior. The model-first route buys interpretable parameters and principled inference at the price of assumptions; the algorithm-first route buys flexibility and speed at the price of not quite knowing what the output *is*. The next section takes the model-first route to the same destination, and the payoff will be that the trade-offs become visible: what K-means silently assumes can be stated exactly once a model stands behind it.\n\n## Clustering with a model: mixtures\n\nSuppose the height of every person on the planet were measured and plotted.^[The measurement is invented, but the rest of the section is real.] The left panel of @fig-height shows the distribution: clearly not normal, with two peaks that look like they might come from two groups. An obvious guess is that the groups are women and men. Had each person's sex been recorded, the guess could be confirmed by drawing the histogram separately per group, as in the right panel: within each sex, height is close to normally distributed, and only the combination is not. But suppose sex was not recorded. This happens constantly in research: the usability test that omitted handedness, the survey that could not ask the sensitive question, the attitude that cannot be measured directly at all. The groups are suspected but unobserved, which is to say *latent*, and recovering them from the observed data is exactly the unsupervised task.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx <- seq(1.40, 2.00, length.out = 400)\nf_w <- dnorm(x, 1.62, 0.065); f_m <- dnorm(x, 1.77, 0.070)\nmix <- 0.5 * f_w + 0.5 * f_m\npar(mfrow = c(1, 2), mar = c(4, 4, 1.5, 1))\nplot(x, mix, type = \"l\", lwd = 2, xlab = \"height (m)\", ylab = \"density\",\n     main = \"observed\")\nplot(x, 0.5 * f_w, type = \"l\", lwd = 2, xlab = \"height (m)\", ylab = \"density\",\n     main = \"the two groups\", ylim = c(0, max(mix) * 1.05))\nlines(x, 0.5 * f_m, lwd = 2)\nlines(x, mix, lty = 2)\n```\n\n::: {.cell-output-display}\n![An invented population of heights. Left: the observed distribution, which is not normal. Right: the two groups that produced it, women and men, each normally distributed, with their sum as the dashed line.](08-unsupervised-clustering-mixtures_files/figure-pdf/fig-height-1.png){#fig-height fig-pos='H'}\n:::\n:::\n\n\nOne idea that does *not* work is to split the sample on a guess about each person's sex and compute histograms within the guessed groups: without extra information the guesses will be wrong often enough to distort both histograms. What does work is a **mixture model**. Write the density of height as a weighted sum of two normal densities,\n\n$$\np(\\text{height}) = \\pi_1^X\\, \\text{Normal}(\\mu_1, \\sigma_1) + (1 - \\pi_1^X)\\, \\text{Normal}(\\mu_2, \\sigma_2),\n$$ {#eq-mixture}\n\nwhere $\\pi_1^X$ is the probability that the latent group variable $X$ takes its first value, and $\\mu_k, \\sigma_k$ are the mean and standard deviation of height within group $k$. (The superscript $X$ is not a power; it labels the variable the probability belongs to, a notation that is standard in this literature and becomes convenient with categorical data below. The groups are numbered rather than named because the model cannot know which component is \"men\": component 1 could equally correspond to women, the mixture-model version of label switching.) Fitting @eq-mixture to the observed heights recovers estimates of all five parameters, and with them the right panel of @fig-height, *without sex ever having been observed*. As the sample grows, the estimates converge on the true within-group distributions.\n\nThis result is remarkable enough that its price should be stated immediately. The model *assumes* that height is normally distributed within each group, and this assumption is not verifiable from the observed data, because the observed data are exactly the mixture in which the groups are hidden. The assumption is what converts an impossible problem, unscrambling two unlabelled distributions, into a solvable one. Everything the mixture model delivers is conditional on it, a point this chapter returns to at length.\n\nEstimation works by a procedure worth understanding, the **EM algorithm**, because its central quantity is also the model's main practical output. Start from a guess of the parameters. Given the guess, compute for each person the **posterior probability** of belonging to each group: by Bayes' rule, the probability that a person of height $h$ is in group 1 is group 1's share of the total density at $h$,\n\n$$\n\\Pr(X = 1 \\mid h) = \\frac{\\pi_1^X\\, \\text{Normal}(h; \\mu_1, \\sigma_1)}{p(h)} .\n$$\n\nThen update the parameter estimates using every person, weighted by these posteriors: a person who is probably a man contributes mostly to the male mean, but also a little to the female mean, in proportion to the uncertainty. Iterating the two steps until nothing changes maximizes the likelihood. The posterior probabilities are the model's answer to \"who is in which group\": not a hard assignment but a probability per person, acknowledging that group membership is genuinely uncertain. A small computation makes this concrete:\n\n\n::: {.cell}\n\n```{.r .cell-code}\np_m <- 0.5 * dnorm(1.72, 1.77, 0.070)   # component density: men, at 1.72 m\np_w <- 0.5 * dnorm(1.72, 1.62, 0.065)   # component density: women, at 1.72 m\nround(p_m / (p_m + p_w), 2)             # posterior probability of being a man\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.7\n```\n\n\n:::\n:::\n\n\nA person of 1.72 metres is more likely a man than a woman, but far from certainly, and the posterior of 0.70 records exactly how far. Where the two component curves cross, the posterior is 0.50 and the observation contributes equally to both groups.\n\n### Latent profile analysis: mixtures of several continuous variables\n\nWith one observed variable the price of the assumption was steep. With several variables the model becomes both more useful and more credible, because the variables corroborate each other. The multivariate version of @eq-mixture, a mixture of multivariate normal distributions, is called a **Gaussian mixture model** in machine learning and **latent profile analysis (LPA)** in the social sciences; the two names refer to the same model. Each component $k$ now has a mean *vector* and a covariance *matrix*, so in two dimensions a component is an ellipse: its centre is the mean vector, its size, shape, and orientation are the covariance matrix.\n\nThe covariance matrices can be constrained, and the constraints matter. Requiring all components to share one covariance matrix gives clusters of equal size and shape; letting every component have its own gives full flexibility at the price of many more parameters, since a covariance matrix in $q$ dimensions has $q(q+1)/2$ of them. This is the bias-variance trade-off of @eq-bias-variance in new clothing: a rigid parameterization can miss the clusters' true shapes, a flexible one can chase noise. The `mclust` package [@scrucca2016] organizes these options in a three-letter code for volume, shape, and orientation, each either **E**qual across components, **V**ariable, or **I** (spherical): \"EII\" is equal-volume spheres, \"EEE\" is shared ellipses, \"VVV\" is every-component-for-itself. By default `Mclust` fits every parameterization for a range of component counts and reports the best model, chosen by a criterion that @sec-mixture-fit examines closely:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(mclust)\nmc <- Mclust(faithful, verbose = FALSE)\nsummary(mc)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n---------------------------------------------------- \nGaussian finite mixture model fitted by EM algorithm \n---------------------------------------------------- \n\nMclust EEE (ellipsoidal, equal volume, shape and orientation) model with 3\ncomponents: \n\n log-likelihood   n df       BIC       ICL\n      -1126.326 272 11 -2314.316 -2357.824\n\nClustering table:\n  1   2   3 \n 40  97 135 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Left: BIC for the mclust parameterizations on the Old Faithful data, by number of components; higher is better in mclust's sign convention. Right: the selected model's classification, with the component ellipses drawn.](08-unsupervised-clustering-mixtures_files/figure-pdf/fig-mclust-1.png){#fig-mclust}\n:::\n:::\n\n\n@fig-mclust shows the criterion behind that choice and the fitted components. Two details of the output deserve attention. First, K-means turns out to be hiding inside this model: constraining the components to equal-sized spheres (EII), the class proportions to be equal, and the posterior probabilities to hard 0/1 assignments makes model-based clustering computationally equivalent to K-means. The algorithm of the previous section was a mixture model all along, with assumptions nobody had to state because no model was written down; spelled out, they are strong ones, spherical clusters of equal size, and @fig-faithful's elongated clusters violate them visibly. Second, the selected solution has *three* components where the eye insists on two clusters. This is not a mistake. The upper-right cluster is not elliptical, so the model uses two overlapping ellipses to describe its shape, and the mixture describes the *density* correctly at the cost of the component–cluster correspondence. When the groups themselves are the quantity of interest, two repairs exist: select the number of components by a criterion that rewards well-separated components (the ICL of @sec-mixture-fit), or fit the well-fitting mixture first and then **merge** components that overlap heavily into single clusters [@baudry2010], as `mclust::clustCombi()` does, which reduces these three components to the two clusters the picture shows; @sec-merging returns to this. The distinction between *components*, the normal densities the model uses, and *clusters*, the groups the researcher means, is worth keeping.\n\n### Latent class analysis: mixtures of categorical variables\n\nWhen the observed variables are categorical, the within-class normal distributions are replaced by within-class category probabilities, and the model is called **latent class analysis (LCA)**. It is the discrete-observed, discrete-latent cell of @tbl-lvm, which organizes several earlier chapters' methods at once:\n\n|                        | Latent variable continuous | Latent variable discrete |\n|------------------------|---------------------------|--------------------------|\n| **Observed continuous** | factor analysis           | latent profile analysis  |\n| **Observed discrete**   | item response theory      | latent class analysis    |\n\n: Names of latent variable models, by the type of the observed and latent variables. {#tbl-lvm}\n\nFor three categorical observed variables $A$, $B$, $C$, the latent class model says\n\n$$\n\\pi_{abc}^{ABC} \\;=\\; \\sum_{x} \\pi_x^X \\, \\pi_a^{A \\mid X} \\, \\pi_b^{B \\mid X} \\, \\pi_c^{C \\mid X} ,\n$$ {#eq-lca}\n\nread as: the probability of observing the response pattern $(a, b, c)$ is a weighted sum over the latent classes $x$ of the probability of that pattern within each class, weighted by the class sizes $\\pi_x^X$. The crucial structure sits in the product $\\pi_a^{A \\mid X} \\pi_b^{B \\mid X} \\pi_c^{C \\mid X}$: *within* a class, the observed variables are independent. This assumption, **local independence**, is LCA's version of the within-class normality assumption above, and it carries the same double role: it is what identifies the model, and it is what the observed data cannot fully check. It also supplies the model's interpretation. The classes are constructed exactly such that they explain the associations among the observed variables: people are similar within classes and different between them, and whatever relationships the variables show in the whole sample should vanish once class membership is held constant.\n\nThe LISS panel provides a natural application. The health module asks every adult respondent whether a physician has ever diagnosed each of a list of conditions. Ten of these diagnoses, from angina to cancer, are binary indicators of a respondent's pattern of chronic disease, and a standing question in health research is whether such conditions cluster into recognizable **multimorbidity** patterns: combinations that co-occur in the same people, such as the cardiometabolic cluster of hypertension, high cholesterol, and diabetes. The script `analysis/liss/06-prepare-lca.R` builds the dataset: 4,647 respondents with complete diagnosis batteries. The model is fitted with the `poLCA` package [@linzer2011].\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(poLCA)\nd <- readRDS(\"../data/liss-health-social-integration/liss_lca_conditions.rds\")\nitems <- c(\"angina\", \"heartattack\", \"hypertension\", \"cholesterol\", \"stroke\",\n           \"diabetes\", \"lung\", \"asthma\", \"arthritis\", \"cancer\")\ndd <- d[items] + 1                       # poLCA codes categories 1, 2\nf  <- as.formula(paste(\"cbind(\", paste(items, collapse = \",\"), \") ~ 1\"))\nset.seed(8)\nfits <- lapply(1:5, function(k)\n  poLCA(f, dd, nclass = k, nrep = if (k == 1) 1 else 10,\n        maxiter = 3000, verbose = FALSE))\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nround(t(sapply(fits, function(m)\n  c(classes = length(m$P), loglik = m$llik, npar = m$npar,\n    AIC = m$aic, BIC = m$bic))), 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     classes  loglik npar     AIC     BIC\n[1,]       1 -9966.1   10 19952.2 20016.6\n[2,]       2 -9361.1   21 18764.1 18899.5\n[3,]       3 -9286.9   32 18637.7 18843.9\n[4,]       4 -9253.5   43 18592.9 18870.0\n[5,]       5 -9240.6   54 18589.2 18937.2\n```\n\n\n:::\n:::\n\n\nThe `nrep = 10` argument runs the EM algorithm from ten random starting points per model and keeps the best, for the local-maxima reason K-means already taught; skipping it is the most common error in applied LCA. Each added class costs eleven parameters, one class proportion and ten conditional probabilities, and buys some log-likelihood. The BIC is smallest for the three-class model, while the AIC is still falling at five classes, a disagreement to which @sec-mixture-fit returns. Staying with the BIC's choice, @fig-lca-profile displays the three-class solution as a **profile plot**: one line per class, showing the probability of each diagnosis within that class.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Profile plot of the three-class latent class model of ten physician diagnoses, LISS 2025 (n = 4,647). Lines show the probability of each diagnosis within each class; percentages are the estimated class sizes.](08-unsupervised-clustering-mixtures_files/figure-pdf/fig-lca-profile-1.png){#fig-lca-profile}\n:::\n:::\n\n\nThe classes are recognizable. The largest, at about three quarters of the sample, is a *healthy* class in which every diagnosis is rare. The second, close to a fifth of respondents, is a *cardiometabolic* class: hypertension in about six of ten members, high cholesterol in more than half, elevated diabetes and arthritis. The smallest, around five percent, is a *respiratory–musculoskeletal* class in which asthma, chronic lung disease, and arthritis are the distinguishing diagnoses. Each respondent additionally receives a posterior probability of belonging to each class, exactly as in the height example, and these posteriors carry real uncertainty: on average the largest posterior is well below 1. That uncertainty must be respected when the classes are used further. Assigning each person to their most likely class and then regressing that assignment on covariates treats the classification as data when it is an estimate, and biases the resulting associations toward zero; corrected **three-step** procedures exist for exactly this task [@bakk2013].\n\nThe local independence assumption is not entirely beyond checking. Within each class, pairs of indicators should be unrelated; computing the residual association of each pair within classes, for instance as a chi-square in the class-specific cross-table (a **bivariate residual**), points to pairs the model fails to explain. A large residual between asthma and chronic lung disease, say, would signal that these two diagnoses share something beyond the classes, and a model treating them jointly, or an extra class, may be needed. What such checks can never do is validate local independence wholesale, for the reason the height example made plain: the classes are latent, so the full pattern of within-class association is not observable.\n\n::: {.callout-tip icon=\"false\" title=\"Exercise 8.2\"}\n(a) In @eq-lca, how many parameters does a $K$-class model for ten binary indicators have, and how many does the saturated model for the $2^{10}$ response patterns have? For which $K$ does the first exceed the second?\n(b) State the three restrictions that turn latent profile analysis into K-means.\n(c) A colleague fits the three-class model above, assigns every respondent to their most likely class, and reports \"class membership predicts mortality\". Name the two distinct sources of overconfidence in that sentence.\n:::\n\n::: {.callout-note collapse=\"true\" icon=\"false\" title=\"Answer 8.2\"}\n(a) The $K$-class model has $(K - 1) + 10K$ parameters: $K-1$ free class proportions and ten conditional probabilities per class. The saturated model has $2^{10} - 1 = 1023$. The model reaches 1023 parameters at $K = 93$, but it stops being identified far earlier, as @sec-mixture-fit discusses: counting parameters is only the crudest identification check.\n(b) Equal-sized spherical covariance matrices in every class (EII), equal class proportions, and hard assignment of each observation to one class (posterior probabilities forced to 0 or 1).\n(c) The classification is an estimate with uncertainty, and treating the modal assignment as observed data biases the association toward zero, which the three-step corrections repair. And the classes themselves are model-dependent: as @sec-mixture-fit argues, a well-fitting mixture does not establish that these particular groups exist, so \"predicts mortality\" inherits every assumption behind the class solution.\n:::\n\n## Choosing K, and trusting the result {#sec-choosing-k}\n\nEverything above postponed the same decision: how many clusters or classes, and which parameterization. In supervised learning this kind of decision went to the validation set, and the test set stood ready to price the final choice honestly. Here there is no outcome to score against, which is why model selection and evaluation deserve more space in this chapter than in any other, and why this section is the chapter's real destination. What replaces the missing judge is not one tool but a strategy [@hennig2015], assembled from five kinds of evidence:\n\n1. **External information**: variables not used to form the clusters, and decisions the clusters are meant to improve.\n2. **Visual exploration**: looking at the clusters, in the data's own dimensions or in a two-dimensional map of them.\n3. **Stability and sensitivity**: whether the clusters survive changes to the method, the sample, or the features.\n4. **Internal validation indices**: numbers computed from the data and the clustering alone, such as the silhouette and the gap statistic.\n5. **Tests for clustering structure**: whether there is any evidence of groups at all.\n\nModel-based clustering adds a sixth kind, the fit of the model itself, which the next section treats on its own because it brings back the deepest issue in the book, equivalence. The five are taken in turn. None is decisive; a defensible analysis consults several and reports what each said, rather than the single number that happened to agree with the analyst.\n\n### External information\n\nThe strongest evidence for a clustering comes from outside it. If the multimorbidity classes above are real, they should differ in variables that played no part in forming them, in directions that make sense: the cardiometabolic class should be older, and a class defined by asthma and arthritis might be expected to contain more women, since both conditions are more prevalent in women. Such variables are called **criterion** or **distal** variables, and the LISS data carry two:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm3  <- fits[[3]]\nord <- order(m3$P, decreasing = TRUE)      # 1 = largest class\ncls <- match(m3$predclass, ord)            # modal class per person\next <- data.frame(class = cls, age = d$age, female = d$female)\nround(t(sapply(split(ext, ext$class), function(s)\n  c(n = nrow(s), mean_age = mean(s$age),\n    pct_female = 100 * mean(s$female, na.rm = TRUE)))), 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     n mean_age pct_female\n1 3782     51.9       52.8\n2  723     66.6       51.0\n3  142     65.0       59.9\n```\n\n\n:::\n:::\n\n\nThe healthy class is fifteen years younger than the other two, and the respiratory–musculoskeletal class is the most female. Neither fact was available to the model, so both count as corroboration. Two refinements turn this from a check into a method. The table assigns each respondent to their modal class, which the previous section warned against: the assignment is an estimate, and treating it as data attenuates the association with any external variable. The **three-step** procedures repair this by estimating the classes first, assigning second, and relating the assignment to external variables third with a correction for the known classification error [@bolck2004; @vermunt2010; @bakk2013]; used this way, three-step analysis is external validation with honest standard errors, and the *size* of the corrected associations is a measure of how much the classes explain. Alternatively the external variable can be let into the model, as a covariate predicting class membership or as a distal outcome predicted by it, and the information criteria of the next section compared with and without the link; a class solution that organizes external variables well then scores better than one that does not, so the criterion has been made to answer partly to the outside world.\n\nThe most demanding external check is to use the clustering for the decision it was built for and to measure whether the decision improves. A market segmentation exists so that different segments can be approached differently; the test of the segmentation is not any index but whether segment-specific campaigns sell more than a single campaign would have [@dolnicar2018]. A multimorbidity typology intended to organize care is validated when care organized by it produces better outcomes than care that ignores it. This is the supervised judge re-entering by the back door: as soon as the clustering serves a decision with a measurable consequence, the consequence is an outcome, and everything @sec-evaluation said about honest evaluation applies. It also invokes everything @sec-explanation-prediction said about rain dances, because \"does the decision improve\" is a causal question that a classification alone cannot answer.\n\n### Visual exploration\n\nIn two dimensions the eye is the best cluster validator there is, which is why this chapter chose Old Faithful. In three to ten dimensions, pairwise scatterplots and projections on the directions that best separate the clusters (**discriminant coordinates**) still serve. Beyond that, the current practice is to map the observations into two dimensions with a nonlinear method that tries to keep each observation's neighbours as its neighbours: **t-SNE** [@vandermaaten2008] and **UMAP** [@mcinnes2018] are the popular choices, and their maps have become the standard picture of high-dimensional data in genomics, natural language processing, and increasingly in social science. Old Faithful is the ideal test of what such maps do, precisely because it needs no mapping: the truth is in @fig-faithful, and @fig-manifold shows what the maps make of it.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Two-dimensional maps of the (standardized) Old Faithful data, coloured by the K-means solution with K = 2. Top left: the data themselves. The other panels are t-SNE with perplexity 5 and 30, and UMAP with 15 neighbours. The two groups survive every map; nothing else does.](08-unsupervised-clustering-mixtures_files/figure-pdf/fig-manifold-1.png){#fig-manifold}\n:::\n:::\n\n\nThe two groups are preserved in every panel, which is the good news and the reason these maps are useful: a clustering found in the full space can be painted onto the map, and clusters that scatter across the map deserve suspicion. Everything else in the picture is manufactured. The elongated, correlated shapes of the real clusters become round blobs or thin strands; the small cluster can be drawn as large as the big one; the distance between the clusters is whatever the algorithm's settings made it; and at low perplexity t-SNE shatters each cluster into a dozen worm-like fragments that a reader without @fig-faithful would happily count as clusters. None of this is a bug. The methods preserve neighbourhoods, not distances, sizes, or shapes, so a map can show *that* groups exist but not how many, how large, or how far apart [@wattenberg2016]. The settings and the random seed change the picture, and there is no criterion for the right settings because the map is not fitted to anything. The worst practice, common in fields where these maps are routine, is to run a clustering algorithm on the map coordinates themselves, which clusters the distortions [@chari2023]. Look at the maps by all means; cluster in the data.\n\n### Stability and sensitivity\n\nStability asks the question closest to this book's heart: would the clusters survive a replication? Three kinds of replication can be simulated on the data at hand, corresponding to three things the analyst could have done differently:\n\n- **the method**: a different distance, linkage, parameterization, or $K$;\n- **the observations**: a different sample from the same population, imitated by resampling;\n- **the features**: a different, equally reasonable, choice of variables.\n\nFor each, the question is whether observations land in the same clusters as before, measured by an index of agreement between two partitions that is indifferent to the arbitrary labels: the **Jaccard index** of a cluster is the share of observations in either version of it that are in both, and the **adjusted Rand index (ARI)** [@hubert1985] scores two whole partitions on a scale where 1 is identical and 0 is chance agreement.\n\n*The method.* For Old Faithful with $K = 2$, K-means and hierarchical clustering under every linkage agree almost perfectly (ARI above 0.99). With $K = 3$ the agreement collapses:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nX  <- scale(faithful)                      # standardized, as before\nhc <- function(m, k) cutree(hclust(dist(X), method = m), k)\nset.seed(1)\nparts <- list(kmeans   = kmeans(X, 3, nstart = 25)$cluster,\n              complete = hc(\"complete\", 3), average = hc(\"average\", 3),\n              single   = hc(\"single\", 3),   ward    = hc(\"ward.D2\", 3))\nari <- outer(names(parts), names(parts), Vectorize(function(a, b)\n  adjustedRandIndex(parts[[a]], parts[[b]])))\ndimnames(ari) <- list(names(parts), names(parts))\nround(ari, 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         kmeans complete average single ward\nkmeans     1.00     0.75    0.61   0.59 0.80\ncomplete   0.75     1.00    0.74   0.66 0.74\naverage    0.61     0.74    1.00   0.85 0.66\nsingle     0.59     0.66    0.85   1.00 0.62\nward       0.80     0.74    0.66   0.62 1.00\n```\n\n\n:::\n:::\n\n\nFive methods, five different third clusters, one of them (single linkage) a single outlying eruption. When every reasonable method returns the same partition, the partition is a property of the data; when they disagree, it is a property of the method, and the report should say which method and why.\n\n*The observations.* Bootstrap stability refits the clustering on resamples of the data and records, for each original cluster, the Jaccard agreement with the most similar cluster in each resample [@hennig2007]. The `fpc::clusterboot()` function does this for any clustering method; below, for K-means with two and three clusters:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(fpc)\ncb2 <- clusterboot(X, B = 100, clustermethod = kmeansCBI, k = 2,\n                   seed = 1, count = FALSE)\ncb3 <- clusterboot(X, B = 100, clustermethod = kmeansCBI, k = 3,\n                   seed = 1, count = FALSE)\njac <- rbind(\"K = 2\" = c(cb2$bootmean, NA), \"K = 3\" = cb3$bootmean)\ncolnames(jac) <- paste(\"cluster\", 1:3)\nround(jac, 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      cluster 1 cluster 2 cluster 3\nK = 2      1.00      0.99        NA\nK = 3      0.69      0.91      0.79\n```\n\n\n:::\n:::\n\n\nBoth two-cluster solutions recur in essentially every resample. The three-cluster solution is less secure, and Hennig's rule of thumb says how much: a mean Jaccard above 0.85 marks a highly stable cluster, above 0.75 a stable one, between 0.6 and 0.75 a pattern whose exact membership is doubtful, and below 0.6 a cluster not to be trusted. Two of the three clusters pass, and the weakest is one of the two halves into which $K = 3$ cuts the large cluster, a cut the data do not support. This is the bootstrap of @sec-evaluation doing its usual job of estimating sampling variability, applied to a partition instead of a coefficient.\n\n*The features.* A clustering is a clustering of whichever variables were included, and a class that depends on one indicator is a class of that indicator. Leaving out each of the ten LISS diagnoses in turn, refitting the three-class model, and comparing the classification with the full model's shows which indicators carry the typology:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nari_drop <- sapply(items, function(drop) {\n  keep <- setdiff(items, drop)\n  fk   <- as.formula(paste(\"cbind(\", paste(keep, collapse = \",\"),\n                           \") ~ 1\"))\n  set.seed(8)\n  m <- poLCA(fk, dd[keep], nclass = 3, nrep = 10, maxiter = 3000,\n             verbose = FALSE)\n  adjustedRandIndex(m$predclass, m3$predclass)\n})\nround(sort(ari_drop), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nhypertension  cholesterol         lung       asthma     diabetes       cancer \n        0.56         0.62         0.73         0.73         0.80         0.83 \n   arthritis  heartattack       angina       stroke \n        0.90         0.97         0.97         0.99 \n```\n\n\n:::\n:::\n\n\nDropping angina, a heart attack, or a stroke changes almost nothing, because these rare diagnoses contribute little to the class definitions. Dropping hypertension or high cholesterol reshuffles the classes: the cardiometabolic class *is* the co-occurrence of those two, and a study that had not asked about cholesterol would have found a different typology. That is not a flaw in the model, but it is a fact about what the typology means, and a reader is entitled to it.\n\nStability is necessary and not sufficient. A partition along the single dominant variable is perfectly stable and perfectly uninteresting; conversely, a real but subtle structure can be unstable at the sample size available. Stability rules out one kind of error, mistaking noise for structure, and says nothing about the other kinds.\n\n### Internal validation indices\n\nInternal indices score a clustering from the data and the partition alone. The best known is the **silhouette** [@rousseeuw1987]. For each observation $i$, let $a_i$ be its mean distance to the other members of its own cluster and $b_i$ its mean distance to the members of the nearest other cluster; the silhouette width is\n\n$$\ns_i = \\frac{b_i - a_i}{\\max(a_i, b_i)} ,\n$$\n\nwhich is near 1 for an observation deep inside a compact, well-separated cluster, near 0 for one on the boundary between two clusters, and negative for one that would fit better elsewhere. The **average silhouette width** over all observations summarizes the partition, and the silhouette plot in @fig-silhouette displays each cluster's widths as a sorted bar chart. The **gap statistic** [@tibshirani2001gap] takes a different route: it computes the within-cluster dispersion $W_K$ for each $K$, as K-means does, and compares its logarithm with what the same computation would give on data with no clusters at all, simulated uniformly over the range of the features. The gap is the difference; it is large when the data are much more clustered than featureless data would be, and the recommended choice of $K$ is the smallest $K$ whose gap is within one simulation standard error of the gap at $K + 1$.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Silhouette plots for K-means on the standardized Old Faithful data with K = 2 (left) and K = 3 (right). Each bar is one eruption's silhouette width, sorted within cluster. With K = 3 the large cluster is cut in two, and both halves have low widths: their members are about as close to the other half as to their own.](08-unsupervised-clustering-mixtures_files/figure-pdf/fig-silhouette-1.png){#fig-silhouette}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nD <- dist(X)\nset.seed(1)\nasw <- sapply(2:6, function(k)\n  mean(silhouette(kmeans(X, k, nstart = 25)$cluster, D)[, \"sil_width\"]))\ngap <- clusGap(X, FUN = function(x, k) kmeans(x, k, nstart = 25),\n               K.max = 6, B = 100)\nround(cbind(K = 1:6, ASW = c(NA, asw),\n            gap = gap$Tab[, \"gap\"], SE = gap$Tab[, \"SE.sim\"]), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     K   ASW   gap    SE\n[1,] 1    NA 0.058 0.022\n[2,] 2 0.745 0.430 0.019\n[3,] 3 0.485 0.363 0.019\n[4,] 4 0.381 0.355 0.021\n[5,] 5 0.364 0.373 0.019\n[6,] 6 0.393 0.375 0.016\n```\n\n\n:::\n:::\n\n\nBoth indices agree with the eye: the silhouette peaks sharply at $K = 2$, and the gap rule stops there as well. Their limitation is easy to state and easy to forget: they encode a particular idea of what a cluster is, compact, well separated, roughly round, and they know nothing of the clustering's aim. Two elongated, touching clusters that a substantive question treats as distinct will score badly on both; a partition that splits one continuous cloud into halves can score well. Different indices formalize different cluster concepts and can rank the same solutions differently, so an index can support a choice made on other grounds but cannot make it.\n\n### Testing for clustering structure\n\nThe last kind of evidence asks the most basic question: is there any structure to find? The **dip test** [@hartigan1985] tests a single variable, or the pairwise distances, against unimodality, and the Hopkins statistic compares the distances among the observations with the distances to random points in the same space; either can flag data that are simply one diffuse cloud. For mixture models the corresponding tool is the likelihood-ratio test of $K$ against $K+1$ components. The ordinary chi-square theory fails here, because the smaller model sits on the boundary of the larger one, and the accepted replacement is the **bootstrapped likelihood-ratio test**, which simulates the statistic's distribution under the smaller model [@mclachlan1987; @nylund2007]:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(3)\nmclustBootstrapLRT(faithful, modelName = \"VVV\", maxG = 3, nboot = 199,\n                   verbose = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n------------------------------------------------------------- \nBootstrap sequential LRT for the number of mixture components \n------------------------------------------------------------- \nModel        = VVV \nReplications = 199 \n               LRTS bootstrap p-value\n1 vs 2   319.065354             0.005\n2 vs 3     6.130516             0.580\n3 vs 4    31.837839             0.010\n```\n\n\n:::\n:::\n\n\nOne component is decisively rejected in favour of two, which is the structure question answered: there are clusters. The rest of the table is a warning about sequential testing. Two against three is not rejected, so the procedure stops at two, but three against four would have been, so the \"number of components\" depends on the direction of travel. And with $n$ in the thousands, as in the LISS data, every added class is significant, because the test detects any misfit however small. Tests establish that structure exists; they are a poor guide to how much.\n\n## Model fit, information criteria, and their limits {#sec-mixture-fit}\n\nFor model-based clustering a sixth kind of evidence exists, and it is the one applied work leans on most heavily: the fit of the model. The standard tools are the AIC and BIC of earlier chapters,\n\n$$\n\\text{AIC} = -2\\,\\ell + 2\\,p, \\qquad\n\\text{BIC} = -2\\,\\ell + p \\log n ,\n$$\n\nwhere $\\ell$ is the maximized log-likelihood, $p$ the number of parameters, and $n$ the sample size. Each has two justifications, and it helps to hold both. The first is the one in their names. Akaike derived the AIC as an estimate of how far the fitted model's distribution lies, in the information-theoretic sense of Kullback and Leibler, from the distribution that generated the data; Schwarz derived the BIC as an approximation to the marginal likelihood of the model, so that comparing BICs approximates comparing the posterior probabilities of the models. The second justification is the one this book has prepared the reader for. The in-sample log-likelihood, like the training error of @sec-overfitting, flatters every added class, because the same data that fitted the parameters are scoring them. On average the flattery, the *optimism* of the in-sample fit, amounts to about $2p$ on the $-2\\ell$ scale, so the AIC is the in-sample deviance plus an estimate of its optimism: an estimate of $-2$ times the log-likelihood the model would achieve on new data from the same population [@hastie2009, ch. 7]. Comparing AICs is therefore an approximation to comparing models on fresh data, the very quantity @sec-evaluation measured by holding data out, and the direct route remains open: the log-likelihood can simply be cross-validated, scoring each held-out fold under the model fitted to the rest, with all of that chapter's machinery and cautions applying unchanged. The BIC's heavier penalty, $p \\log n$, buys a different property. It is consistent: when one of the candidate models is true, the BIC selects it as $n$ grows, where the AIC keeps a taste for slightly-too-large models. In mixtures the BIC tends to select fewer, better-separated classes, and it is the default in this literature [@gormley2023]. The vector-quantization trade of this chapter's first half is the same computation in different words: the log-likelihood is the reconstruction, the penalty is the file size.\n\nThe two criteria disagreed on the LISS data, the BIC choosing three classes and the AIC five, and such disagreement is typical rather than exceptional. The AIC aims at predictive accuracy and will add classes that improve the density estimate slightly; the BIC aims at recovering a parsimonious structure. There is no neutral arbiter, because the criteria answer different questions, and the choice between them is a choice about the task. When the classes are to be interpreted and used, parsimony and separation usually matter more than the last increment of fit, which favours the BIC, possibly alongside the **ICL**, a BIC variant that additionally penalizes solutions whose classes overlap so much that observations cannot be confidently assigned [@biernacki2000]. On Old Faithful the difference is visible: the BIC chose three components, the ICL chooses two, because the third component buys fit but costs certainty of assignment. The next section returns to this.\n\n::: {.callout-tip icon=\"false\" title=\"Exercise 8.3\"}\nUsing the AIC/BIC table for the LISS diagnoses:\n\n(a) Reconstruct the BIC of the two-class model from its log-likelihood and parameter count, with $n = 4{,}647$.\n(b) The AIC still prefers five classes. Explain, in the vocabulary of chapters 6 and 7, what each criterion is trying to estimate, and construct a scenario in which the five-class model is the right choice after all.\n(c) Propose a cross-validation scheme that would compare the three- and five-class models directly on out-of-sample performance, and state what quantity is scored on the held-out folds.\n:::\n\n::: {.callout-note collapse=\"true\" icon=\"false\" title=\"Answer 8.3\"}\n(a) $\\text{BIC} = -2 \\times (-9361.1) + 21 \\times \\log 4647 = 18722.2 + 21 \\times 8.44 \\approx 18899.5$, matching the table.\n(b) The AIC estimates out-of-sample log-likelihood, so it rewards any structure that helps describe fresh data, including small or overlapping components; the BIC approximates the evidence for the model and demands more per parameter, favouring few well-separated classes. If the task were density estimation, generating realistic synthetic response patterns, say, the five-class model's better predictive fit is exactly what is wanted. For interpretable groups, the three-class solution's separation matters more.\n(c) Split respondents into folds; fit each candidate on the training folds, with many random starts; compute each held-out respondent's log-likelihood under the fitted model, summing over classes as in @eq-lca; average per fold and compare. The scored quantity is the out-of-sample log-likelihood that AIC approximates, and everything @sec-evaluation said about folds and leakage applies, including refitting the entire pipeline within each fold.\n:::\n\n**Identification, and its empirical failure.** With latent variables a question precedes model selection: is the model identified at all? @sec-identification introduced identification for causal quantities; the parametric version asks whether different parameter values could produce the same distribution of the observed data. For mixtures the answer degrades gracefully and dangerously. A latent class model can be formally underidentified, with strictly more parameters than the observed table can support, the parameter count of Exercise 8.2 being only the crudest bound [@goodman1974]. More insidious is **empirical underidentification**: the model is identified on paper, but the observed data barely constrain some parameters, so the likelihood surface is nearly flat in some directions. LCA reaches this state quickly, especially with rare indicators, small classes, and generous $K$. Its symptoms are visible to an analyst who looks. Repeated estimation from many random starts returns different solutions with practically equal log-likelihoods; estimated probabilities land on the boundary at exactly 0 or 1; some class sizes collapse toward zero; and standard errors of some parameters explode. The six-class model for the LISS diagnoses shows the syndrome on demand:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsixes <- t(sapply(1:8, function(s) {\n  set.seed(100 + s)\n  m <- poLCA(f, dd, nclass = 6, nrep = 1, maxiter = 3000, verbose = FALSE)\n  c(loglik = m$llik, smallest_class = min(m$P),\n    boundary_estimates = sum(unlist(m$probs) < 1e-4 |\n                             unlist(m$probs) > 1 - 1e-4))\n}))\nround(sixes, 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       loglik smallest_class boundary_estimates\n[1,] -9226.89           0.01                 26\n[2,] -9228.66           0.03                 20\n[3,] -9228.68           0.03                 22\n[4,] -9228.62           0.03                 20\n[5,] -9228.63           0.03                 20\n[6,] -9226.88           0.01                 24\n[7,] -9233.45           0.00                 12\n[8,] -9229.00           0.01                 26\n```\n\n\n:::\n:::\n\n\nEight starts produce several distinct maxima whose log-likelihoods differ only in the first decimal, each with a dozen or more boundary estimates and smallest classes holding at most a few percent of the sample. No one of these solutions deserves the name \"the six-class model\": the data cannot tell them apart, and any substantive story told about one of them would have come out differently on the next start. The practical defences follow from the symptoms: always use many random starts and inspect the spread of the maxima, distrust boundary estimates and near-empty classes, and when the syndrome appears, reduce $K$, restrict parameters, or collect more indicators, since each added indicator multiplies the observable information while adding only $K$ parameters.\n\n**Equivalence, one more time.** Even a well-identified, well-fitting mixture supports a weaker conclusion than it appears to, and the reason is not special to mixtures. Every fit statistic in this book, from the chi-square of @sec-theory-to-glm to the BIC above, works the same way: the model implies a distribution for the observed data, and the statistic measures the distance between that implied distribution and the observed one. Two models that imply the same distribution are therefore indistinguishable by any fit statistic, whatever their parameters say, and this is the **equivalence** problem of @sec-theory-to-glm and @sec-identification in mixture clothing. It arises here in two forms. A heavily restricted model with many classes can reproduce the observed distribution as well as a flexible model with few classes; and, as the Old Faithful example showed, a mixture of three components and a mixture of two merged clusters describe one and the same density. Model selection, in other words, compares the members of a menu the analyst wrote down, and cannot see that the menu contains equivalent entries or that the truth is not on it; this is a general limitation of model selection, supervised or not, that the supervised chapters could ignore only because their menu was scored on an outcome. Without an outcome the consequence is stark. Fit cannot distinguish between equivalent descriptions, so the choice among them is made by assumptions, and the inference \"the model fits, hence these are the true latent groups\" is never available. What is available is the conditional statement this book has practiced since @sec-identification: *if* the population consists of groups within which the indicators are independent (or normal), *then* the data point to these groups, with this many classes, of these sizes. The assumptions carry the conclusion, and for latent variables some of them are uncheckable in principle, since checking would require observing the very variable that is latent.\n\nUncheckable is not the same as unsupportable, and here the book's oldest theme returns: design. Local independence is an assumption about *why the indicators are correlated*: it says the latent class is the only common cause, so that within a class the remaining variation in each indicator is noise specific to that indicator. Whether that is plausible depends on where the indicators come from. Ten self-reported diagnoses from a single questionnaire share a respondent, a sitting, a memory, and a reporting style, and any of these can correlate the indicators within classes, violating local independence in ways no fit statistic will reliably flag. Now consider instead a design in which one indicator of, say, problematic debt comes from a survey question, a second from an administrative register of payment arrears, and a third from a digital trace of account activity. These three measurements share essentially one thing: the person's true state. Their error sources, self-presentation, administrative lag, algorithmic misclassification, are distinct by construction, so conditional independence given the latent state is not a hope but a designed property. The same assumption that is heroic within a single survey becomes credible across sources, and nothing about the model changed, only the design behind its inputs. Latent variable models do not remove the need for input thinking; they relocate it, from the interpretation of coefficients to the provenance of indicators.\n\n## Merging components into clusters {#sec-merging}\n\nOne problem has surfaced three times now and deserves its own solution. The mixture model's building blocks are normal components (or, in LCA, locally independent classes), and the information criteria count *components*: the BIC picks the number of normal densities needed to describe the data's density well. A cluster in the researcher's sense is something else, a group of observations that belong together, and a group that is not normally shaped needs several components to trace it. On Old Faithful the BIC needed three components for two clusters. On a dataset of 200 crabs of two species and two sexes, four groups by construction, the BIC selects *nine* components, and @hennig2010 shows that they describe the density better than four would; the count is not wrong, it is answering a different question. Practice in the social and health sciences almost always equates classes with components, and so it is caught between two errors: accept the criterion's count and report subgroups that are shape artefacts, or override it by hand and lose the fit.\n\n**Merging** dissolves the dilemma, and it is remarkably underused outside statistics. The idea is to separate the two questions. First fit the mixture the data ask for, with as many components as the BIC wants, so that the density is described well. Then combine components hierarchically into clusters: start with every component as its own cluster, find the pair of clusters whose union is most cluster-like, merge them, and repeat until a stopping rule says the remaining clusters are distinct [@hennig2010]. Everything depends on the criterion for \"most cluster-like\", and several exist. The **entropy** criterion of @baudry2010, implemented in `mclust::clustCombi()`, merges the pair whose union most reduces the uncertainty of assignment, so that the resulting clusters are ones observations can be assigned to confidently; the decrease in entropy as clusters are merged shows a clear elbow at the right number of clusters. **Unimodality** criteria merge two components when their union has a single mode, checked along the ridgeline connecting the two component means or by the dip test, and stop when a merge would produce a bimodal cluster. **Misclassification** criteria, such as the Bhattacharyya distance between the components or a direct estimate of how many observations one component would misassign to the other, merge components so overlapping that they cannot be told apart, and stop when the remaining clusters can. @fig-merge shows the entropy version on Old Faithful, starting from the three components of @fig-mclust.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Merging on Old Faithful. Left: the two clusters obtained by merging the pair of components with the smallest entropy cost (`mclust::clustCombi()`), starting from the three components of @fig-mclust. Right: the entropy of the classification by number of clusters. Going from three components to two clusters removes almost all the uncertainty of assignment; going from two to one removes almost none, so two is the elbow.](08-unsupervised-clustering-mixtures_files/figure-pdf/fig-merge-1.png){#fig-merge}\n:::\n:::\n\n\nThe entropy of the three-component classification is about 42 nats, nearly all of it from eruptions torn between the two overlapping components in the upper right; merging those two removes almost all of it, leaving half a nat, and merging the two remaining clusters would remove only that half, which is to say that they were already separated and nothing is gained. The elbow at two clusters is the answer. The merged solution agrees with K-means almost perfectly (ARI 0.98) while keeping everything the mixture model offered, the posterior probabilities, the estimated proportions, and a density that actually fits. The alternative repair, selecting by the ICL instead of the BIC, reaches two components directly on these data, but it does so by accepting a worse density in exchange for separation, which matters whenever the model is also used to describe or generate data; merging keeps the fit and adds the clusters on top. The same logic applies to latent class analysis: fit the classes the BIC asks for, then merge classes between which the posterior probabilities cannot discriminate, and report the merged clusters as the typology while the full solution stays on record as the model.\n\nThere is a reason the choice of merging criterion cannot be made by the data, and @hennig2010 states it plainly: the merging problem is not identified. A mixture of two normal components is the same density whether the components are called one cluster or two, so whether they should be merged is not a question about the data at all. It is a question about the **cluster concept**, what the researcher means by a cluster. If clusters are modes, two components whose union is unimodal are one cluster. If clusters are dense patterns that stand out from a diffuse background, a narrow component sitting inside a wide one is a cluster of its own, though the union is unimodal. If clusters are groups that can be assigned to reliably, the criterion is misclassification. These concepts give different answers on the same data, and no fit statistic can adjudicate, because fit is identical across them. This is not a defect of merging; it is the truth about clustering that merging makes explicit. The number of clusters was never in the data alone; it was always in the data together with an idea of what a cluster is, and the idea should come from the task. A multimorbidity typology meant to guide treatment wants classes that can be assigned reliably; a typology meant to describe distinct disease processes wants modes. Saying which is the first step of the analysis, not the last.\n\n::: {.callout-tip icon=\"false\" title=\"Exercise 8.4\"}\n(a) Rank the five kinds of evidence of @sec-choosing-k by how much each depends on the analyst's cluster concept, and justify the two ends of your ranking.\n(b) A t-SNE map of a 40-item questionnaire shows six clear islands. List three questions to ask before believing there are six types of respondent.\n(c) On the LISS data, dropping hypertension changed the three-class solution substantially (ARI 0.56). A colleague concludes the typology is \"unreliable\". Give a more precise reading.\n(d) Explain why a 4-component mixture merged into 2 clusters and a 2-component mixture fitted directly can have identical clusters and different log-likelihoods, and when the difference matters.\n:::\n\n::: {.callout-note collapse=\"true\" icon=\"false\" title=\"Answer 8.4\"}\n(a) Internal indices depend most, because each index *is* a formalized cluster concept (compact and separated, for the silhouette). Tests for clustering structure depend least, since they ask only whether the data depart from one homogeneous cloud, though the choice of null hypothesis is itself a weak concept. External validation sits in between: it depends on the concept only through the choice of external variables and decisions.\n(b) Whether the islands survive a different perplexity and seed; whether a clustering fitted in the 40-dimensional data, painted on the map, respects the islands; and whether the islands are response *patterns* rather than persons, since 40 categorical items generate many identical rows that the map draws as tight clumps.\n(c) The typology is reliable *given its indicators*: resampling respondents leaves it intact. What the feature check shows is that the cardiometabolic class is largely defined by hypertension and cholesterol, so the typology is a typology of this item set, and a study with different items would find a different one. That is a statement about meaning and generalization, not about noise.\n(d) The four-component model describes the density with more flexibility, so its log-likelihood is at least as high; merging changes the labels, not the density. The difference matters when the model's density is used, for posterior probabilities near the boundaries, for simulating data, or for prediction, and does not matter when only the hard partition is used.\n:::\n\n## What the missing judge means\n\nThis chapter closes the machine learning part of the book, and it ends on a reversal worth stating plainly. Chapters 6 and 7 built their case on output validity: fix the task and the metric, and models can be compared empirically, with assumptions demoted to whatever helps prediction. That case rested entirely on the existence of a supervisor, an observed outcome against which performance could be measured honestly. Unsupervised learning has no such outcome, and the consequence runs through everything in this chapter. The number of clusters is not measurable but chosen, with criteria that answer different questions; the clusters themselves are conditional on assumptions, some uncheckable in principle; equivalent models tell different stories about the same fit; the very definition of a cluster comes from the task, not the data; and the strongest support available comes not from any statistic but from design, in the provenance of the indicators and in validation against external information. In other words: where the supervisor leaves, input validity returns. The questions of chapters 1 to 4, what was measured, how, on whom, and what must be assumed, were never machine learning's rivals; they are what machine learning stands on whenever the ground of honest output measurement is unavailable. A researcher who can run both playbooks, and knows which one the problem calls for, has the whole book.\n\n## Where to go from here {.unnumbered}\n\nClustering and mixture modelling extend in every direction, and this chapter has shown only the trunk. A few branches the reader may want, with where to read about them rather than here. Covariates can be built into the mixture, so that class membership depends on background variables (**latent class regression**, or mixtures of experts), and the classes can predict distal outcomes; @vermunt2010 and @bakk2013 cover the estimation issues, and `poLCA` fits the regression version. Repeated measurements bring **latent transition analysis**, in which people move between classes over time, and **growth mixture** or group-based trajectory models, in which the classes are shapes of development [@collins2010; @nagin2005]. Mixed continuous and categorical indicators, counts, rankings, sequences of states, curves from sensors, and networks each have their own mixture models, surveyed in @gormley2023 and @bouveyron2019. On the algorithmic side, density-based methods such as DBSCAN find clusters of arbitrary shape without a $K$ [@ester1996], and in high dimensions the question of *which* variables to cluster on becomes a model selection problem of its own. For texts, images, and other unstructured data the current practice is to cluster embeddings produced by a neural network, which raises every question of this chapter with the added difficulty that the features are themselves learned. Chapter 12 of @james2021 covers clustering from the machine learning side; @oberski2016 is a compact introduction to latent profile and latent class analysis from the social science side, on which this chapter's treatment of mixtures draws; @hennig2015 is the guide to choosing a clustering strategy that this chapter's evaluation section follows; and @mclachlan2000 is the comprehensive reference on finite mixture models.\n\n## Test yourself {.unnumbered}\n\n::: {.callout-tip icon=\"false\" title=\"Exercise 8.A\"}\nA municipal health service wants to identify types of problematic alcohol use among 12,000 residents, combining three indicators: a survey self-report, emergency-department records, and pharmacy dispensing data.\n\n(a) Say why this three-source design supports the local independence assumption better than three survey questions would, and name one residual threat to it.\n(b) Specify a defensible procedure for choosing the number of classes, naming at least three distinct tools and the order in which you would consult them.\n(c) The four-class solution includes a class of 1.5 percent of residents with two conditional probabilities estimated at exactly zero. What do you suspect, and what three checks would you run?\n(d) The service wants to target an intervention at the highest-risk class. Which chapters' machinery does that decision invoke beyond this one's, and why?\n:::\n\n::: {.callout-note collapse=\"true\" icon=\"false\" title=\"Answer 8.A\"}\n(a) The three sources share the resident's true state but little else: survey errors come from self-presentation and recall, ED records from presentation and coding practices, dispensing data from prescription behaviour. Distinct error mechanisms make within-class independence a designed property rather than an assumption of convenience. A residual threat: all three sources may miss the same people, for example residents who avoid care entirely, which correlates the indicators within the healthy class.\n(b) Fit $K = 1, 2, \\ldots$ with many random starts; consult the BIC (and ICL) for a defensible range; run the bootstrapped likelihood-ratio test on the boundary candidates; check stability by refitting on bootstrap resamples; and weigh interpretability and class separation for the final choice, documenting the whole path rather than the winner alone.\n(c) Empirical underidentification. Check the spread of log-likelihoods across many starts; inspect standard errors around the boundary estimates; and refit with $K - 1$ classes and with the boundary parameters restricted, comparing fit.\n(d) Targeting is an intervention, so its justification is causal: the designs of @sec-rq-to-interpretation and the identification reasoning of @sec-identification. That the class predicts harm is an umbrella claim; that intervening on its members reduces harm is a rain-dance claim, in the vocabulary of @sec-explanation-prediction.\n:::\n\n::: {.callout-tip icon=\"false\" title=\"Exercise 8.B\"}\nTwo published analyses of the same national survey report latent class models of adolescent risk behaviour. Study 1 reports a four-class model with unrestricted conditional probabilities. Study 2 reports a seven-class model in which many conditional probabilities are constrained equal across classes. Both report excellent and nearly identical fit, and each claims to have found \"the\" typology.\n\n(a) Explain why the near-identical fit is not surprising, using this chapter's vocabulary and its antecedents in earlier chapters.\n(b) Neither study used multiple random starts. What specifically is at risk in each?\n(c) A reader asks which typology is true. Write the two-sentence honest answer.\n:::\n\n::: {.callout-note collapse=\"true\" icon=\"false\" title=\"Answer 8.B\"}\n(a) The two models are close to equivalent: restrictions traded against classes can leave the implied distribution of the observed responses nearly unchanged, so fit cannot separate them, just as equivalent path models fit identically in @sec-identification. The data constrain the observed distribution; the partition of that distribution into classes comes from the assumptions.\n(b) Each reported solution may be a local maximum, so the published parameters, and with them the substantive typology, might not even be the best solution of the authors' own model; and with seven classes, Study 2 is additionally at high risk of empirical underidentification, with several near-equal maxima describing different typologies.\n(c) Neither is known to be true: each is the best description of the data conditional on its own restrictions, and the data cannot adjudicate between the restrictions. What can be reported honestly is the conditional claim, together with checks, stability, external validation, design of the indicators, that make one set of assumptions more defensible than the other.\n:::\n\n::: {.callout-tip icon=\"false\" title=\"Exercise 8.C\"}\nReturn to the Old Faithful data.\n\n(a) K-means with $K = 2$ and the merged mclust solution produce nearly the same two clusters. State one substantive conclusion the mixture model licenses that K-means does not, and why.\n(b) mclust's chosen model used three components for two clusters. Explain to a non-statistician colleague why \"the algorithm found three groups\" would be a misreading.\n(c) Suppose eruptions were recorded by two different instruments, and the instrument identity were unavailable. What syndrome from this chapter should the analyst worry about, and which checks apply?\n:::\n\n::: {.callout-note collapse=\"true\" icon=\"false\" title=\"Answer 8.C\"}\n(a) The mixture model yields posterior probabilities, so it can report that eruptions near the boundary belong to either type with stated uncertainty, and it estimates the types' proportions with standard errors; K-means's hard assignments assert certainty the data do not contain.\n(b) The three normal components are the model's building blocks for describing the shape of the data's density, not necessarily the groups of interest: one banana-shaped cluster needs two ellipses to trace it. Components are vocabulary; clusters are the claim.\n(c) An unmeasured grouping variable, the instrument, can generate spurious classes or distort real ones, and within-\"type\" correlation induced by the instrument violates local independence. Stability checks across subsamples, external validation against any available metadata, and scrutiny of whether extra small classes appear with boundary estimates are the applicable defences.\n:::\n",
    "supporting": [
      "08-unsupervised-clustering-mixtures_files/figure-pdf"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{},\"value\":[]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}